### ISSUE TITLE
issue: Array of error messages returned from `validate` function is neglected

### ISSUE THREAD

**Issue by vovkvlad** [react-hook-form/react-hook-form#10145]
### Version Number

7.43.6

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-validate-array-return-tqf3qi?file=/src/App.js

### Steps to reproduce

1. Create any simple form with one input and custom validate function.
2. Return an array of error messages from validate handler
3. See that `formState.error.<field_name>` has error of type `validate` and empty `message` property

### Expected behaviour

And array of error messages to be returned in `message` property.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vovkvlad** [comment]
@bluebill1049 not really got your point point:
- what do you mean by `how to support type check`?  (As far as I saw from types validate method types already support `Message` or `Message[]` return type. Haven't checked `formState.error` types yet though)
- what's JSX has to do with return type for `validate` function?

Would it be to complicated/incorrect from design perspective to just return `string[]` in `error.<field_name>.message`?
Or do you have other plan in mind? I could try to take a look at my spare time

**Comment by bluebill1049** [comment]
> what do you mean by how to support type check? (As far as I saw from types validate method types already support Message or Message[] return type. Haven't checked formState.error types yet though)

I think this got introduced by @jorisre a couple days ago for the resolver package, we didn't have this support but we maybe able to look into it.

> what's JSX has to do with return type for validate function?

because you can return JSX, but we couldn't do it because it would require the user to type assert the message.

> Would it be to complicated/incorrect from design perspective to just return string[] in error.<field_name>.message?
Or do you have other plan in mind? I could try to take a look at my spare time

As this change made by @jorisre just a couple of days ago https://github.com/react-hook-form/react-hook-form/commit/ab31da3732b4e205cb3a846a229549478e709c3d I am not in a hurry to support it however, open for PR if this is something required for your usage.

**Comment by bluebill1049** [comment]
Going to move this into the feature request board instead.
