### ISSUE TITLE
issue: When using with `useSyncExternalStore`, form data may not be set by `reset`.

### ISSUE THREAD

**Issue by fneco** [react-hook-form/react-hook-form#10248]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/drafts-react-hook-form-but-report-9w4frb

### Steps to reproduce

1. Go to https://codesandbox.io/s/drafts-react-hook-form-but-report-9w4frb
2. Click on 'set name'
3. The form value become 'bill' as you see it
4. Click submit button, then you see that the form data is `{ "name": "no name" }`

### Expected behaviour

1. Go to https://codesandbox.io/s/drafts-react-hook-form-but-report-9w4frb
2. Click on 'set name'
3. The form value become 'bill'
4. Click submit button, then you see that the form data is `{ "name": "bill" }`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fneco** [comment]
Thank you for creating and maintaining this amazing library!

I found this issue when I update react-redux to v8 which use `useSyncExternalStore` internally. 
Here is a reproduction using react-redux.
https://codesandbox.io/s/drafts-react-hook-form-but-report-with-react-redux-qo89wg

**Comment by leapful** [comment]
@fneco @bluebill1049 

It seems to be related to batch rendering issue https://github.com/facebook/react/issues/25191 where the previous default value `{ name: 'no name' }` is being kept on rendering phase for `counter.increment()`.

Move `counter.increment()` to where event handler of changing default value will make behave normal. I would recommend this way instead of update data from `useSyncExternalStore` inside `useEffect`.

Working demo: https://codesandbox.io/s/drafts-react-hook-form-but-report-forked-zmg5ql?file=/src/App.js

**Comment by bluebill1049** [comment]
Thanks, @leapful I am also a bit hesitant to merge that PR even it's consider to be a limitation.

**Comment by bluebill1049** [comment]
Thanks @fneco for the additional context, we may leave react to sort this out for us.
