### ISSUE TITLE
Append to field array after submission makes fields get validated

### ISSUE THREAD

**Issue by khuongtp** [react-hook-form/react-hook-form#10251]
### Version Number

^7.43.8

### Codesandbox/Expo snack

https://codesandbox.io/s/calc-forked-k7ie27?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/calc-forked-k7ie27?file=/src/App.tsx
2. Click on SUBMIT
3. Click on APPEND 
4. See the newly added item gets validated

### Expected behaviour

Newly appended items should not be validated because they're not touched

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
type="button"

**Comment by khuongtp** [comment]
I think you get it wrong, it's not the type attribute, what i want is there should be no errors from the fieldState of the Controller when you add an new item after submitting the form, in v7.43.0, it seems fine
![image](https://user-images.githubusercontent.com/62872729/231339287-514afcf1-c662-43ac-822a-a735df7e6a19.png)
Notice the first row, it has errors because I clicked submit, then I append 2 more which have no errors

**Comment by BillyLevin** [comment]
Hi @bluebill1049 I agree that this appears to be a bug. To clarify what the issue is:

1. Set up a dynamic field using `useFieldArray()`
2. Try to submit the form without filling in required fields - you will see validation errors, which is correct behaviour
3. If you then try to append some fields to the form, these new fields immediately have validation errors, even though they haven't been touched yet. This seems to be incorrect behaviour as it's pretty bad UX

I am also having this issue on v7.43.8

**Comment by kambing86** [comment]
it seems like if you put in `type="button"` to your `button` component then issue gone, but I don't understand why we need to do that

@bluebill1049 does that mean we cannot use any other thing other than `button with type="button"` to append?
