### ISSUE TITLE
Have multiple errors when required field is empty pls :)

### ISSUE THREAD

**Issue by miguelSoldado1** [react-hook-form/react-hook-form#10277]
**Describe the bug**
This might be a bug but I feel like it's an actual feature because it seems like the usual error handling in most forms. Basically I need to build a form where I'm required to show multiple errors when field is empty. I know of the "criteriaMode" : "all" option but when the field is empty and it's required instead of showing all the errors that the input might have it only shows the required error message. In my sandbox example I have a simple use case where I would be required to show both the "required error message" and the "pattern not recognized error message". Hopefully this case could be an option in the form options (maybe another criteriaMode option).  

**To Reproduce**

Go to the sandbox: https://codesandbox.io/s/react-hook-form-feature-request-425mdm
Click on the submit button.
Notice it only shows "Field is required." when the input is empty and "Not an email." when the pattern is not recognized.
I would like to show both the "Field is required." and "Not an email." errors when the input is empty.
P.S: Sorry for the ugly unstyled layout :)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-feature-request-425mdm

**Expected behavior**
Show all error messages in all cases.

**Additional context**
Using react-hook-form v7.43.9

**Comment by leapful** [comment]
@bluebill1049 @miguelSoldado1 

I think the reason of this behavior is from `isEmpty` as fail fast checking from https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/validateField.ts which only allow validate other rules like `pattern`, `maxLength`, `minLength` ... if value is not falsy.

A workaround for this case is to use `resolver` option or `validate` custom rule handler to perform validation instead of built-in validator from react-hook-form.

**Comment by bluebill1049** [comment]
thanks @leapful i am fixing it 👍

**Comment by bluebill1049** [comment]
Going to revert this commit, for pattern we will need to check is empty.
