### ISSUE TITLE
issue: Controlled input doesn't register when conditionally mounted

### ISSUE THREAD

**Issue by hichemfantar** [react-hook-form/react-hook-form#10386]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-watch-render-bug-krzkow?file=/src/index.js

### Steps to reproduce

1. Set Show age to true
2. Open devtool
3. Age field is rendered but not registered in form state
4. Press rerender button
5. Age field is now visible in devtool

### Expected behaviour

Age input should register automatically when mounted

### What browsers are you seeing the problem on?

Firefox, Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanduluca** [comment]
This is happening because of [React StrictMode that trigger useEffect twice ](https://blog.ag-grid.com/avoiding-react-18-double-mount/). If you remove the React.StrictMode the Controlled input behave as expected.
```jsx
<React.StrictMode>
    <App />
</React.StrictMode>
```

To test the problem react 18 is required and <React.StrictMode> should be added. 

The problem is here: https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L72-L77


1. Ref is created with the  input registration + Mounted
2. Unmounted (cleanup function unregister the input)
3. Ref was already created and it doesn't register it again

A fix can be input registration on mount:
```tsx
  const _registerProps = React.useRef<UseFormRegisterReturn | null>(null);
  React.useEffect(() => {
    _registerProps.current = control.register(name, {
      ...props.rules,
      value,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

**Comment by bluebill1049** [comment]
thanks for looking into this @sanduluca I don't follow his (author's) csb, why would this cause an issue? if a controller gets mounted the name is meant to be cached.

**Comment by bluebill1049** [comment]
while `shouldUnregister` is convenient but it's not perfect, especially in strict mode, if this causes your the issue, call unregister manually.

**Comment by hichemfantar** [comment]
I'll try the manual unregister approach but it'd be great if this was fixed because it seems like a legit bug with unintended behavior.
What do you think of @sanduluca 's fix?

**Comment by bluebill1049** [comment]
I don't think we will go ahead with that fix.

**Comment by hichemfantar** [comment]
Is there something wrong with the proposed solution by @sanduluca ?
I think he may be right because the bug only happens with controlled inputs.

**Comment by hichemfantar** [comment]
@bluebill1049 I'm not sure if I should open a new issue because the bug is still present after your commit #10418
