### ISSUE TITLE
isValid not always updated as expected

### ISSUE THREAD

**Issue by Mindaugas-Jacionis** [react-hook-form/react-hook-form#10437]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/sad-aj-6mrkvq?file=/src/index.js

### Steps to reproduce

1. Change input value by 1 char (add 1 or delete 1)
2. Submit button stays disabled
3. Change input value by 1 more char (add 1 or delete 1)
4. Submit button becomes enabled

### Expected behaviour

After step 1 button is supposed to become enabled. It shouldn't need 2 onChange events. 
Issue seems to be with `isValid` value, and becomes visible only when combined with some other value from formState, i.e. common case when form not only needs to be valid, but also changes to it need to be done (common when loading prefilled forms).

[Attached codesanbox](https://codesandbox.io/s/sad-aj-6mrkvq?file=/src/index.js) contains not only sample of issue, but also commented out example that uses destructuring to read values from state before using them in component conditional logic. Use case with destructuring works.

### What browsers are you seeing the problem on?

Chrome: 113.0.5672.134  
Safari: 16.4  
Firefox: 113.0.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
This behavior is expected. The `formState` object is intentionally designed as a `Proxy` object for optimization purposes. In order to make each individual state reactive, you need to first read the form state value, which will allow you to subscribe to it.

For more information, please refer to [the "Rules" section](https://react-hook-form.com/docs/useform/formstate#rules) of the `formState` documentation page.
