### ISSUE TITLE
issue: With field array virtualised list and controller, input focus is lost on revalidation.

### ISSUE THREAD

**Issue by rahul-keyValue** [react-hook-form/react-hook-form#10502]
### Version Number

7.38.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-virtual-inputs-forked-2jbxe4?file=/src/App.js:967-973

### Steps to reproduce

-  Click on the sandbox shared.
- Click the submit button, all the fields are required as of now, an error will be shown as fields are required
- Now start filling in the error field
- Focus on the input is lost as soon as the user type in the first character in the input.
-  I need to click the input button again to fill in the rest of the characters.

### Expected behaviour

- Focus isn't lost when typing in the requied field, at any point, even when revalidation is happening.
required

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This probably going to be quite difficult to manage, imagine if you have an error out side the virtual list. It's impossible for us to focus on that input. I would almost consider this as design limitation for this lib.

**Comment by rahul-keyValue** [comment]
Thanks for the reply @bluebill1049 .

**Comment by kotarella1110** [comment]
@rahul-keyValue 

The loss of focus occurs because the `FixSizeList` component is being re-rendered. When `formState` is used, the entire `List` component that utilizes `useForm` is re-rendered, consequently causing the `FixedSizeList` component to be re-rendered as well. The solution to avoid this is to use `fieldState`. Please refer to the following CodeSandbox for more details.

https://codesandbox.io/s/react-hook-form-usefieldarray-virtual-inputs-forked-f1ng1n?file=/src/App.js
