### ISSUE TITLE
issue: field-array-level validation errors not sent to the formState when blurring array items' inputs

### ISSUE THREAD

**Issue by jkatofskyCoveo** [react-hook-form/react-hook-form#10776]
### Version Number

7.43.9

### Codesandbox/Expo snack

https://codesandbox.io/s/rhf-bug-rzx4sz

### Steps to reproduce

I want to have a validation that all strings in a field array are URLs with the same domain...

1. Change one of the two URLs to have a new domain
2. Blur (click outside) the text input for that URL
4. Notice that the error does not end up in the `formState` (we get nothing displayed after `Array-level errors:`)
5. Then, click `Manually validate` , which does a `trigger` of the whole form, and see that the multiple domains error now gets sent to the `formState` (the message is displayed after `Array-level errors:`)

### Expected behaviour

Unless I am missing something about the expected behaviour of the form when `mode == "onBlur"`, the multiple-domains error should be appearing in the form after step 2.

Some sanity-checks to further demonstrate the issue:

- See via the console logs that in _both the case of the blur, and the manual validation_, the `refine` is properly executed and is passed the correct `urls`.
- See that _array-item-specific validation on blur is working fine_ by deleting the URL from an input entirely, blurring it, and noticing that we get the empty-string error after `Error for this input:`.
- When adding `onBlur={() => trigger()}` directly on the inputs, the issue goes away.
- We can also see that this is not an issue with the validation schema library, or a specific resolver, since the exact same behaviour happens when using `zod` or `superstruct` for the validation in the CodeSandbox.

So there really seems to be an issue with sending field-array-level errors to the form, _specifically onBlur of specific items_.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
field array level only occurred at the action level (append, prepend and etc).

**Comment by lauriharpf** [comment]
Thank you for your work on this excellent library! 🙏 I'm facing an issue that seems similar to @jkatofskyCoveo's report.

> field array level only occurred at the action level (append, prepend and etc).

Unfortunately I can't understand this as I'm not that familiar with `react-hook-form`. Can you give a more detailed answer on what is happening and how to achieve the functionality @jkatofskyCoveo would like to have? E.g. forking https://codesandbox.io/s/rhf-bug-rzx4sz and changing it so that the desired functionality is achieved could be a good way to illustrate.

I notice the `useFieldArray` use in the Codesandbox and have read through https://react-hook-form.com/docs/usefieldarray but these alone don't clarify things enough for me.

> See that array-item-specific validation on blur is working fine by deleting the URL from an input entirely, blurring it, and noticing that we get the empty-string error after Error for this input:.

I can otherwise reproduce the issue with the Codesandbox but cannot reproduce this behaviour (with Chrome): After deleting the URL and blurring nothing appears after "Error for this input:". Can @jkatofskyCoveo double-check, did I perhaps just miss something in the report?

**Comment by jkatofskyCoveo** [comment]
> field array level only occurred at the action level (append, prepend and etc).

@bluebill1049 I don't fully understand your comment 😅 - is there a particular follow-up you are asking for?

This is definitely what is happening, but the behaviour is not intuitive to me. Why should an error returned by the validation schema be ignored by the form, simply because the event which triggered validation is not at the array level? I can imagine that there are many use cases for having an array-level validation error that is computed whenever an individual array element is modified.
