### ISSUE TITLE
How to use react hook form with ckeditor !

### ISSUE THREAD

**Issue by Temkit** [react-hook-form/react-hook-form#1077]
**Describe the question?**

How to integrate ckeditor ! ( Is it possible to Integrate it )

**To Reproduce**

I tried the simple integration way, and also tried with React Hook Form Input can't capture the value of the editor !

**Comment by bluebill1049** [comment]
I never used ckeditor, but you can `register` at `useEffect` and `setValue`.

**Comment by iamSonBK** [comment]
@bluebill1049 so, how can I get data from CKEditor with that ? I tried find in object of data.input but I cant see where is value

**Comment by iamSonBK** [comment]
@bluebill1049  I got solution, If you want to get value from your CKeditor, you should get editor in onChange, like that
`onChange={(value, editor) => setValue("input", editor.getData())}`
because, value in onChange of CKeditor, that like event in onChange of <input />

**Comment by JeomJeom** [comment]
@bluebill1049 
formState seems not tracking the value from the CKEditor. How can I track the input value from CKEditor in the formState of the React-hook-form?

**Comment by meshackjr** [comment]
@bluebill1049 You can use trigger api to manually validate each time there is a change on the ckeditor;

```
useEffect(() => {
  register('input');
})

<CKEditor 
  onChange={( event, editor ) => {
        setValue('input', editor.getData());
        trigger('input');
    }}
/> 
```

**Comment by jeremy8883** [comment]
I guess the problem with the solutions above is that they don't allow features such as auto blur on error, initial field values, or the ability for fields to update the values based on RHF's `setValue` and `reset` calls. Or am I missing something?

I created a wrapper component, replicating the DOM APIs that RHF relies upon.

```
export const FormattedTextBoxRhfWrapper = forwardRef(
  ({ onReady, onChange, onBlur, name, ...rest }: Props, ref) => {
    const domElementRef = useRef(null);
    const componentRef = useRef(null);
    useImperativeHandle(
      ref,
      () => ({
        focus: () => {
          domElementRef.current?.focus();
        },
        select: () => {
          domElementRef.current?.select();
        },
        set value(val: string) {
          componentRef.current?.setValue(val);
        },
        get value() {
          return componentRef.current?.getValue();
        },
        type: "formatted-text-box",
        name,
      }),
      [name]
    );

    const handleChange = (value: string) => {
      if (!onChange) return;

      onChange({
        target: {
          name: name,
          value: value,
        },
        type: "change",
      });
    };

    const handleBlur = (value: string) => {
      if (!onBlur) return;

      onBlur({
        target: {
          name: name,
          value: value,
        },
        type: "blur",
      });
    };

    const handleReady = editor => {
      domElementRef.current = editor.sourceElement;

      if (onReady) {
        onReady(editor);
      }
    };

    return (
      <MyCkEditorImplementation
        onReady={handleReady}
        onChange={handleChange}
        onBlur={handleBlur}
        ref={componentRef}
        {...rest}
      />
    );
  }
);
```

This would allow me to spread `register` into the wrapper component, as you would for any regular input field. Although I wouldn't call `register` until the `onReady` callback has been called though, otherwise, CKEditor may not have finished initializing yet, which would lead to errors. Eg.

```
const { register } = useFormContext();
const [isCkEditorReady, setIsCkEditorReady] = useState(false);
const registeredField = isCkEditorReady ? register(fieldPath) : {};

const handleReady = () => {
  setIsCkEditorReady(true);
};

return <FormattedTextBoxRhfWrapper onReady={handleReady} {...registeredField} />
```

Then at the bottom level, `MyCkEditorImplementation` would include all configurations etc, to get CKEditor working to our liking. It would also provide the imperative functions `setValue` and `getValue`, which are required by `FormattedTextBoxRhfWrapper`.

The `MyCkEditorImplementation.setValue` function also does a `if (newValue !== oldValue) {` check before actually setting the value, so we don't unnecessarily update the CKEditor state. Every time a validation error would show or hide, or if we blurred away from the text field, a call to `MyCkEditorImplementation.setValue` was unnecessarily being made, leading to glitchy behaviour with CKEditor. I don't think this should be required, and I haven't yet looked into if this was an issue on our side or not.

We haven't done a complete QA of the above code yet, but upon initial tests, it seems to work well. Granted, I'm worried that there's a slight risk that this implementation may not work with future versions of `react-hook-form`. Is there a more blessed way to integrate with a component like CKEditor, where imperative getters and setters are available?
