### ISSUE TITLE
Watch behaviour varies on useFieldArray

### ISSUE THREAD

**Issue by benswinburne** [react-hook-form/react-hook-form#1078]
**Describe the bug**
The output of `watch` is inconsistent between actions and depending on what you're watching.

**Watching all fields (whole form)**

This starts off with 1 structure (nested) from default values but then on input changes to a path based key structure. It should probably convert the defaults before being used for consistency?

This also has an issue whereby removal of the last field is not reflected, it simply reverts to the defaults.

**Watching a specific field by name**

This start off with no ids (because the defaults didn't have them) but then if you append/prepend etc it adds ids on, fine. However, if you then type into one of the fields, the ids disappear from the watch result (this may not be a bug but just seemed odd so thought worth mentioning)

**Watching all fields with nest: true**

This matches the structure from the default values but in the same way as watching not nested, the removal of the last field reverts to defaults, not to empty.

**To Reproduce**
Steps to reproduce the behaviuor:
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nefw4?fontsize=14&hidenavigation=1&theme=dark
2. Type more into existing field and observe structure of watched value change
3. Append a field and watch specific field structure get items as expected (note new field absent from watched form)
4. type more into appended field and watch watched field structure change and lose ids

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-nefw4?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
I'd expect the removal of the last item to update the value to [] instead of reverting to defaults.

**Screenshots**
![image](https://user-images.githubusercontent.com/1208977/75056693-6eacc000-54cf-11ea-8695-82334649ee1f.png)

**Comment by bluebill1049** [comment]
hey, @benswinburne thanks for the detailed issue report. This is actually an expected result. I think there is something missing in the doc which I should update.

`watch` with field array is challenging for uncontrolled input because there is no such concept of state,  `watch` was meant to made work for input change and reflect what's the user is typing and interaction. however, I do understand often people want to have a conditional input-based approach inside field array, so I made a specific fix (workaround) when you watching the Field Array (useFieldArray). I would suggest isolating your watch to specific fields, otherwise, it's almost losing the point of RHF's performance benefit. 

please give me a suggestion on how to improve this in the doc, so things can be more clear.

**Comment by bluebill1049** [comment]
Here is the updated documenation:

<img width="930" alt="Screen Shot 2020-02-22 at 12 55 58 pm" src="https://user-images.githubusercontent.com/10513364/75084208-b0db0d80-5572-11ea-81c8-2f2e138bbf1d.png">

**Comment by bluebill1049** [comment]
Deploying the docs update to the website.

**Comment by bluebill1049** [comment]
let me know if you have more questions or concerns.
