### ISSUE TITLE
issue: Wrapping a (MUI) <Radio /> within another React component disables its selection

### ISSUE THREAD

**Issue by MMF2** [react-hook-form/react-hook-form#10868]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-controller-v5-ii1vs?file=/src/index.jsx

### Steps to reproduce

Modify the code of index.jsx in the sandbox in the following way:

1. Insert the definition (inside or outside the App component, no difference in effect)
`const WrappedRadio = () => <Radio />;`

2. Replace (line 78 in the unmodified file, the radio button for "Female" ) `<Radio />` with `<WrappedRadio />`

Observed behavior: The "Female" button cannot be selected any longer (the "Male" button with its original `<Radio />` still can be selected).

This is a minimal example that doesn't make sense, of course. My intention was to modify the radio button within the WrappedRadio component, e.g. to modify its color.

### Expected behaviour

There should be no difference in behavior between `<Radio />` and `<WrappedRadio />`. In particular, the radio button rendered by the latter should remain selectable.

### What browsers are you seeing the problem on?

Firefox, Vivaldi (Chrome) - Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The issue is unrelated to RHF. MUI's using [`composition`](https://mui.com/material-ui/guides/composition) to make some of the parent -> child component as prop functionality which heavily relies on [`ref`](https://react.dev/learn/manipulating-the-dom-with-refs) usage. By "wrapping" your component without [`forwardRef`](https://react.dev/reference/react/forwardRef), you disconnect the child components from their parent resulting in the loss of functionality.

You can read more about the composition approach and it's caveats [in the MUI docs](https://mui.com/material-ui/guides/composition/#caveat-with-refs).

In your case, the "fix" would be
```diff
- const WrappedRadio = () => <Radio />;
+ const WrappedRadio = forwardRef((props, ref) => <Radio ref={ref} {...props} />);
```

**Comment by MMF2** [comment]
Thank you very much.
