### ISSUE TITLE
Add setSubmitting function

### ISSUE THREAD

**Issue by StKostyantin** [react-hook-form/react-hook-form#1096]
In the documentation I did not find an example of how to control isSubmitting.

[Formik has setSubmitting functionality](https://jaredpalmer.com/formik/docs/api/formik#setsubmitting-issubmitting-boolean--void)

I need to manually specify isSubmitting = false. Because I use redux-saga and my requests are sent through the store.

```
<FormContext {...methods}>
        <Form onSubmit={methods.handleSubmit(handleSubmit)} layout="vertical">
```

Here is the handle I use with formik:
```
 const handleSubmit = values => {
    onLogin({
      payload: values,
      onSuccess: () => {
        Router.push('/');
      },
      onError: rej => {
        setErrors(rej);
      },
      onFinally: () => {
        setSubmitting(false);
      }
    });
  };
```
There is an opportunity to get around this by writing this action to a promise. But I think this is not a very elegant solution.

**Comment by bluebill1049** [comment]
In React Hook Form, it's happening automatically, you can subscribe to formState isSubmitting.

**Comment by StKostyantin** [comment]
> In React Hook Form, it's happening automatically, you can subscribe to formState isSubmitting.

Yes I know)
But I need the ability to manually control this state, because if you look at my example, then I use callbacks to transfer data from the saga to my component.
When the action is triggered, the state changes to false without waiting for the saga to complete.

**Comment by bluebill1049** [comment]
i don't think we will add such function, you will have to use await inside `handleSubmit`.

**Comment by StKostyantin** [comment]
> i don't think we will add such function and have no plan to expand our API, you will have to use await inside `handleSubmit`.

I can’t just write await to wait for the fork saga query.
This needs to be done through a promise and yes it is real, but it adds an extra 5 lines of code to each request, which could be done with one of the APIs.

```
const handleSubmit = async values => {
    try {
      await new Promise((res, rej) => {
        onLogin({
          payload: values,
          onSuccess: () => {
            res(Router.push('/'))
          },
          onError: err => {
            rej(err)
          }
        });
      })
    } catch (e) {
      setErrors(e);
    }
  };
```


But all the same, thank you very much for the answer, I really like this library)

**Comment by bluebill1049** [comment]
hey @StKostyantin sorry for not accepting the feature request... trust me the last thing i want to do is to deny someone's feature request while still remain the lib to be simple. it's a tradeoff that i have to take sometimes... hope you will understand. 🙏

**Comment by m5nv** [comment]
@bluebill1049 Let me know if this needs to be a new issue. My situation is related. 

Currently moving from Formik to React Hook Form. The porting of functionality was a breeze, compared to writing stuff in Formik almost a year ago. The issue is my tests that pass with Formik are failing. 

I am using redux-thunk to handle remote server calls. On success, I navigate away from the `login` page, and on error I use Formik's `setStatus` method. Which is then used to display server errors. Please note that the server messages do not necessarily map to form fields - security best practices suggest not to give away which field is in error; which means I can't use RHF's `setError` function.

To understand the use case, it is better to quote Formik's [setStatus](https://formik.org/docs/api/formik#setstatus-status-any--void) documentation than me rehashing it.


> A top-level status object that you can use to represent form state
> that can't otherwise be expressed/stored with other methods. 
> This is useful for capturing and passing through API responses to
> your inner component.
>
> **status should only be modified by calling setStatus**.

It comes in handy when dealing with server responses that need to be taken into consideration when rendering the form.

The code base for context can be found [here](https://github.com/million-views/praas/blob/master/praas-app/src/store/user/login.js#L41-L58). 

I mocked the callbacks (to Formik's setStatus that were getting passed in `actions`) by using useState. Trouble is react-testing-library is not finding the text I am looking for. I then directly accessed the errors held in redux store (using `useSelector`) and even then I am unable to find the text. 

The reason I think is because react testing library is not waiting for the `rerender` that happens after the server response arrives. But this was not an issue when using Formik because the `errors from remote` where managed by it.

I am out of ideas. Any guidance on how to move forward will be helpful. Here is one of the [tests](https://github.com/million-views/praas/blob/master/praas-app/src/app/pages/login.test.js#L100-L112) that is failing, all others are failing for the same reason. 

```code
  it('should display error message on login failure', async () => {
    renderPage();
    const { email, password, submit } = subjectsUnderTest();

    userEvent.type(email, 'tester@testing.paradise');
    userEvent.type(password, 'password');
    userEvent.click(submit);

    await waitFor(() => {
      const serverError = screen.getByText(/email or password is invalid/i);
      expect(serverError).toBeInTheDocument();
    });
  });
 ```

Thanks for your time in advance!

**Comment by bluebill1049** [comment]
@m5nv react hook form auto-trigger submitting `formState` when user clicks on the submit button. curious why would you need `setStatus`?

**Comment by m5nv** [comment]
> @m5nv react hook form auto-trigger submitting `formState` when user clicks on the submit button. curious why would you need `setStatus`?

Because the "Email or password is invalid" message is set after the response from the server is received `asynchronously`, after `submit`ing. The form then displays this message which is outside the fields div. 

This works in Formik, because I suspect the `status` changed (when the server response was received and set in `redux-thunk`), and thus React decides to `rerender` the form because of this. Fwiw, the redux-thunk for login looks as below:

```code
export const loginUser = (user, actions, navigate) => {
  return (dispatch) => {
    dispatch({ type: LOGIN_REQUEST, payload: user });
    PraasAPI.user.login(user).then(
      (data) => {
        localStorage.setItem('user', JSON.stringify({ ...data.user }));
        dispatch(loginUserSuccess(data.user));
        actions.setSubmitting(false);
        navigate('/');
      },
      (error) => {
        dispatch(loginUserFailure(error));
        actions.setSubmitting(false);
        actions.setStatus({ errors: { ...error.errors } });
      }
    );
  };
};
```

When the server response comes back, Formik's `setStatus` is called which is then used in the form as below:
```
...
...

  return (
    <Form>
      <h2>Login to your account</h2>
      {
        {/* the test is looking for this message from the server which was set in redux upon request completion */}
        {/* not to be confused with validation `errors` which is per field  */}
        status && <Alert klass="alert-danger" message={status.errors} />
      }
...
...

    </Form>
  );
```

**Comment by bluebill1049** [comment]
`isSubmitting` is async.

```
const onSubmit = async () => {}

formState.isSubmitting // will be true after user click on the button

formState.isSubmitting // will be false after onSubmit function is resolved.

```

**Comment by bluebill1049** [comment]
I would recommend you try it out in a codesandbox @m5nv

**Comment by m5nv** [comment]
@bluebill1049 Thanks for your time. 

I am going after the ability to associate an `application-state` with the Form component that can be set asynchronously, which is what `setStatus` from Formik provides. 

To be sure, my application is working correctly (after modifying code to fit the RHF design pattern). While it could be made simpler, that is not the issue I am reporting.

I am having trouble with tests failing and I have no clue why because the same tests pass with Formik.

Anyway I managed to reproduce this issue using an example you provided in one of the chats on Spectrum.
Again, the app itself is working fine in browser. 

Specifically any test that looks for an `appearance` of an element after a form submission fails.  Please take a look at my [codesandbox](https://codesandbox.io/s/epic-minsky-q4jw0)  and let me know if you spot something that is not correct.

PS: I have not managed to run the tests in codesandbox, not sure if it is a premium feature. But the code unmodified will reproduce the error on CLI.

**Comment by bluebill1049** [comment]
Did you take a look at this section: https://react-hook-form.com/advanced-usage#TestingForm?

also, there are plenty of tests in the repo, you can probably just refer to as well.

**Comment by m5nv** [comment]
I did. In fact this [sample I uploaded to codesandbox](https://codesandbox.io/s/epic-minsky-q4jw0) is from that section, modified to look closer to my tests. I first verified that your code works as is, then I modified it to use `userEvent` instead of `fireEvent`, and finally added a test case that demonstrates the class of test failures I see in my current project after migrating to React Hook Form.

Fyi, here is the output:
```
  App
    ✓ should display required error when value is invalid (107 ms)
    ✓ should display matching error when email is invalid (87 ms)
    ✓ should display min length error when password is invalid (51 ms)
    ✓ should display no errors AND reset when accepted by server (118 ms)
    ✕ should NOT reset AND display server validation errors (1048 ms)
```

Have been at it for a couple of days now. I am too dumb to figure out what I am missing. The fact that these tests work with Formik is throwing me off. Will keep digging. Anyway now that the [example is in place](https://codesandbox.io/s/epic-minsky-q4jw0), I am hoping more eyes can look at whatever it is I am doing wrong and let me know.

Thanks!

PS: the example code can also be [forked from github](https://github.com/m5nv/hftl)

**Comment by bluebill1049** [comment]
@keiya01 (our testing master) would you be able to spot this issue?

**Comment by keiya01** [comment]
@bluebill1049 Sure. I will check this issue :)

**Comment by bluebill1049** [comment]
ty @keiya01 🙏

**Comment by keiya01** [comment]
Hey @m5nv, sorry for delay. But I fixed this problem.

Probably,  `jest.fn()` need to be initialized every time. Therefore, you should declare `mockLogin1` and `mockLogin2` in every `it()` `test()` or `beforeEach()`.

Here is example https://github.com/keiya01/hftl/blob/master/src/App.test.js#L118

**Comment by bluebill1049** [comment]
Thanks very much @keiya01 🙏

**Comment by m5nv** [comment]
@keiya01 Thank you so much. That indeed fixed the issue. @bluebill1049 Thank you!

**Comment by m5nv** [comment]
Just as note to myself I can't use beforeEach because I need to be able to `reject` or `resolve` depending on the nature of the test. Again, I want to thank @keiya01 for resolving my issue. I learned something about Jest!

**Comment by bluebill1049** [comment]
yea @keiya01 is our wizard for testing. 🧙
