### ISSUE TITLE
issue: incorrect isDirty values in formGroups

### ISSUE THREAD

**Issue by marit970** [react-hook-form/react-hook-form#11055]
### Version Number

7.47.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/react-hook-form-disabled-dirty-forked-wxx2hm

### Steps to reproduce

1. Type something in one of the textInputs
2. Note that instead of the other field being disabled, both fields are disabled now

### Expected behaviour

In our use case, we are using multiple groupForms with inputs and want the other group/input to be disabled once the user has started to type something in one of the input fields. I have tried to reproduce this behaviour and created a minimal example with two fromGroups('name' and 'state') with a text input inside each group. When the user types something in the 'name'-field, the other one ('state') should be disabled. And the other way around, when typing something in 'state', 'name' should be disabled respectively. Instead of this, both fields are disabled when starting to type something in one of the fields because of incorrect isDirty values.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`useFormGroup` is not part of hook form API.

**Comment by slax57** [comment]
Indeed `useFormGroup` is a hook provided by react-admin.

However, to me, this issue finds its root in this library I'm afraid.

More precisely, it's consecutive to this PR: https://github.com/react-hook-form/react-hook-form/pull/10805

From what I can tell, since this PR, any field with `disabled` set to `true` will be considered dirty.
This is clearly visible by comparing these two sandboxes: [RHF v7.45.4](https://codesandbox.io/s/react-hook-form-disabled-dirty-m0d4xo) and [RHF 7.47.0](https://codesandbox.io/s/react-hook-form-disabled-dirty-forked-7gv8vr)

To be honest, I don't understand why that change was made.
Why consider a disabled field as dirty?

If I'm correct and this change was not intended, could you revert it?
If I'm wrong, would you care to explain why this change was made?

Thank you so much.

**Comment by slax57** [comment]
Indeed `useFormGroup` is a hook provided by react-admin.

However, to me, this issue finds its root in this library I'm afraid.

More precisely, it's consecutive to this PR: https://github.com/react-hook-form/react-hook-form/pull/10805

From what I can tell, since this PR, any field with `disabled` set to `true` will be considered dirty.
This is clearly visible by comparing these two sandboxes: [RHF v7.45.4](https://codesandbox.io/s/react-hook-form-disabled-dirty-m0d4xo) and [RHF 7.47.0](https://codesandbox.io/s/react-hook-form-disabled-dirty-forked-7gv8vr)

To be honest, I don't understand why that change was made.
Why consider a disabled field as dirty?

If I'm correct and this change was not intended, could you revert it?
If I'm wrong, would you care to explain why this change was made?

Thank you so much.

**Comment by bluebill1049** [comment]
I am happy to talk about it. If an input gets set to an empty value, it's considered dirty in RHF. In this case, if an input get disabled the value will be set to undefined which changes from the origin value.

**Comment by slax57** [comment]
Thank you very much for your answer.
I must admit this behaviour was a bit surprising to me (not submitting the input when it is disabled), but looking into it, it seems that this is the case with default html forms too ([source](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)).
Hence I agree that it can make sense to implement it this way.
You may close this issue. Thank you again so much for taking the time to explain.

**Comment by ghost91-** [comment]
Hey there,

let me try to elaborate a bit on our use case:

We have a form where you are only allowed change one specific input, or a set of others. So far, we have been solving this by putting these inputs into 2 different form groups (from React Admin), and then react to their dirty state: If one form group is dirty, we disable all inputs in the other one, to prevent those other inputs from being changed.

With the current behavior of marking a field as dirty when it becomes disabled, this use case completely breaks: Changing an input results in it becoming dirty, then our logic disables the other form group, then (due to the changes in react-hook-form), the other form group is also considered dirty, and then our logic disables the first form group and we end up with all inputs being disabled.

I'm not sure about the functionality in just RHF, but at least with React Admin, when disabling an input and then submitting the form, the value that is actually submitted is not `undefined`, but the original value (otherwise, this would not have worked for us at all). So from that perspective, deactivating the inputs we want to prevent from being changed makes total sense. If that's not how RHF behaves on its own, and it instead sets the value to `undefined`, I at least understand where you are coming from and why it kind of makes sense to do it like this in RHF.

But that doesn't change the fact that our use case is now broken. Do you have any ideas/suggestions how to achieve the same (or similar) functionality with the new behavior of RHF? Or is this simply not supported at all by RHF?

@slax57 Do you have any suggestions how we could work around this with React Admin? Maybe we were missing another more obvious solution to the problem?

**Comment by slax57** [comment]
@ghost91- can you try setting the input as `readOnly` instead of `disabled`?

**Comment by ghost91-** [comment]
@slax57 There doesn't seem to be a `readOnly` prop for React Admin's input components. It seems to work if we use the `useInput` hook to create a custom input component, but that's not really an option since we heavily rely on React Admins input components. Recreating all of them would be a huge task.

**Comment by slax57** [comment]
@ghost91- I'm sorry but I see no obvious solution right now, only possible workaround ideas that would require some testing to make sure they work.
For instance you can try [resetting the field](https://react-hook-form.com/docs/useform/resetfield) when it is disabled to force its state going back to pristine.
