### ISSUE TITLE
issue: wrong type for ControllerFieldState.error for fieldArray

### ISSUE THREAD

**Issue by sKopheK** [react-hook-form/react-hook-form#11202]
### Version Number

7.48.2 (as you can see in codesandbox, i'm running 7.39.7 in my project with the same result)

### Codesandbox/Expo snack

https://codesandbox.io/s/trusting-voice-287f6c?file=/src/App.tsx

### Steps to reproduce

hi,
in case of field array, `ControllerFieldState.error` type should include errors for each item as well as root error for the whole field (which does now). as you can see in the codesandbox it can be array of multiple FieldError items

error type is incorrect - a single error
![imagen](https://github.com/react-hook-form/react-hook-form/assets/5802917/9592cfcf-fa85-4d45-a0ff-19d424c9c6dd)

funny enough, value type is inferred correctly
![imagen](https://github.com/react-hook-form/react-hook-form/assets/5802917/789feb1b-566d-459f-9834-7e849c1b00bf)

### Expected behaviour

ControllerFieldState.error provides correct type for fieldArrays - array/object of multiple errors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> Does not support flat field array.

https://react-hook-form.com/docs/usefieldarray

**Comment by sKopheK** [comment]
how do i update my code in order to make it work then? by the looks at the definitions, it does not seem error type will be any different no matter how many dimensions my array has

**Comment by Moshyfawn** [comment]
> how do i update my code in order to make it work then? by the looks at the definitions, it does not seem error type will be any different no matter how many dimensions my array has

Here are a few necessary changes to properly set up your code with RHF:

1. As previously stated by @bluebill1049 , the RHF field array **does not support flat arrays**. It is necessary for your field array shape to be **an `array` of `object`s instead of `strings`** _(or any other types)_. This is because RHF requires its own field array item property `id` in order to track the item position. 

```diff
type FormValues = {
- myArr: string[]
+ myArr: { item: string }[]
}
```

2. You are registering the top-level array object _(`myArr`)_ as a field and its nested array items _(`<Controller name={`myArr.${i}`} />` inside `<Controller name="myArr" />`)_, which is not the correct way to handle form fields with RHF. Instead, you should iterate through the `fields` property returned by `useFieldArray` to register your fields correctly and keep track of them.

Please refer to [this working codesandbox](https://codesandbox.io/s/confident-grass-tqz7n6?file=%2Fsrc%2FApp.tsx) that includes all the above-mentioned details.
