### ISSUE TITLE
issue: onTouch doesn't work

### ISSUE THREAD

**Issue by nicitaacom** [react-hook-form/react-hook-form#11217]
### Version Number

7.48.2

### Codesandbox/Expo snack
why? - anyway you move it to discussion I see no sence

### Steps to reproduce

https://youtu.be/4euAxX6K93A?list=PLC3y8-rFHvwjmgBr1327BA5bVXoQH-w5s&t=79

```tsx
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    reset,
    trigger,
    getValues,
  } = useForm<FormData>({ mode: "onTouched" })
  ```
  https://github.com/react-hook-form/react-hook-form/assets/39565703/8e504ad8-866f-4818-ab9c-997b9c9823ba

### Expected behaviour

On touch doesn't work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The issue is closed as there is no reproduction codesandbox or steps to reproduce the problem. It is not feasible for us to scroll through every frame of your screencast just because you believe that "`onTouch` doesn't work", which is entirely untrue. Have you made any attempts to replicate the problem in a minimal environment?

And please learn some basic manners when requesting assistance in public, as no one is obliged to help solve the issue you are experiencing in your complex codebase without any effort from your end.

**Comment by nicitaacom** [comment]
> The issue is closed as there is no reproduction codesandbox or steps to reproduce the problem. It is not feasible for us to scroll through every frame of your screencast just because you believe that "`onTouch` doesn't work", which is entirely untrue. Have you made any attempts to replicate the problem in a minimal environment?
> 
> And please learn some basic manners when requesting assistance in public, as no one is obliged to help solve the issue you are experiencing in your complex codebase without any effort from your end.

>Have you made any attempts to replicate the problem in a minimal environment?

Yes previously I sent you github repository (because codesandbox doesn't work and expro stack doesn't have 'open in vs code' button) - somebody moved it to trash (I mean discussions)
