### ISSUE TITLE
Way to Set isTouched on All Fields onSubmit

### ISSUE THREAD

**Issue by jwalkerinterpres** [react-hook-form/react-hook-form#11366]
**Is your feature request related to a problem? Please describe.**

The subject pretty much says it all: this is a simple request ... and a popular one.

In [this comment of this issue](https://github.com/react-hook-form/react-hook-form/issues/1418#issuecomment-660461297), 21 users all upvoted:

>I also need a way to set a field to touched. Actually, what I really want is all fields to automatically be touched on submit.

And that's in a ticket closed three years ago!  There would undoubtedly be more if the issue was still open.  Clearly there's a desire by many users, myself included, to have this feature.

Why?  Simple scenario: you don't want to show your user errors until they mess with the field, or until they submit the form.  Right now the library can only handle the "until they mess with the field" part ... but it knows when the form is submitted, so it's capable of solving the entire scenario (easily, with a single boolean option!)

**Describe the solution you'd like**

    useForm({...otherOptions, setIsTouchedOnSubmit: true });

When that option is set to `true`, the library would set the `isTouched` of every field to `true` when the form submit handler is triggered.

**Describe alternatives you've considered**
There's an obvious/lame one, which I'm currently using now: create and maintain a separate state variable :(

    const [wasFormSubmitted, setWasFormSubmitted] = useState(false);

    // ...
    return (
      <form onSubmit={e => {
        setWasFormSubmitted(true);
        onSubmit(e);
      })>

    // ...
      <Controller
         // ... otherProperties
        render={({ field, fieldState: { error, isTouched } }) => (
          <>
            // This part has to be repeated for every field in the form
            <input {...inputProps}>
              {error && (isTouched || wasFormSubmitted) && (
                // show the error
              )}
           />

**Additional context**

**Comment by Moshyfawn** [comment]
Can you help me understand what [`formState.isSubmitted'](https://arc.net/l/quote/zrmnrgnq) or even [`formState. isSubmitSuccessful`](https://arc.net/l/quote/aykjfbiz) doesn't solve for you in this scenario? You mentioned the "obvious" alternative, which is to host your own `wasFormSubmitted` state, which RHF already manages for you.

**Comment by jwalkerinterpres** [comment]
> what formState.isSubmitted ... doesn't solve

 I was unaware of `isSubmitted` (|||⇁_⇁)

However, now that I am, it still doesn't _solve_ the issue ... it just makes it less of a problem.  I no longer have to maintain the separate state variable, but I do still have to track two booleans for every field in the form:

    {error && (isTouched || isSubmitted) && (
      // show the error

We programmers are lazy, and we hate mindless repetition, right?  I mean, the point of this library is to eliminate such repetition (when it comes to form logic).

So, it'd still be preferable if we could just do:

    useForm({...otherOptions, setIsTouchedOnSubmit: true });

    // ...

    {error && isTouched && (
      // show the error

**Comment by Moshyfawn** [comment]
No problem!

The concern with developers wanting to set the `touched` field state manually is that this state is **derived from the user's input** by design, so overriding it for the user isn't the correct way to solve the problem.

In this particular case, the need is to validate the user's input on the field touched, which means the user has to interact with the field by focusing on it. For this, RHF provides the `mode` prop, which can be set to `onTouched`, validating the particular input when the input is blurred and then on every change. Instead of trying to override the touched state of all inputs, including the ones the user hasn't interacted with, you can set the `reValidateMode` prop to `onChange`, which will revalidate the form on every change **after the user has submitted the form**. This way, the user will get the feedback they need without having to override the touched state of the inputs.

Here's [an example codesandbox](https://codesandbox.io/p/devbox/distracted-cookies-p6942m?file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr1ejykr00073b6elu4jn7bn%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr1ejykq00023b6e7mmbn5rq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr1ejykq00043b6ejgm3lqe0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr1ejykq00063b6eljm6t8jk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr1ejykq00023b6e7mmbn5rq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr1ejykq00013b6e258x7ywk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr1ekd0300023b6ei0nr42al%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr1ejykq00023b6e7mmbn5rq%2522%252C%2522activeTabId%2522%253A%2522clr1ekd0300023b6ei0nr42al%2522%257D%252C%2522clr1ejykq00063b6eljm6t8jk%2522%253A%257B%2522id%2522%253A%2522clr1ejykq00063b6eljm6t8jk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr1ejykq00053b6e60cfiiwz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr1ejykq00053b6e60cfiiwz%2522%257D%252C%2522clr1ejykq00043b6ejgm3lqe0%2522%253A%257B%2522id%2522%253A%2522clr1ejykq00043b6ejgm3lqe0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr1ejykq00033b6e282h0vu3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr1ejykq00033b6e282h0vu3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to demonstrate the above.

1. Open the example
2. Focus one of the input fields
3. Blur / unfocus the field by clicking outside of the input
4. See the error that occurred `onTouched` for the field
5. Fix the field's error by entering a value which is all lowercase letter _(for example, the word `example` 🤪)_
6. Submit the form by clicking the Submit button
7. See the other "untouched" field got the validation error
8. Try entering any value into any of the inputs to see that now the `onChange` validation mode is in effect
