### ISSUE TITLE
issue: useFieldArray not working properly with useController

### ISSUE THREAD

**Issue by kaio-eduardo** [react-hook-form/react-hook-form#11517]
### Version Number

7.50.1

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/usefieldarray-controller-gjywsv

### Steps to reproduce

1. Add any value to the first input so the arrayfield form mounts
2. Click on append
3. Delete the value in the first input so the fieldarray unmount
4. Add another value to the first input, the fieldarray, then you see the fieldarray still have the appended value

Also if you append to values to the array, remove one, unmount the fieldarray form, then mount again, it will have two append values again

### Expected behaviour

The expected behavior would be that once the array is unmounted and mounted again, it would be empty.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaio-eduardo** [comment]
Just to add, this doesn't happen when using the register method. This problem only appears when using the Controller component or the useController hook

**Comment by kaio-eduardo** [comment]
Trying things i found the problem is the shouldUnregister at the useForm level. if i set it to the default and set shouldUnregister at component level, it works as expected.
I just dont know if that should be the expected behaviour when using the shouldUnregister at the global level

**Comment by bluebill1049** [comment]
it wouldn't work with `shouldUnregister` because the nature of input get mount and unmount in field array.

**Comment by kaio-eduardo** [comment]
> it wouldn't work with `shouldUnregister` because the nature of input get mount and unmount in field array.

So the right thing is to use the shouldUnregister at the component level?

**Comment by bluebill1049** [comment]
> > it wouldn't work with `shouldUnregister` because the nature of input get mount and unmount in field array.
> 
> So the right thing is to use the shouldUnregister at the component level?

shouldn't use `shouldUnregister` within the usage of `useFieldArray`.

**Comment by kaio-eduardo** [comment]
> > > it wouldn't work with `shouldUnregister` because the nature of input get mount and unmount in field array.
> > 
> > 
> > So the right thing is to use the shouldUnregister at the component level?
> 
> shouldn't use `shouldUnregister` within the usage of `useFieldArray`.

Now its more of a question, but what would be the best way to do that behavior?

**Comment by bluebill1049** [comment]
I would consider manually calling the unregister, if you want individual field to remove completely unregistered.

**Comment by kaio-eduardo** [comment]
Taking a look at the code, using the shouldUnregister from the useFieldArray should be fine i think, since it does just that:
```js
  React.useEffect(() => {
    !get(control._formValues, name) && control._updateFieldArray(name);

    return () => {
      (control._options.shouldUnregister || shouldUnregister) &&
        control.unregister(name as FieldPath<TFieldValues>);
    };
  }, [name, control, keyName, shouldUnregister]);
```

The thing i dont understand is how when i set the useFieldArray and the useController shouldUnregister to true, it works. But when i set the useForm shouldUnregister to true then it start having those problems

**Comment by bpinto** [comment]
The solution to this problem seems to be to not use `shouldUnregister`, yet this option was added to [disable merging of defaultValues](https://github.com/react-hook-form/react-hook-form/issues/4619). So, is there a solution that disables the merging of defaultValues that doesn't break array interactions?

I tried something like the following:

```
  useEffect(() => {
    const fieldNames = Object.keys(methods.control._fields)

    methods.reset(
      Object.keys(methods.getValues()).reduce((acc, val) => {
        if (!fieldNames.includes(val)) {
          acc[val] = undefined
        }

        return acc
      }, {})
    )
  }, [])
```

which on an example where we have `defaultValue: { included: 1, excluded: 2 }` and `excluded` is not a form field then the code above would call `reset({ excluded: undefined })` in order to remove it from the submission data. But doing so means `watch` would be triggered.

I couldn't come up with a solution yet, I still find it would have been easier for anyone that wanted react-hook-form not to behave like native forms (since they are submitting data that is not included on the form, not even using a hidden input) to merge the data when calling `onSubmit`: `onSubmit({ ...defaultValues, ...data })`.
