### ISSUE TITLE
issue: Fields dirty state is not updated when passing values to useForm since 7.51.0

### ISSUE THREAD

**Issue by djhi** [react-hook-form/react-hook-form#11794]
### Version Number

7.51.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/control-forked-stnhsf

### Steps to reproduce

To reproduce, change the value of the only input and observe the `isDirty` value displayed by the `IsolateReRender` component. It stays `false`

 

### Expected behaviour

It should be set to `true`.

I actually set up two sandboxes:
- with v7.50.1: https://codesandbox.io/p/sandbox/control-forked-sjggjc
- with v7.51.0: https://codesandbox.io/p/sandbox/control-forked-stnhsf

The issue is still present in v7.51.3.

This breaks all react-admin applications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thanks, for the report, looks like the issue is already fixed: https://codesandbox.io/p/sandbox/control-forked-5fys45?file=%2Fsrc%2FApp.tsx%3A9%2C20 related issue: https://github.com/react-hook-form/react-hook-form/issues/11778

**Comment by djhi** [comment]
There's something I don't understand though. My second sandbox (https://codesandbox.io/p/sandbox/control-forked-stnhsf) uses `7.51.3` just like yours, yet it has the same issue but yours don't. Besides, I don't see any differences between the two.

**Comment by slax57** [comment]
> There's something I don't understand though. My second sandbox (https://codesandbox.io/p/sandbox/control-forked-stnhsf) uses `7.51.3` just like yours, yet it has the same issue but yours don't. Besides, I don't see any differences between the two.

That's because the fixed sandbox imports from `./src` and not from `react-hook-form`

**Comment by djhi** [comment]
> > There's something I don't understand though. My second sandbox (https://codesandbox.io/p/sandbox/control-forked-stnhsf) uses `7.51.3` just like yours, yet it has the same issue but yours don't. Besides, I don't see any differences between the two.
> 
> That's because the fixed sandbox imports from `./src` and not from `react-hook-form`

Good catch, thanks :)

**Comment by djhi** [comment]
@bluebill1049 Any chance to have a release soon? :pray:

**Comment by bluebill1049** [comment]
> @bluebill1049 Any chance to have a release soon? 🙏

yes, sorry I am on a break.

**Comment by djhi** [comment]
Hi @bluebill1049! Thank you for the release. It does not seem to be fixed though :sob: 
https://codesandbox.io/p/sandbox/control-forked-stnhsf

**Comment by TheWirv** [comment]
I have breaking unit tests because a CSS class is applied based on the `isDirty` state, and I check in the tests, whether the state is class is applied or not.

I have logged some of the data while rendering the component, and this is the final state, with version `7.51.4`:
![image](https://github.com/react-hook-form/react-hook-form/assets/4397989/33c8f167-86ba-4052-b407-5a08ee6ef50a)

I have executed the same test on an older version (I am trying to upgrade package versions for our project right now) and there it works fine, with version `7.15.4`:
![image](https://github.com/react-hook-form/react-hook-form/assets/4397989/631b4030-ae7e-414b-a94d-6bf5e9157900)

Both use the same `userEvent.type` API from the user event testing library.

**Comment by Cafnio** [comment]
Also happening in my case. using latest releast

**Comment by RayzorFlash** [comment]
Can second, still seeing issues with dirty fields on the latest release (7.51.5)
