### ISSUE TITLE
Nested field arrays break data.slice

### ISSUE THREAD

**Issue by hperl** [react-hook-form/react-hook-form#1208]
**Describe the bug**
`data.slice is not a function` when removing multiple sub-elements in nested field arrays.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-defaultvalues-4o5iu
2. Click on "Add element"
3. Click on "add subelement" twice
4. Click on "remove subelement" twice
4. After the second "remove subelement" the app breaks with `data.slice is not a function`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-defaultvalues-4o5iu

**Expected behavior**
Sub-elements should be removed without an error.

**Additional context**
If I add another element before removing the second sub-element it works fine. It seems like after removing one nested field array the state is left in a bad state.

**Comment by jtoliver** [comment]
So if you add 3 items you have some thing like element[0].name, element[1].name, element[2].name then remove element 1...things shift leaving you with element[0].name, element[1].name where 1 used to be 2. But you are not unregistering fields so element still has extra items registered that should be. I just had this issue and swap to the <Controller /> component so it would take care of auto register/unregister. Hopefully that made sense...I'm half sleep :)

**Comment by hperl** [comment]
I'm still confused. What would the correct way be to do nested field arrays?

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useFieldArray
<img width="933" alt="Screen Shot 2020-03-15 at 9 24 45 am" src="https://user-images.githubusercontent.com/10513364/76691457-db664500-669e-11ea-99b4-bdd669772f58.png">

it's due to `register` not to get invoked inside `map` when using with `FormContext`.

**Comment by bluebill1049** [comment]
for more information and background: https://github.com/react-hook-form/react-hook-form/issues/1198

**Comment by hperl** [comment]
Thanks @bluebill1049 I missed that in the docs. Now everything works like a charm. Thanks again for the support and the great library!

**Comment by bluebill1049** [comment]
my pleasure :) sorry about this not so user-friendly behavior. we have tried to fix it...

**Comment by JoaoGuedes** [comment]
https://github.com/react-hook-form/react-hook-form/issues/1198#issuecomment-597555557

@bluebill1049 seems that even using `register()` won't work as expected, if you run your example and do `append` and then `remove` both items you'll get the `data.slice` error.

Seems something's off with `getFieldValueByName(fieldsRef.current, name)` in `remove()` in `utils/useFieldArray.ts` as it sometimes returns an `{}` instead of the field array?

Haven't dug much deeper though...

**Comment by bluebill1049** [comment]
@JoaoGuedes what do you mean run append and remove at the same time? I don't think that's going to work since the input is not even registered.

**Comment by JoaoGuedes** [comment]
Initially you have `useFieldArray` > append a new one (`append`) > remove `append` > try to remove `useFieldArray` and it crashes

**Comment by bluebill1049** [comment]
thanks @JoaoGuedes what do you mean?

-  try to remove useFieldArray and it crashes 

i am trying to isolate the issue and apply a fix for it.

**Comment by JoaoGuedes** [comment]
I mean deleting the row that has the `useFieldArray` text value

**Comment by bluebill1049** [comment]
@JoaoGuedes fixed it's an outdated version: https://codesandbox.io/s/react-hook-form-usefieldarray-kbsls

**Comment by rnnyrk** [comment]
Thanks for this one, also missed it in the docs but this resolved the issue.

**Comment by bluebill1049** [comment]
no worries @rnnyrk
