### ISSUE TITLE
issue: explicitly registering input disabled: false boolean value does not trigger validation

### ISSUE THREAD

**Issue by reinertisa** [react-hook-form/react-hook-form#12207]
### Version Number

7.52.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/usewatch-does-not-trigger-validation-r2f55d?file=%2Fsrc%2FApp.js%3A41%2C33

### Steps to reproduce

1. Click on 'Submit'
2. See validation errors
3. Select 'Apple'
4. You will see validation error because of input registered as **disabled: false** - FAILED
<img width="587" alt="Screenshot 2024-08-22 at 6 04 48 PM" src="https://github.com/user-attachments/assets/ef29b751-cbac-4433-964d-9f239fbf39b3">

5. Select 'Banana'
7. You will see validation error will gone because input registered **disabled: undefined** and validation will trigger. - PASSED
<img width="573" alt="Screenshot 2024-08-22 at 6 05 00 PM" src="https://github.com/user-attachments/assets/edae269a-623b-4d91-9eb2-a181fa34c1c5">

**Note**: I also used validate function but it does not work. 

### Expected behaviour

When input registered with explicitly **disabled=false**, validation should trigger when I toggle input. It works with version 7.47.0 but it does not work with 7.52.2

**Version 7.52.2 - FAILED**

<img width="835" alt="Screenshot 2024-08-22 at 6 10 32 PM" src="https://github.com/user-attachments/assets/cbbc2d1d-76ec-449e-8fcf-318946cee0ff">

**Version 7.47.0 - PASSED**

<img width="850" alt="Screenshot 2024-08-22 at 6 13 05 PM" src="https://github.com/user-attachments/assets/079a20bf-97bb-4042-815a-995619dd5832">

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeByRaf** [comment]
Hi [reinertisa](https://github.com/reinertisa),

I think there is an issue on direct implication of the state inside the element using disabled attribute. You might try adding it directly, the disabled attribute to the element. Works fine for me. I hope this answers your question.

![image](https://github.com/user-attachments/assets/f61d8912-016a-40e6-9210-9ad5b27d8de8)

Sorry for bad English -_-

**Comment by CodeByRaf** [comment]
Hi [reinertisa](https://github.com/reinertisa),

I deleted my previous comment because it does not address the issue.

The useWatch hook in React Hook Form is designed to track changes in form values, but it doesn't track changes to attributes like disabled directly. The disabled attribute is not part of the form values managed by React Hook Form; it's a property of the DOM element that affects its behavior and interaction.

This is my personal opinion of what useWatch define.

**Comment by CodeByRaf** [comment]
If it worked in the past versions, it might cause performance issues because it checks for DOM changes. However, if the functionality is essential for all developers, it would be beneficial to revert these changes. Keep in mind, though, that this may negatively impact performance.

**Comment by reinertisa** [comment]
@CodeByRaf hi, thank you for comments. I gave two scenarios. One of them **disabled: false** and **disabled: undefined**. 
- When **disabled: false**, it works for **7.47.0** but it does not work **7.52.2**. 
- When **disabled: undefined**, it works for both versions 
- Or when we do not register disabled in register. It works for both versions. 
 
The question is why disabled: false does not trigger validation but other scenarios trigger validations. If you need any information, please let me know. Thank you.

**Comment by CodeByRaf** [comment]
If you're gonna look in the world web standard. There is no such **disabled = false** or **disabled=undefined** Better to revamp that logic, if I were you. Even they fix it. You'll encounter it in the future updates due to the world web standard. You'll end up fixing that issue again.

Not sure why disabled undefined works, but it will conflict the browser engine in the future updates. Better to revamp it. 

If you really need that feature. Stay where the functionality works temporarily and we need to wait for the author/community to address the concern.

Happy coding!

**Comment by reinertisa** [comment]
@CodeByRaf I see, but if there is an option on api, we need to use this boolean value to trigger validation. Without disabled property in register function and with disabled property and setting false should act the same. react-hook-form documentation also gives this option and it worked well previous version. This is screenshot from official documentation. 
<img width="954" alt="Screenshot 2024-08-23 at 10 39 46 AM" src="https://github.com/user-attachments/assets/443bb3e4-827d-43a8-9587-9b189fc6c71c">
https://react-hook-form.com/docs/useform/register

**Comment by CodeByRaf** [comment]
As you can see. They are referencing the built-in rules. Maybe that's why undefined works. 

When the value is undefined. The disabled attribute won't be able to render it to the element. Still its just some of my observations.

Maybe they have some tweaks in the previous version that's why it's working. Better check it in the inspect element. What's the difference between the version.

This will be my last response to this topic.

Thanks and Happy coding!

**Comment by bluebill1049** [comment]
fixed with the latest.

**Comment by reinertisa** [comment]
@bluebill1049 thank you for fixing it. It works great now.
