### ISSUE TITLE
issue: Function register does not return required following the types

### ISSUE THREAD

**Issue by JoffrayBillon** [react-hook-form/react-hook-form#12346]
### Version Number

7.53.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/register-required-isnt-exist-as-suggested-in-the-types-fv7qjr

### Steps to reproduce

1. Go to setup clean react project with `const { register } = useForm();`
2. `register("firstName", { required: true })`

### Expected behaviour

<img width="684" alt="image" src="https://github.com/user-attachments/assets/91ec16ea-c1b8-411f-878d-a4630c9fe5a3">

Am I doning it wrong ? How to get returned the required property, I can't find anything in the doc...

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
In Chrome:
{name: 'firstName', onChange: ƒ, onBlur: ƒ, ref: ƒ}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Those are optional return types. 
![Screenshot 2024-10-19 at 8 29 57 AM](https://github.com/user-attachments/assets/2c496e59-9a99-4772-ba6d-cb3bc4e110af)

**Comment by JoffrayBillon** [comment]
> Those are optional return types. ![Screenshot 2024-10-19 at 8 29 57 AM](https://private-user-images.githubusercontent.com/10513364/378015871-2c496e59-9a99-4772-ba6d-cb3bc4e110af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDQ3NzUsIm5iZiI6MTcyOTUwNDQ3NSwicGF0aCI6Ii8xMDUxMzM2NC8zNzgwMTU4NzEtMmM0OTZlNTktOWE5OS00NzcyLWJhNmQtY2IzYmM0ZTExMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA5NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZmNkOTEyZDgxNDg0YjA4YjVlNTk1M2YxMTUxNzk2YzFlZjk4YjU3OThjMDZlMTEwZTYxMDMwYjBjMDBjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wU0q2l1ASp06xwPIe_SZe3nUfdImtQDeBVPetfXLPAI)

Yes I totaly get it but if they are optionnal, then what are the case that made them returned ?
Else if it's intened to never be defined, why define them in the types ?
And in this case, shouldn't it be removed of the types to avoid confusion when reading the returned types.

As I told in the ticked nothing document that behavior in the doc.

**Comment by vivi90** [comment]
Same issue here with version `7.52.1`:

Don't see the purpose of `required` in the return type of `register()` since it's never returned.
Also `register("exampleRequired", { required: true })` - as documented in the quick start guide - does not return `required` at all.
https://react-hook-form.com/get-started#Quickstart

**Comment by tjbrennan** [comment]
Hey @JoffrayBillon and @vivi90. I had the same question and since @bluebill1049's answer was less than helpful I thought I'd post my findings for you and anyone else who arrives here with the same question. 

What I found is that these props are only returned if you set `progressive: true` in your `useForm` options. This option is used in tandem with `<Form>` for SSR. The `progressive` option doesn't appear to be used anywhere else but I can't guarantee that there won't be side effects if you enable it. Otherwise, the register options are used internally and the only props exposed to the component are `disabled`, `name`, `onChange`, `onBlur`, and `ref`.

- Register return values logic: https://github.com/react-hook-form/react-hook-form/blob/baea055c22d23ff1ed9f073f809ee9168e65e37a/src/logic/createFormControl.ts#L1062
- All usages of `progressive`: https://github.com/search?q=repo:react-hook-form/react-hook-form%20progressive&type=code
- `Form` documentation: https://react-hook-form.com/docs/useform/form
