### ISSUE TITLE
issue: disabled is causing undefined values on Submit with error

### ISSUE THREAD

**Issue by terragady** [react-hook-form/react-hook-form#12443]
### Version Number

7.53.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/rhf-disabled-not-working-forked-yxhlf8

### Steps to reproduce

See the error in code sandbox
Once pressed submit, `showSomething` value goes undefined.
Also check the consol log, last field if present is also undefined during submission.

In my use case this is causing a lot of issues with advanced forms and does not look nice. Also it does not come back to defaultValue (or set value in that matter).

I want to keep disabled form during submission, maybe there is some better way to do it?
For me it only creates a problem when there is API error during submission, on normal query without error it is just fine.
I think it dissapears after first error of the try.

The problem did not occur with previous version 7.53.1 which means some change was done in 7.53.2 which changes some stuff around.

Video from my use case:
https://github.com/user-attachments/assets/6646d029-9360-4811-a9f9-7f670a110ff8

### Expected behaviour

Keep the values

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by terragady** [comment]
hmm, yes kind of explain but then one version ago it was working fine at least in my case, also triggering disabled dynamically withh not cause the problem. `readOnly` is not available globally.

**Comment by bluebill1049** [comment]
> also triggering disabled dynamically withh not cause the problem.

can you give more detail on this?

**Comment by LimmaPaulus** [comment]
There seem to be many closed issues regarding field values being undefined when a field is disabled. The commonly mentioned workarounds are to make the field `readOnly` or to wrap it in a disabled `<fieldset/>`. I’m commenting here because this issue is still open.

I have to say that the current logic is extremely frustrating. I just spent hours trying to figure out why my `watch("fieldName")` is returning undefined instead of the default value when the form is disabled. This unexpected behavior causes significant issues when I simply want to make the form read-only.

**My use case:** I have a "type" selection on my form. If the user selects type A, they dynamically see a set of fields specific to that type. The same goes for type B. In some situations, the user is not allowed to edit the form but should still be able to view the values. I set the stored value for "type" as `defaultValues`. Then, I use `watch("type")` to render the appropriate dynamic fields. However, when the form is disabled, watch returns undefined, and the type-dependent fields disappear.

The suggested workarounds, such as using a `<fieldset>` wrapper or the readOnly attribute, feel like hacks. The `readOnly` attribute is fundamentally different from disabled, and I shouldn’t have to introduce unnecessary wrappers just to achieve proper behavior when disabling fields.

Here is an example of the problem with `watch()`. For some reason, watch returns the default value on the first render, but when the user clicks the button and the state is updated, watch returns undefined:

https://codesandbox.io/p/sandbox/j93q5f

**Comment by bluebill1049** [comment]
We can't do `diable` for the entire form while submitting. I am trying to follow the standard here, with disabled input which will result in `undefined`. This would be perhaps something you should do at CSS level.

**Comment by jaens** [comment]
This is quite a breaking change that IMHO should not be in a minor version...

A lot of our forms are using global "disabled" to have a decent UX when the form is loading, and after upgrading RHF half the app is subtly broken (forms are cleared when the submit handler fails due to eg. server-side validation error).

The entire reason why we are using a form framework is to patch around various deficiencies in browser-native forms, so adding those deficiencies back is... mystifying.

This amongst other subtle bugs/"features" is why we'll now be moving the entire app to probably Tanstack Form (or our own form framework) instead, because it looks like RHF can't be trusted to have reliable design decisions.

**Comment by LimmaPaulus** [comment]
> I am trying to follow the standard here, with disabled input which will result in undefined

Could you elaborate on that? Personally, I am not aware of any standard that states this behavior. If such a standard exists, I believe it’s not worth adhering to, as this kind of behavior would be unexpected by most users.

This library is an excellent piece of software! Please consider this feedback and refine this detail for better usability.

Please check this CodeSandbox. The user can select either option "A" or "B." If option "A" is selected, an extra input field appears.

When the form is disabled, everything initially works as expected with default values. However, after the state is updated by pressing the extra button, the input field disappears. Good dev experience?

[https://codesandbox.io/p/sandbox/kyh8zh](https://codesandbox.io/p/sandbox/kyh8zh)

**Comment by bluebill1049** [comment]
Please refer to the here: https://www.w3.org/TR/html401/interact/forms.html#disabled

Would the following consider a work around for async post API? As my understanding the issue caused by UX on user submit the form while request is hanging.

```tsx
onSubmit={handleSubmit(async (data) => {
  setDisabled(true);
  await postData();
  setDisabled(false);
})}
```

> Please consider this feedback and refine this detail for better usability.

Yes, that's from your perspective while I have to take care others who reported the `disabled` props, it was always meant to be set to undefined when `disabled` prop been set. It was a bug which I get to fix it.

**Comment by LimmaPaulus** [comment]
> Please refer to the here: https://www.w3.org/TR/html401/interact/forms.html#disabled

I don't see anything stating that the value of a disabled field should be undefined — only that it should not be submitted.

Shouldn't the value returned by `watch` match what is shown in the UI? If you check my previous CodeSandbox, you'll see that it doesn't. The value in the select field is set, but watch returns undefined. In any case, why would watch return something different from the current value of the field?

If I set disabled in useForm but then explicitly set disabled for fields to false, `watch` still returns undefined. What about that?

[https://codesandbox.io/p/sandbox/kyh8zh](https://codesandbox.io/p/sandbox/kyh8zh)

> Yes, that's from your perspective while I have to take care others who reported bug on the disabled props, it was always meant to be set to undefined when disabled prop been set. It was a bug which I get to fix it.

I may not fully understand all perspectives and the complete history of this issue. However, I clearly see a problem with `watch` returning undefined values while the UI displays the correct values. I am just trying to say that there is an issue which should be addressed somehow.

**Comment by jaens** [comment]
Indeed, this does not even follow browser standards.

The `value` of a `disabled` `<input>` element does not go anywhere (in case the page is not navigated away eg. in case of an error), ie. it is never set to `undefined`, and as `watch(name)` intuitively accesses the value of an input, having it return `undefined` does not match browser behavior.

The `disabled` state only affects HTML standard section [4.10.21.4 Constructing the entry list](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set), which is a concept RHF does not currently even have.

**Comment by bluebill1049** [comment]
Go and test this example

```
export default function App() {
  return (
    <form action="/">
      <input name="data1" value="1234" disabled placeholder="First Name" />
      <input name="data" placeholder="First Name" />
      <input type="submit" />
    </form>
  );
}
```

This form value will not be submitted, which is the same as omitting the value. `watch` or `getValues` share the same mechanism, it's just return what the current form values will get submitted. Overall, you are driving into a different issue or conversation other than the current reported issue, making this issue even more confusing.

**Comment by LimmaPaulus** [comment]
> Overall, you are driving into a different issue or conversation other than the current reported issue, making this issue even more confusing.

No, my issue is exactly same as @terragady's original one. Check the original CodeSandbox, lines 43 and 62. There watch is returning undefined while form is disabled, which brokes the UI.

```
const showSomething = methods.watch("showSomething");
...
{showSomething === "1" && <p>Show something is 1</p>}
```

> Go and test this example

I don't understand why you are trying to mimick native form behavior. Aren't you trying to implement something better than native forms?

> This form value will not be submitted, which is the same as omitting the value.

I disagree. We are not speaking about submitting the disabled value, but getting the current value.  You can check what native components return if you query the disabled field value manually:

```
export default function App() {
	return (
		<>
			<form action="/">
				<input name="data1" value="1234" disabled placeholder="First Name" />
				<input name="data" placeholder="First Name" />
				<input type="submit" />
			</form>
			<button
				onClick={() => {
					const input = document.querySelector('input[name="data1"]');
					console.log(input.value);
                                        // Logs 1234, not undefined
				}}
			>
				Log current value
			</button>
		</>
	);
}
```

There have been numerous issues about this same thing. At least
#12303 #11258 #11145 #9743

So I'm pretty sure I'm not the only one not understanding this choice.

Of course you are free to make any choices you want with your library. Maybe I will fork it or make some workaround.

**Comment by bluebill1049** [comment]
> I don't understand why you are trying to mimick native form behavior. Aren't you trying to implement something better than native forms?

I am not trying to mimic, but I am more aligned. So when you are not using this library, your expectation would be the same for the native form.

I get your point on the `watch/getValues` part. It would not be a simple change/fix to return disabled input value with `getValue` or `watched`, we will have to track all disabled input within lib if we want to go down this path. 

What I would recommend to do:

- Ping the old version if that's the desired behavior 
- Fork and make your workaround
- Don't use this library, as the other guy stated. It's an open-source library, you are free to do whatever you like.
- Wait for me to get some time to look into the tracking disable field. It would be just a fix on the form level but also the field level, so it would take some time, right now I am kind of busy with everything.

**Comment by LimmaPaulus** [comment]
Thank you, and I apologize. I didn’t mean to be offensive. I just wanted to make my point clear, and I now see that you understand it. I understand that you are making voluntary work here and open source is always open source.

**Comment by bluebill1049** [comment]
> Thank you, and I apologize. I didn’t mean to be offensive. I just wanted to make my point clear, and I now see that you understand it. I understand that you are making voluntary work here and open source is always open source.

Thanks for understanding. Your comments were fine, and I appreciate your patient as well. Often after a long day I am already exhausted, so going through comments could be frustrated and missing points.
