### ISSUE TITLE
Check if form has been submitted successfully 

### ISSUE THREAD

**Issue by bogdansoare** [react-hook-form/react-hook-form#1452]
Currently `isSubmitted` is set to true, even though because of validation the `onSubmit` handler hasn't been triggered which is kind of confusing.

Both formik and final-form set `isSubmitted` to true only after the `onSubmit` handler has successfully ran

**Comment by bluebill1049** [comment]
> submitted: Read-OnlyReturns whether the form submission has been triggered.

Do you have any good reference include submitted should only be successful submission?

**Comment by bogdansoare** [comment]
I don't really understand understand how it is submitted if the `onSubmit` handler hasn't ran?

**Comment by zlangbert** [comment]
I was also very confused by this. I haven't used other react form libraries, but when I saw the `isSubmitted` property I assumed it would only be true if the form was successfully submitted (i.e passed validation). With how I was using that property, I initially thought validation wasn't working. It took me a minute to figure out that is will be set to true on any submission, valid or not. 

I understand I can achieve the same thing with the submit callback, but maybe something in the docs to clarify the behavior of `isSubmitted` would be helpful to others as well.

I also think a `isSuccessfulSubmitted` would be valuable. In my case I am swapping the form UI out for a success message on submit, if I could just use a property on `formState` rather than having to add another state variable to my component that would clean things up a bit.

Overall this library is awesome, thank you!

**Comment by bluebill1049** [comment]
> I was also very confused by this. I haven't used other react form libraries, but when I saw the `isSubmitted` property I assumed it would only be true if the form was successfully submitted (i.e passed validation). With how I was using that property, I initially thought validation wasn't working. It took me a minute to figure out that is will be set to true on any submission, valid or not.
> 
> I understand I can achieve the same thing with the submit callback, but maybe something in the docs to clarify the behavior of `isSubmitted` would be helpful to others as well.
> 
> I also think a `isSuccessfulSubmitted` would be valuable. In my case I am swapping the form UI out for a success message on submit, if I could just use a property on `formState` rather than having to add another state variable to my component that would clean things up a bit.
> 
> Overall this library is awesome, thank you!

This will be part of 6.8.0 release.
