### ISSUE TITLE
setValue not working in the latest release

### ISSUE THREAD

**Issue by kamranahmedse** [react-hook-form/react-hook-form#1465]
**Describe the bug**
`setValue` is not setting the form values in the latest release.

**To Reproduce**
* Open the codesandbox links given below
* Click the "Click Me" button in the preview

**Codesandbox link (Required)**
* Working 5.4.2 — https://codesandbox.io/s/festive-morse-m8cxm?file=/src/App.js
* Not Working [Latest] — https://codesandbox.io/s/winter-cdn-w8wp7?file=/src/App.js

**Expected behavior**
Value should be set in the form

**Comment by kyle-mccarthy** [comment]
It also looks like the new version broke the `setValue` typings.

```typescript
setValue('someName', 'theValue');
```

Results in the following TS error.

```
Overload 1 of 2, '(name: string, value: DeepPartial<any>, shouldValidate?: boolean): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'DeepPartial<any>'.
  Overload 2 of 2, '(namesWithValue: DeepPartial<Pick<Record<string, any>, string>>[], shouldValidate?: boolean): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'DeepPartial<Pick<Record<string, any>, string>>[]'.
```

**Comment by bluebill1049** [comment]
hey, @kamranahmedse make sure you are registered at `useEffect`, otherwise, each render will refresh the registration. The latest patch introduce `ref` compare to avoid component unmount and remount problem.

https://codesandbox.io/s/elastic-sinoussi-urxkm?file=/src/App.js

**Comment by bluebill1049** [comment]
@kyle-mccarthy can you give more context on the issue above, did you define type at useForm?

**Comment by bluebill1049** [comment]
> It also looks like the new version broke the `setValue` typings.
> 
> ```ts
> setValue('someName', 'theValue');
> ```
> 
> Results in the following TS error.
> 
> ```
> Overload 1 of 2, '(name: string, value: DeepPartial<any>, shouldValidate?: boolean): void', gave the following error.
>     Argument of type 'string' is not assignable to parameter of type 'DeepPartial<any>'.
>   Overload 2 of 2, '(namesWithValue: DeepPartial<Pick<Record<string, any>, string>>[], shouldValidate?: boolean): void', gave the following error.
>     Argument of type 'string' is not assignable to parameter of type 'DeepPartial<Pick<Record<string, any>, string>>[]'.
> ```

FYI @kotarella1110

**Comment by kyle-mccarthy** [comment]
@bluebill1049 Sorry, I thought they were related issues and didn't provide enough context. I am actually having the problem when using `useFormContext`. With 5.4.2 it worked without providing the FormValues generic to the context.

**Comment by bluebill1049** [comment]
@kyle-mccarthy you want to provide a codesandbox and let us investigate it?

**Comment by kotarella1110** [comment]
It is a bug caused by this PR (https://github.com/react-hook-form/react-hook-form/pull/1412). I will fix this.

[TypeScript Playground](https://www.typescriptlang.org/play/?ssl=41&ssc=19&pln=41&pc=32#code/PTAEBcE8AcFNQGIHsBOBbAagQwDYFdYBnUAXlAG8AoEUWw8FASwDsBzALlHqbYG5qwtZnjQAjWCk7CxE-jVpJRAK1gBjcJyrzaoaeMm6R+uYJ2ikSHLCzNO5y9eYmdAX2e0sKFFkiaBOugYWDi4gvn8A+ysbOwtopwjQFwBtAF1nN0pKKDhEVExcAmIyACU1VAATAB5uYIAaUBtIAD5+SlgAD2hUcAgYeAAZRnAJXAAVJAAFJjRhxgA3WCqx0E6R5griJubSUBW12A3iWrZKWgB+UJ5WM9BOfY71zcMZFFvLvQlb+9XHw+eoo53qBATZvns2p1uihejl4AARWCwaCTTzgRi4ZY7MhUWjJSagFigADWsEgSAAZntUud7vjUr8nsQAIJeHxVFgUiSgACqzVuF1ArO8kCqiORqJhGJwVT5-ICdMmDIOR1AZSwFSQzBwkGF7M53L5AtAl3Vmu1urZovFKLR0tlzXlOkVyr+qvIoGSpN8V2CqU4eGYxOYSAA7swksbLjbJejMWN6U7aC7+JlKBU1DhPPAKYH1IwtVxYOBsPglg8mSSyZS8uhS0VmgAKW7MLBoIgAdWGAAt67BODG7ZjJoxVMSqsg64UiA0xo60nVboRu0g8DgKqXGBUsCNaSC4o5FwBKTjzJBb-gZ1RZlA5vPowuEYt95aM-7HMKsBo8t+qwPBsNmCbFs237PZF1oeZpx+FVnm9GtJwKMtCCjUBBylTFEL7QhkjGVIkzuUAhhGbwcAmaZGFmdFFgdCCuBXNcN1wLcd1gPdQWYY9T3PCo2koJ8S2nRsAHITlYYSGmEkZ6GEo9-FzZh80fZ9pyqAAiMS1IaMSm1bdtOA0z8tNAKCy04MTtIY9dN23XdYgcGxQAAH1AQMMwpFhYAqE8TJ4-iVLLETPhQCTQAARjkmgFKUiMBJfNTguM4LdNAgzEoaUyCCkIwJEs1drOY2y2Ps+JnNcjZYA85gvJ8s8t38wTAuE4LQuEiQUFQWT-EAGXJODhVYvFQBq+0bZIPTEzgpKIcBhKSVJIrAaKH1igKCHUzSUvbQgu3AXtoLQpFbQwmURzHCd8mwhpDOuNT51SPLGJs1j2IPRyXLcyrPO87j6rioSxpefRJvazq5oW0Ber6XIQbeP7ArGpdP0m6SZro4LODCygXHm+T7wLFbGrW67gjUsqEpylBbsbPTOx7PsB0O2N7VO8csOnQgrs0snEruh6CpwFi7P3ByI3eiqqpqn6KmG-7bnGpHQCmmSkjoj10fClXKBxqK8eUwmlmJthSZc8nXipmntrp-b0LjE7R1Zi72c5ozuYp27mgXej8qYgWipekWyo+iXvt837VtgETFBUdRQrVimMaSI9nCW-Gi319So7UcBjLj15steJJNrAtTM-UYzMrAm37VzoHAdkYX4hKxxC75n3BeKhvm7F9yvtqvy4YISPlCzgA6DjQoYAgk9xxTlrT+LS-AMfXuYYyOKLgzF+XkXy-2jjW6eoWOMD8Xe6lmWms8EVQoBibFZR2bsfBlO9fiq+fBz302HMz9eCSNIN6gDUu-SAu8yx7kbFXTE8trg-2uH-DiTcbB-xcDsbun1qreTSCfHumCD6FWekg0W5VcGS1DtLAeEdhIgOSGFVI294gTxQFPGeMV56qWAVaWh9COJrxXoAzhIpuEMMcGArKncbD4N9oQiRxCg5n3IRfQe1CuF0JETYVqIYYZdR1rPVOlD1I0LUbw7Sn4BFGJ4SvMRYELJe0egQo+K8cEYLIXVCh4caifgaOvESFj1HMFato8GkN+owyURHAGIDOAA0QaACkuAnxzSfqwueBjBEfyLpbXa9MDoSiHHbM6bNkJXRAe7T2y5vaHw7sfdBwc+5biAA)

**Comment by kamranahmedse** [comment]
@kotarella1110 @bluebill1049 thanks for the quick response but this doesn't seem to be fixed :)

Here is the updated codesandbox with the latest release:

https://codesandbox.io/s/tender-hooks-9fkoe?file=/src/App.js

**Comment by davidtran** [comment]
I am still getting this error

**Comment by casizzi** [comment]
> I am still getting this error

+1

**Comment by bluebill1049** [comment]
@davidkartuzinski @casizzi 

Could you please share a codesandbox?

**Comment by jeanlambert17** [comment]
I have this same error.

`	const handleDate = (date: Date) => {
		setDate(date)
		setValue('expMonth', date.getMonth() + 1)
		setValue('expYear', date.getFullYear())
	}
`

When onSumit is called, it doesn't contain the values updated by setValue.

**Comment by bluebill1049** [comment]
> I have this same error.
> 
> ` const handleDate = (date: Date) => { setDate(date) setValue('expMonth', date.getMonth() + 1) setValue('expYear', date.getFullYear()) } `
> 
> When onSumit is called, it doesn't contain the values updated by setValue.

share a codesandbox?

**Comment by Krausso** [comment]
Still getting error

**Comment by Champkinz** [comment]
Hey i don't know if this is help full, but if you try to setValue a value that is not registered or set on default values, it will not work properly.

**Comment by bluebill1049** [comment]
@Champkinz can you share a codesandbox? so I can look into it.

**Comment by Champkinz** [comment]
> @Champkinz can you share a codesandbox? so I can look into it.

I cant share the entire code block for nda reasons.

Basically what my issue was that I haven't used the `register()` function to register my **_variable_** (form item).
but I have set value too that **_variable_** using `reset()` function only.
and on a separate method im trying to a set value to that said **_variable_**, but it does not work as intended.

Solution was to register the **_variable_** on  component mount.

**Comment by bluebill1049** [comment]
Thanks, @Champkinz for the detail which version are you running?

**Comment by Champkinz** [comment]
> Thanks, @Champkinz for the detail which version are you running?

7.6.4v

**Comment by bluebill1049** [comment]
can you try with the latest @Champkinz

**Comment by Champkinz** [comment]
@bluebill1049 Sorry for the delay, i still have the same issue on new version.
