### ISSUE TITLE
Can't seem to update a field when using useFieldArray with setValue

### ISSUE THREAD

**Issue by dorsharon** [react-hook-form/react-hook-form#1564]
Please consider asking the question at our spectrum channel.

https://spectrum.chat/react-hook-form

**Describe the question?**

**To Reproduce**
1. use `useFieldArray`
2. try to update a certain field in all members of the array using `setValue`
3. `fields` is out of sync with `watch`

**Detailed explanation:**
I'm using useFieldArray to manage an array of objects.
One of the fields in these objects has to be set manually, since it affects the other array members (it's a toggle of who's the primary member of the array, toggling one as the primary toggles the others off)
Using setValue makes the `fields` object out of sync from what comes from `watch`.

**Comment by bluebill1049** [comment]
can you please follow the question template?

**Comment by dorsharon** [comment]
I updated my question, hopefully that's good enough to understand my problem

**Comment by bluebill1049** [comment]
<img width="729" alt="Screen Shot 2020-05-04 at 9 59 38 pm" src="https://user-images.githubusercontent.com/10513364/80963581-923aa200-8e52-11ea-8fde-a27dee530f4b.png">

**Comment by dorsharon** [comment]
Sorry, I've tried to replicate as best I could:
https://codesandbox.io/embed/react-hook-form-usefieldarray-template-2csgp?fontsize=14&hidenavigation=1&theme=dark

Right now, this is the only way I could keep them in sync, using both `setValue` and manually updating the `fields` array

**Comment by bluebill1049** [comment]
what're the steps to reproduce the issue?

> - use useFieldArray
> - try to update a certain field in all members of the array using setValue
> - fields is out of sync with watch

your original question above, i don't see `watch`

**Comment by dorsharon** [comment]
My point was that I was using both `watch` and `fields`.

Either way, regardless of those steps, my actual question is how do I manually set a value with a FieldArray in a way that will affect that field in all array members?
Since I must be doing something wrong, because the `watch` values get updated, while the `fields` is not

**Comment by bluebill1049** [comment]
> My point was that I was using both `watch` and `fields`.
> 
> Either way, regardless of those steps, my actual question is how do I manually set a value with a FieldArray in a way that will affect that field in all array members?
> Since I must be doing something wrong, because the `watch` values get updated, while the `fields` is not

I got your confusion now.

`setValue` is for set input's value, not about trigger re-render (state update).  If you want to trigger state update, then you will need to attach `watch`

take a look at the example below:

https://codesandbox.io/s/react-hook-form-usefieldarray-template-ykcqs?file=/src/index.js

**Comment by dorsharon** [comment]
I'm not seeing how you used `watch` in your sandbox.
Also, like I said, I used `setValue`, but then the result was that the `fields` object didn't receive the update.
How do I make sure it does?

**Comment by bluebill1049** [comment]
> Also, like I said, I used setValue, but then the result was that the fields object didn't receive the update.

Please read what I stated above, setValue doesn't trigger re-render only update the input value.

> How do I make sure it does?

use watch i have updated the codesandbox.

**Comment by dorsharon** [comment]
So if, for example, I want to render for each item if its `primary` or not, I can't use `item.primary` since that doesn't ever gets updated, I have to use `watch`?

**Comment by bluebill1049** [comment]
if you are not directly updating the `input` value, you have to use `watch`, `setValue` is targeting on the input hence we don't trigger re-render.

**Comment by bluebill1049** [comment]
`setValue`: only trigger re-render when an error occurred or disappeared
`watch`: re-render what's watched.

**Comment by dorsharon** [comment]
I see. Thanks for your replies!

**Comment by bluebill1049** [comment]
welcome :)

**Comment by dorsharon** [comment]
Hi, going through this again, this still doesn't to work for me.

I've updated the sandbox:
https://codesandbox.io/s/react-hook-form-usefieldarray-template-g6vdp

I've used `watch` and yet `item.primary` is still not updated ever as you can see.
even the value returned from `watch` is still wrong for some reason.

What am I supposed to do to make this right?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-usefieldarray-template-ykcqs?file=/src/index.js

not working above?

**Comment by dorsharon** [comment]
can't you do it without watching the whole array field?
I want to watch only a specific field, wouldn't watching all mean it re-renders on each field change?

**Comment by Chandu** [comment]
@bluebill1049 Thanks for the CSB, it helped me with the issue I was facing.
However with this approach, when I try to append a new record with default values, the values are not available while rendering.

You can see this @ https://codesandbox.io/s/react-hook-form-field-array-and-table-0pbu.
When you click on Add, you can see that against the label: 'Original Name' the default value I am passing ('Some Model') is printed.
However against the label 'Watched Label' the value is blank.

**Comment by bluebill1049** [comment]
@Chandu try to supply fields for the watch as default value

`watch('xxx', fields')` that should solve the problem.

**Comment by Chandu** [comment]
@bluebill1049  Thanks. It worked.

**Comment by Chandu** [comment]
@bluebill1049  One question though, as per the documentation @ https://react-hook-form.com/api/#watch the second parameter to the watch function is for providing a defaultValue and this would be returned if the property being watched is undefined (my interpretation).

But in the case of my CAB example @ https://codesandbox.io/s/react-hook-form-field-array-and-table-0pbut the proerpty `names` being watched is not undefined, then why does passing the fields as the second parameter to the watch function work?

**Comment by bluebill1049** [comment]
good question @Chandu here is what happend.

Because useFieldArray is relay on uncontrolled input as well (that's why no re-render when the user is typing), so which means state lives inside inputs, this also means there are times when we need to reshuffle the inputs and potentially destroy the association between inputs, so the updated input values will be ready until the next render phase is complete, by supplied a default value with fields it close the gap with that single render.

**Comment by ApolloEstrella** [comment]
I have an issue on react-hook-form. This is regarding useform watch and fields in fieldarray, they are not in sync
the contents of watch is not the same with "fields". I used watch("items").map instead of the fields.map to reliably get the actual values that I set using setValue. My expected behavior should be is the the fields array should reflect the contents of watch("items"). But there is a trade-off in performance re-rendering using watch("items"), when type on dynamic fields there is a delay. I also used watch("items", fields). Same behavior, there is a delay when typing on dynamic fields.

**Comment by bluebill1049** [comment]
> I have an issue on react-hook-form. This is regarding useform watch and fields in fieldarray, they are not in sync
> the contents of watch is not the same with "fields". I used watch("items").map instead of the fields.map to reliably get the actual values that I set using setValue. My expected behavior should be is the the fields array should reflect the contents of watch("items"). But there is a trade-off in performance re-rendering using watch("items"), when type on dynamic fields there is a delay. I also used watch("items", fields). Same behavior, there is a delay when typing on dynamic fields.

which version are you using? and maybe consider to use `useWatch`.

**Comment by ApolloEstrella** [comment]
Thank  you for the reply. I am using "react-hook-form": "^6.14.0",

**Comment by ApolloEstrella** [comment]
I will try to use useWatch now.

**Comment by chriszirkel** [comment]
I have had a similar problem: I'm using useFieldArray and watch this fields with useWatch to have changes within the fields reflected directly. When I loaded existing values from the database and populated the form via setValue, this didn't work with array fields. The values have been set via setValue(), but they were directly overwritten due to re-renders and inconsistencies between useFieldArray fields and useWatch.

I changed my code the following way and it works now:
- provide no default values via `<Controller>` component for field array fields (because they are not registered yet). I had default values for these input and when they got mounted, they were overwriting the loaded value from the database.
- `useFieldArray` and `useWatch` to get a controlled field array. the returned fields from `useFieldArray` should be used as defaultValue for useWatch, e.g. `useWatch({ name: 'parameters' , defaultValue: fields})``
- after data has been loaded, populate the form with `reset({ ... })` instead of `setValue()` 

I'm using `"react-hook-form": "^7.6.3"`.

**Comment by dancixx** [comment]
I have the same issue in nested field arrays. The top-level field array doesn't work properly, but the second one is good with fields.

```
Here doesn't work the fields.map just the watched returns.
const { control, watch, getValues } = useFormContext();
const { fields, remove } = useFieldArray({
            control,
            name: 'exercises',
        });
const watchedExercises: Array<WorkoutExerciseProps> = watch('exercises');

Here works the fields.map method.
const { control, watch } = useFormContext();
const { fields, append, remove } = useFieldArray({
        control,
        name: `exercises.${exerciseIndex}.exerciseSets`,
    });
```

**Comment by bluebill1049** [comment]
@dancixx can you provide a codesandbox with some more detail on the issue and steps to reproduce?

**Comment by dancixx** [comment]
@bluebill1049 I use this in a react-native program, I cant share more sorry.

But the base concept is I have Provider at App.tsx level and I have to a different screen where I try to use the FormContext api where the fields.map doesn't work. The second field array is on the same screen.
