### ISSUE TITLE
Validation of field array with yup (min length error) is not working properly

### ISSUE THREAD

**Issue by vilanelle** [react-hook-form/react-hook-form#1573]
**Steps to reproduce the behavior:**
1. Go to **sandbox**: https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-1bsmi?file=/src/index.js
2. Click on the "Add question" button to add an array item
3. Click on the "Remove question" button to remove the item
4. The error for min array length is not showing :(

**Expected behavior**
Validation should return the error on fail

Thanks in advance!

**Comment by bluebill1049** [comment]
Thank you, will patch this bug soon.

**Comment by bluebill1049** [comment]
after careful analyze, here is a proposal for the fix:

because when there is no item in the array field, react hook form will submit data as `{}`, which means in order for the schema validation to validate correctly we will have to append `required()`. react hook form's input state live inside inputs instead local state, which is the reason why when you submit the form, if there is not array field item, it will simply be omitted.

take a look at the example below and let me know your thoughts, I think what can do to make it work with at least one item in an array filed with a schema.

https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-pcyvy?file=/src/index.js:493-509

an alternative **solution** would be trigger validation at `useEffect` when array becomes empty.

**Comment by vilanelle** [comment]
Thanks for the quick reply, the proposed solution will work for us. Also, you're doing an awesome job with the library (and support), many thanks :))

**Comment by bluebill1049** [comment]
awesome, thanks @vilanelle I will put into a PR for this issue. thanks for the verification.

**Comment by szymexpawlowski** [comment]
Hi @bluebill1049 could you provide any estimate when this problem could be solved?

**Comment by bluebill1049** [comment]
I am busy trying to figure out a solution @szymexpawlowski, here is a ticket for you to track: https://github.com/react-hook-form/react-hook-form/issues/1617

**Comment by szymexpawlowski** [comment]
thanks a ton @bluebill1049
