### ISSUE TITLE
Focus on error goes to first error in order of registration rather than in DOM order.

### ISSUE THREAD

**Issue by arrocke** [react-hook-form/react-hook-form#1613]
**Describe the bug**
Focus on error follows input registration order, not DOM order. Definitely not a deal breaker for this amazing library, but it would make the user experience a lot cleaner.

**To Reproduce**
Steps to reproduce the behavior in the codesandbox link:
1. Click submit (focus goes to Extra Input)
2. Click append to add a new input above Extra Input.
3. Click submit again (focus still goes to Extra Input)

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-j0uff?file=/src/index.js

**Expected behavior**
I'd expect the focus on an error to go to the first field in the form that has an error using the order in the DOM. Right now if the first field with an error was added after the first render, it is not focused, but an input below it is.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chrome
 - RHF Version: 5.7.1

**Comment by bluebill1049** [comment]
That's expected behavior.

**Comment by arrocke** [comment]
I understand that this is how the library works currently, but can't this be improved? If you have an input with an error and another input after it is focused when you submit, then a low vision user will most likely tab forward to the submit button and miss that first input with the error.

**Comment by bluebill1049** [comment]
See the issue above that you raised as a bug? so for this lib is expected behavior. It's always easy to ask why this lib doesn't support this and that, but why not put into another perspective, do some deep investigation, and see if this is possible or even "easy" to implement before making a statement to be improved. 

here is my import:

I think this would not be an easy task for react hook form to know the exactly position of your input, especially when you can manipulate the with CSS, so it's achievable but not a simple task and I don't think it's would be a part of react hook form probably an external lib.

**Comment by arrocke** [comment]
I can appreciate that this request is difficult to implement and that is why you've chosen not to address this. I should have proposed this as a feature request instead of a bug. I apologize for that.

I would have liked to have heard your reasoning in your original response. I responded as I did because I didn't understand why this was an invalid request. Thanks for a great library

**Comment by bluebill1049** [comment]
Thanks for understanding. I think i may be overreacted on the above feature request. please let's move on, but what I stated above is correct, it's a tricky one to do combined with SSR, CSS and media query.
