### ISSUE TITLE
fieldArray `required` validation errors out even when array not empty

### ISSUE THREAD

**Issue by vilanelle** [react-hook-form/react-hook-form#1617]
**The `required` validation on field array gives a false-positive error when an array element is removed, but the array is not empty.** 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-um8sn?file=/src/index.js

**Expected behavior**
The `required` validation should pass when array is not empty

**Comment by bluebill1049** [comment]
hmmmi think what I did before is not correct, it's much easier to do at useEffect level and `setError`, probably won't work well with schema validation with useFieldArray with min length.

```
useEffect(() => {
  if (!fields.length) {
    setError('fieldArray', 'minLength');
  }
}, [fields])
```

**Comment by bluebill1049** [comment]
I have thought about this issue for the couple days already, I think I start to get my head straight, I will provide a solution/feedback on this one today.

**Comment by bluebill1049** [comment]
here is a feedback from spectrum: https://spectrum.chat/react-hook-form/help/im-in-trouble-with-usefieldarray-empty-instead-of-removing-field~5b9cd7d8-c64d-47f3-be67-3ea46cda1326

**Comment by bluebill1049** [comment]
My decision: for now, is not changing anything. Here are some of my reasons and thoughts:

React hook form embrace uncontrolled input, which is the reason why you would see empty results when Field Array is empty during submission because there isn't any input gets `register` into the hook.

eg:

```
{fields.map(() => <input ref={register} name="test" /> )}
```

if fields are empty then there won't be anything to be registered. so I did consider placing an empty `[]` when no fields are been registered, but then it conflicts with the nature of fields input and philosophy behind react hook form, those kinds of side effects are not ideal to introduce.

However, I did also invest sometimes for an alternative solution: 

https://codesandbox.io/s/react-hook-form-fieldsarray-yup-validation-y0pck?file=/src/index.js

most of the stuff in the CSB is trying to leverage existing API:

```jsx
const isInitalRender = React.useRef(true);
  const appendQuestion = () => {
    append({
      text: ""
    });

    if (errors.questions?.type === "min") {
      clearError("questions"); // always clear errors when there is add action.
    }
  };

  useEffect(() => {
    if (!fields.length) {
     // register an empty array when nothing is regsiter
      register("questions");
      setValue("questions", []);
      if (!isInitalRender.current) {
        triggerValidation();
      }
    } else {
      unregister("questions");
    }

    if (isInitalRender.current) {
      isInitalRender.current = false;
    }
  }, [fields, register, setValue, unregister, triggerValidation]);
```

**Comment by vilanelle** [comment]
Hi @bluebill1049, huge thanks for the effort put into providing a workaround for the issue! We do appreciate the limitations tied to this particular validation case (though we'll still look forward to a more declarative solution should you ever decide to add one :) ) Again, thanks for the awesome work you're doing!

**Comment by bluebill1049** [comment]
thanks, @vilanelle for understanding, I think with V6 `resolver` maybe a better solution for the validation part:

https://github.com/react-hook-form/react-hook-form-resolvers

```
import { yupResolver } from 'react-hook-form-resolvers';

const schema = ...;

const resolver = (data) => {
  const { values, errors } =  yupResolver(schema)(data);
  return { 
    values,
    errors: {
      ...errors,
     ...!data.fieldArray: { minLength: {} } : {}, // manually check if array field is empty and append error
    }
  }
}

useForm({
  resolver,
})
```

I will follow this one up again, once V6 is released.
