### ISSUE TITLE
When using suggested value form last input of browser, it will trigger event listener of "input" event that is registed in

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#201]
@bluebill1049 When using suggested value form last input of browser, it will trigger event listener of "input" event that is registed in

https://github.com/bluebill1049/react-hook-form/blob/a9409ef0787b263d227ac004d5259feb80ef38dd/src/logic/attachEventListeners.ts#L16

The listener performs validateAndStateUpdate() callback in 
https://github.com/bluebill1049/react-hook-form/blob/41374ccf58116a2f446ff47e3be43edaf98409ff/src/useForm.ts#L225

that also triggers a re-rendering.

At this time, the selected value is cleared because input value is not updated to form control object (onChange is not fired for change in text content).

You can re-produce this issue on my codesandbox sample above. Just type a value then submit and refresh the page. After that, click on input field to select suggested value from last input.

_Originally posted by @leapful in https://github.com/bluebill1049/react-hook-form/issues/144#issuecomment-520108523_

**Comment by leapful** [comment]
@bluebill1049 

Here is the codesandbox sample:
https://codesandbox.io/s/react-hook-form-input-event-d47lq

Steps to re-produce:
1. Enter text value for first input then click "Submit".
2. Refresh page and click on first input to select suggestion in the previous input text value in step 1.
3. Selected value is being cleared.

Root cause: When rendering form array, a form control object is used for each item in form array to hold and keep input value up-to-date in order to restore correct value whenever form array index is changed (remove a input of form array).
In case selecting value form browser suggestion, the change will trigger event "input" in react hook form to perform validation and re-rendering if possible. At this time, there is no update on form control object therefore the next re-rendering uses old value of form control  object (which is empty value).

This is not bug of react form hook, it's a side effect when handling form array with react form hook.

Solution: Update form control object by using values from input ref of form array when re-rendering.

Working sample:
https://codesandbox.io/s/react-hook-form-input-event-ebzxv

**Comment by bluebill1049** [comment]
thanks for the detailed issue report @leapful looking now

**Comment by bluebill1049** [comment]
Funny thing, it works for me...

1. submit a form
2. type the same word and click the autocomplete value
3. click on the autocomplete and value gets filled.

I think I may miss the step or something? I am on mac chrome.

**Comment by leapful** [comment]
@bluebill1049 It's only being cleared at the first selecting value. May be you can try to refresh the page then click on the input again ? I can re-produce it with Google Chrome on Ubuntu and macOS.

**Comment by bluebill1049** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10513364/62831375-727aa280-bc61-11e9-99b1-9240a066b63f.gif)

**Comment by bluebill1049** [comment]
weird... maybe I am not reproducing the right way.

**Comment by leapful** [comment]
@bluebill1049 I think I found the reason, you're using codesandbox sample that already apply the fix :D.

The sample with error is the other link:
https://codesandbox.io/s/react-hook-form-input-event-d47lq

**Comment by bluebill1049** [comment]
ha!

**Comment by bluebill1049** [comment]
now i can see the issue, hehe

**Comment by bluebill1049** [comment]
so it's input event trigger re-render... will see if can find a solution. if you have some idea, feel free to submit a PR @leapful 🙏

**Comment by bluebill1049** [comment]
it's potential due to `onChange` vs `input` event, if you change `mode` to `onChange` and remove `onChange` that may solve the problem.
