### ISSUE TITLE
isValid is false while there are no errors

### ISSUE THREAD

**Issue by smashercosmo** [react-hook-form/react-hook-form#2147]
**Describe the bug**
isValid property is false in formState while errors object is empty

**To Reproduce**
https://codesandbox.io/s/react-hook-form-useform-template-chn2x

**Expected behavior**
isValid should be true if there are no errors

**Comment by bluebill1049** [comment]
you will need to set mode to `onChange`

**Comment by smashercosmo** [comment]
Alright, sorry, missed that part

**Comment by smashercosmo** [comment]
Thanks

**Comment by hui21109** [comment]
documents said `This state is only applicable with onChange and onBlur mode.`
But I found it does not work with mode: 'onBlur'.

**Comment by bluebill1049** [comment]
@hui21109 can you share a codesandbox? need more info.

**Comment by hui21109** [comment]
I can't reproduce it on codesandbox so far, I will try my best. :(
But, is there any case that isDirty is false and isValid also false... ? 
this is what I get now.

**Comment by hui21109** [comment]
Sorry, I forget to extract `onBlur` from render function of Controller.
But it is a little weird that it is invalid (the resolver is checked) but get {} of error.

**Comment by eseakin** [comment]
I am having this issue as well, but in react testing library.
It is only happening when I use reset() to set the default values of the form after a gql query returns data.

Something like:

`const Form = ({ data, loading, error }) => {
  const { reset } = useForm({ mode: 'onBlur' });
  
  useEffect(() => {
    if(data)
      reset(data);
  }, [data])

  ...
}`

The actual implementation works fine, but for some reason the tests are showing isValid: false and isDirty: false even after updating the form and attempting to save it. Changing mode to onChange has no effect.

**Comment by bluebill1049** [comment]
> I am having this issue as well, but in react testing library.
> It is only happening when I use reset() to set the default values of the form after a gql query returns data.
> 
> Something like:
> 
> `const Form = ({ data, loading, error }) => {
> const { reset } = useForm({ mode: 'onBlur' });
> 
> useEffect(() => {
> if(data)
> reset(data);
> }, [data])
> 
> ...
> }`
> 
> The actual implementation works fine, but for some reason the tests are showing isValid: false and isDirty: false even after updating the form and attempting to save it. Changing mode to onChange has no effect.

`reset` is async, are you wrapped act with async?

**Comment by eseakin** [comment]
Yes it is wrapped with async.

The test is something like this:

`await act(async () =>{
  render(<form>) 
})

await act(async () =>{
  fireEvent.input(screen.getById(inputId))
})

await act(async () =>{
  fireEvent.click(screen.getById(submitButtonId))
})`

What is strange is the api data is mocked to be immediately available, so reset fires after the first render. Yet when I console log the render, I see that it takes 2 renders for the default values to show up after reset is called (using getValues). I'm assuming this is because the form has internal state that needs to be updated, which then needs to propagate to my component?

It turned out that the input event and the reset are happening on the same event loop, so reset seems to be overriding it, even though the input event is second. When it calls submit, isDirty is false because reset has cleared the input value.

Is there any way around this? I tried just putting a delay in between the initial render and the input event, but I think reset is happening after the input and clearing it. The code works in real use cases, and it is breaking only in the test.

(Thanks for your help!!)

**Comment by bluebill1049** [comment]
> It turned out that the input event and the reset are happening on the same event loop, so reset seems to be overriding it, even though the input event is second. When it calls submit, isDirty is false because reset has cleared the input value.

Do you have a code example above?

**Comment by eseakin** [comment]
https://codesandbox.io/s/awesome-dew-ly8m7?file=/src/App.js

Here this seems to illustrate it. I am calling reset(), then calling setValue() in the same function. Yet reset() overrides setValue() and the setValue() value never actually renders, as you can see in the console logs.

**Comment by bluebill1049** [comment]
> https://codesandbox.io/s/awesome-dew-ly8m7?file=/src/App.js

I think this is going to be problematic as `reset` is async under the hood, i would suggest maybe `watiFor` element change verified before invoking setValue.

**Comment by eseakin** [comment]
Oh that's exactly what I need! Perfect. Thank you for all your help!
