### ISSUE TITLE
[v6.0.6] Bug: Checkboxes are always being cast to strings despite providing boolean default value.

### ISSUE THREAD

**Issue by harrisrobin** [react-hook-form/react-hook-form#2241]
**Describe the bug**
I'm trying to use react-hook-form with checkboxes and even though the default values for said checkboxes are all booleans (false), as soon as I interact with the checkbox the form value gets cast to a string. I was able to reproduce this fully in the codesandbox below. 

**To Reproduce**
1. Create checkbox components with default values that are booleans
2. watch the values
3. check them and you will see that they are cast to strings.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-checkboxes-get-cast-to-strings-everytime-lioo1?file=/src/index.js

**Expected behavior**
I expect the checkboxes to not get cast into strings and simply change from `true` to `false` and vice versa.

**Screenshots**
![image](https://user-images.githubusercontent.com/3880008/87559844-cae3cc80-c688-11ea-8de7-3e86e66a800b.png)

@bluebill1049 it seems checkbox behaviour also randomly changed, i don't think I had this problem with older versions but will also double check.

**Comment by harrisrobin** [comment]
@bluebill1049 I can confirm this is a regression because if I downgrade back to 6.0.1, I don't have this problem anymore: 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/3880008/87584036-df38c100-c6aa-11ea-84e7-8e0946da2175.png">


I'm re-updating to latest in the code sandbox for you to look at, just figured this information would be helpful.

**Comment by chranderson** [comment]
@harrisrobin - I agree this looks like a regression related to the `Controller` component.
 I had a similar issue using rendering `<input type="checkbox" {...}>` inside a custom component via the `Controller` component.

**using v6.0.6**
- The checkbox input value is being changed to `'on'` instead of a `boolean` and the `Controller` component is passing props: `{onBlur, onChange, value}` to the custom input component (and in the render props).
- using `Controller`, the value matches `defaultValue` passed in `useForm`, but when checkbox is changed, it gets set to a string.
- If I render a native checkbox input using `ref={register}` (not using `Controller`), it works as expected.

**using v6.0.1** 
- The custom component rendered in a `Controller` worked as expected. 
- `Controller` component passes props: `{onBlur, onChange, checked}`, and does not pass the prop `value` to checkbox inputs.
- checked is a boolean value

**Comment by chranderson** [comment]
looks like it might be related to this update, but I did not see this mentioned in the docs anywhere.
https://github.com/react-hook-form/react-hook-form/pull/2140#issue-447145164

**Comment by harrisrobin** [comment]
I think the fact that it behaves differently when it comes to booleans in render prop vs not is going to confuse a lot of people.

**Comment by bluebill1049** [comment]
> * The custom component rendered in a `Controller` worked as expected.
> * `Controller` component passes props: `{onBlur, onChange, checked}`, and does not pass the prop `value` to checkbox inputs.
> * checked is a boolean value

Those concerns above are all valid.

Another reason is it leads to a bug (user reported) whenever a boolean value gets passes down, how Controller determines a checkbox is too vague. That's why `as` will simply pass down `onChange, onBlur, value` nothing more, for other usages like `checkbox` always stick with `rerender`, that gives you transparency and freedom on how you wire up your external component.

**Comment by harrisrobin** [comment]
@bluebill1049 I think some improvements to the docs with more checkbox examples and a search feature would help. I'll take a look at how the docs are setup and see if I can contribute something here.

**Comment by bluebill1049** [comment]
> @bluebill1049 I think some improvements to the docs with more checkbox examples and a search feature would help. I'll take a look at how the docs are setup and see if I can contribute something here.

That would be awesome. Thank you.

**Comment by bluebill1049** [comment]
<img width="943" alt="Screen Shot 2020-07-16 at 10 51 29 am" src="https://user-images.githubusercontent.com/10513364/87614035-51181580-c752-11ea-887d-5ccd770f2150.png">

perhaps place an example right there.

**Comment by bluebill1049** [comment]
<img width="579" alt="Screen Shot 2020-07-17 at 9 08 35 am" src="https://user-images.githubusercontent.com/10513364/87731139-1a530580-c80d-11ea-8977-59786fc32189.png">
<img width="1028" alt="Screen Shot 2020-07-17 at 9 08 57 am" src="https://user-images.githubusercontent.com/10513364/87731160-28a12180-c80d-11ea-9db4-3f7084399c8b.png">

updated both the doc and CSB to emphasize checkbox example.

**Comment by ikbal-nayem** [comment]
I am using "react-hook-form": "^7.8.3",
This does not update the status of the checkbox of "Material-UI".

**Comment by Anugraha123** [comment]
onChange(JSON.parse(e.target.value))

just a workaround
