### ISSUE TITLE
Checkbox value is string

### ISSUE THREAD

**Issue by popuguytheparrot** [react-hook-form/react-hook-form#2322]
**Describe the bug**
Checkbox set value to string like "false"

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-controller-sdtly
2. Click on checkbox 
3. See in results

**Expected behavior**
value be boolean 

![image](https://user-images.githubusercontent.com/19804652/88191364-09a6f300-cc44-11ea-8ce8-525c3784e3ac.png)

**Comment by dandv** [comment]
[I've just run into this **critical** regression too](https://codesandbox.io/s/rhf-608-mui-checkboxes-with-clickable-labels-50ddn), and it breaks any GraphQL integration that expects strict types. This worked fine in 6.0.0-rec5.

**Comment by bluebill1049** [comment]
@popuguytheparrot I think you got an old CSB: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

@dandv This was due to an issue report on Component which returns `boolean` value but it's not a Checkbox. We are no longer determine checkbox inside `Controller`, It's problematic to assume any giving value is `boolean` value is a `Checkbox`, so moving forward use `render` prop for any none standard `value` `onChange` `onBlur` component, which includes Checkbox, DatePicker and etc.

**Comment by popuguytheparrot** [comment]
@bluebill1049 
Need fix this example 
https://react-hook-form.com/get-started#IntegratingwithUIlibraries

**Comment by bluebill1049** [comment]
thanks @popuguytheparrot can you share the codesandbox link? this one looks working: https://codesandbox.io/s/react-hook-form-with-ui-library-lg33x

**Comment by dandv** [comment]
@bluebill1049 thanks for the link to the Changelog. This is a breaking change though, maybe it should've happened on a minor version (6.1.0), not on the patch version level?

**Comment by dandv** [comment]
@bluebill1049 thanks for the link to the Changelog. This is a breaking change though, maybe it should've happened on a minor version (6.1.0), not on the patch version level?

Re. the codesandbox, https://codesandbox.io/s/react-hook-form-with-ui-library-lg33x doesn't include a checkbox demo, and https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/index.js uses RHF 5. [Updating the latter to RHF 6](https://codesandbox.io/s/react-hook-form-controller-tpc7b) produces string instead of boolean.

**Comment by bluebill1049** [comment]
thanks @dandv valid points, I will sort them out and update the doc.

**Comment by corysimmons** [comment]
@bluebill1049 Any chance of looking at this one again? My team has been running into react-hook-form casting checkbox values to strings a lot. I don't see the reason for it to be casted to a string.

**Comment by bluebill1049** [comment]
hey @corysimmons if you don't provide a `value`, react hook form will return `boolean`, otherwise, it will return the value associated with your checkbox/radio. If this is not your desired option, then probably building a controlled input and wrapped with a controller is something you guys can look into.
