### ISSUE TITLE
Ability to call trigger() on fieldArray fields

### ISSUE THREAD

**Issue by benswinburne** [react-hook-form/react-hook-form#2381]
It'd be useful to be able to call `trigger()` on field arrays.

A minimum API would be `trigger('myfield[i].property')`

Further potential APIs

`trigger('myfield')` iterates over `myfield[]` and `Object.values()`
`trigger('myfield[0]')` iterates over `Object.values()`

**Additional context**

Related discussion https://github.com/react-hook-form/react-hook-form/issues/2379

**Comment by bluebill1049** [comment]
what about leverage regex `trigger(/^test/)`?

**Comment by dwiyatci** [comment]
@bluebill1049 @benswinburne I'm sorry, here as far as my understanding goes, after following the discussion #2379, `trigger('fields[i].property')` is already supported because `fields[i].property` is basically a `fieldName`, right?

**Comment by bluebill1049** [comment]
> @bluebill1049 @benswinburne I'm sorry, here as far as my understanding goes, after following the discussion #2379, `trigger('fields[i].property')` is already supported because `fields[i].property` is basically a `fieldName`, right?

right now, it only works for the input name.

**Comment by dwiyatci** [comment]
🤔 Hm ok, just to clarify again ('cause I'm also gonna use this manual trigger for fieldArray elements in my project 😁): here in my CSB (https://codesandbox.io/s/react-hook-form-usefieldarray-forked-wu88d?file=/src/index.js), since `` `test[${index}].firstName` `` is an input name, `` trigger(`test[${index}].firstName`) `` works, right?
