### ISSUE TITLE
[useFieldArray] The value will be the default value when removed all fields

### ISSUE THREAD

**Issue by chouandy** [react-hook-form/react-hook-form#2382]
**Describe the bug**
The value will be the default value when removed all fields. If the arguments of useForm has defaultValues.

**To Reproduce**
1. Go to the codesandbox provided below
2. Remove all array fields
3. Click submit
4. See console output

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-cqvfs

**Expected behavior**
The data of the submission should be an empty array.

**Desktop:**
 - OS: macOS
 - Browser: chrome
 - Version: 84.0.4147.89

**Comment by bluebill1049** [comment]
@keiya01 i think this could be an issue caused by `getValues()` fix?

**Comment by keiya01** [comment]
@bluebill1049 
i think so too... i will fix this issue.

**Comment by bluebill1049** [comment]
Thanks heaps @keiya01 👍

**Comment by bluebill1049** [comment]
@keiya01 This is actually a tricky one, chicken, and egg situation. I guess that was the first reason why i didn't want to include getValues() to return default values.

**Comment by keiya01** [comment]
> @keiya01 This is actually a tricky one, chicken, and egg situation. I guess that was the first reason why i didn't want to include getValues() to return default values. (perhaps check if there is nothing registered)

Hmm, I think we should provide option about while `defaultValue` should be included in passed value from `getValues()` and `handleSubmit` or not. Because I think passed value from these method need to be same.

**Comment by bluebill1049** [comment]
@keiya01 `handleSubmit` we should use the `getFieldsValues` method and ignore the `defaultVlaues`.

**Comment by chouandy** [comment]
> @keiya01 `handleSubmit` we should use the `getFieldsValues` method and ignore the `defaultVlaues`.

Hi @bluebill1049,
Will the field value of `watch` method be empty array? I currently use `useEffect` method to monitor the field value. If the field value is empty array by updating, I use `reset` to set the field value to empty array. This is a workaround solution.

**Comment by bluebill1049** [comment]
Thanks, @chouandy we should fix this issue soon. 🙏

**Comment by chouandy** [comment]
Hi @bluebill1049, thank you for fixing the issue of the submission data. But I am still confused about the `watch`, `getValues`, and `useWatch` methods for the same case.

<img width="847" alt="Screen Shot 2020-07-29 at 00 49 40" src="https://user-images.githubusercontent.com/5448836/88696207-8a2e8d80-d135-11ea-8ca7-e3a94dffc877.png">

The above pic is a description of the `watch` method. The `defaultValues` will only return at the first render. But in the same case, when I remove all the fields, the value of the methods return is the default value instead of an empty array.

You can check the codesandbox link.
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-lr0o6

**Comment by bluebill1049** [comment]
looks like `getValues` still having an issue... it should return `{}`

**Comment by bluebill1049** [comment]
hi guys,

This `getValues` and `watch` confusion bothers me a lot, I think for better change shall we do the following: if any field got registered, we will internally mark the form as been registered and no longer return `defautlValues` with further re-render.

@kotarella1110 @keiya01 @JeromeDeLeon please let me know your thoughts, if we can align we shall release a minor release and fix this once for all and update doc accordingly.

cheeers
bill

**Comment by JeromeDeLeon** [comment]
When do you think is the better time to return the `defaultValues`?

**Comment by JeromeDeLeon** [comment]
I will try to think of this later as I am having a presentation today. 😬😬

**Comment by bluebill1049** [comment]
good luck @JeromeDeLeon.

**Comment by bluebill1049** [comment]
I want getValues to return empty values despite defaultValues, but quite a few users want this feature:

https://github.com/react-hook-form/react-hook-form/issues/2320

so to solve this problem, marking `registered` inside the app will help this issue, with reset API reset that flag.

**Comment by keiya01** [comment]
I think we can revert #2359 because we have workaround. Workaround pass `defaultValue` directly if returned value is empty.

The following CSB is v6.0.8 before my change is applied.
https://codesandbox.io/s/exciting-saha-wqtrz?file=/src/App.js

I should have thought of it before I change this feature...

**Comment by bluebill1049** [comment]
shall we make the following change

only return `defautlValues` with `watch, getValues, useWatch` before initial render (before any inputs get registered) so they all aligned.

**Comment by keiya01** [comment]
> shall we make the following change
> 
> 
> 
> only return `defautlValues` with `watch, getValues, useWatch` before initial render (before any inputs get registered) so they all aligned.

i think we should do not return defaultValues before initial render.

**Comment by bluebill1049** [comment]
> > shall we make the following change
> > only return `defautlValues` with `watch, getValues, useWatch` before initial render (before any inputs get registered) so they all aligned.
> 
> i think we should do not return defaultValues before initial render.

I totally agree! how can we let the users agree with that? That's the tough part, that was the reason why I didn't want to bring `defaultValues` in v6 with `getValues()`, it create a lot of side effects.

https://github.com/react-hook-form/react-hook-form/issues/2308

**Comment by bluebill1049** [comment]
Thoughts: 

1. getValues() only return what's in the form
2. watch() return what's in the form and `defaultValues` before render

**Comment by bluebill1049** [comment]
@h-sakano I think this topic is relevant to you as well, maybe you can include your thoughts as well.

**Comment by bluebill1049** [comment]
FYI @keiya01 revert #2359

**Comment by keiya01** [comment]
> > > shall we make the following change
> > > only return `defautlValues` with `watch, getValues, useWatch` before initial render (before any inputs get registered) so they all aligned.
> > 
> > 
> > i think we should do not return defaultValues before initial render.
> 
> I totally agree! how can we let the users agree with that? That's the tough part, that was the reason why I didn't want to bring `defaultValues` in v6 with `getValues()`, it create a lot of side effects.
> 
> #2308

Could we suggest getting default value by user side ?

like below.

> I think we can revert #2359 because we have workaround. Workaround is to pass defaultValue directly if returned value is empty.
>
> I applied my workaround. The following CSB is v6.0.8 before my change is applied.
> https://codesandbox.io/s/exciting-saha-wqtrz?file=/src/App.js

> I should have thought of it before I change this feature...

**Comment by bluebill1049** [comment]
> > > > shall we make the following change
> > > > only return `defautlValues` with `watch, getValues, useWatch` before initial render (before any inputs get registered) so they all aligned.
> > > 
> > > 
> > > i think we should do not return defaultValues before initial render.
> > 
> > 
> > I totally agree! how can we let the users agree with that? That's the tough part, that was the reason why I didn't want to bring `defaultValues` in v6 with `getValues()`, it create a lot of side effects.
> > #2308
> 
> Could we suggest getting `defaultValues` by user side ?
> 
> like below.
> 
> > I think we can revert #2359 because we have workaround. Workaround is to pass defaultValue directly if returned value is empty.
> > I applied my workaround. The following CSB is v6.0.8 before my change is applied.
> > https://codesandbox.io/s/exciting-saha-wqtrz?file=/src/App.js
> 
> > I should have thought of it before I change this feature...

Yes, I think there are multiple ways they do that at app level, it's much easier to having logic embed inside RHF.

**Comment by bluebill1049** [comment]
@chouandy for watch and `useWatch` API with useFieldArray, if you want to garment the watch is what's on the fields after the deletion (so it doesn't fall back to defaultValues), you can use `fields.length` check, if that helps. I will update the doc regarding the statement as it's made for normal form instead of fieldArray.

**Comment by chouandy** [comment]
@bluebill1049 OK, thank you~

**Comment by JeromeDeLeon** [comment]
> > shall we make the following change
> > only return `defautlValues` with `watch, getValues, useWatch` before initial render (before any inputs get registered) so they all aligned.
> 
> i think we should do not return defaultValues before initial render.

Hmm... makes sense because this is only at initial render when there are no fields  being registered on RHF.

**Comment by shinpou** [comment]
@bluebill1049 I'm not sure this is a real fix for the problem. The intended use case for useForm and more generally, useFormContext is the idea that you can separate your form into distinct components and refer back to the higher level form via useForm. 

It is then also natural to expect, that the _watch_ for the whole form data exists on a higher order component that has no idea about the specific data model of a component that lives underneath, or that useFieldArray is being used inside a specific component. Now, the workaround suggested here actually makes that abstraction leak, because any watch that is put into a higher order component **needs to circumvent this problem on their respective level.**

**Comment by bluebill1049** [comment]
> @bluebill1049 I'm not sure this workaround is sufficient. The intended use case for useForm and more generally, useFormContext is the idea that you can separate your form into distinct components and refer back to the higher level form via useForm.
> 
> It is then also natural to expect, that the _watch_ for the whole form data exists on a higher order component that has no idea about the specific data model of a component that lives underneath, or that useFieldArray is being used inside a specific component.
> 
> Now, the workaround suggested here actually makes that abstraction leak, because any watch that is put into a higher order component **would need to circumvent this problem in the watches that they create**. And I think you'll find that this is not doable because the parent component has no way of discerning, if the output of the child component's field value is **set to a value that resembles defaultValue by intent**, or **set to a value that we mean as empty, because it looks like defaultValue** - therefore the parent can also not save the correct data into a backend.
> 
> Also, the child component, that uses _useFieldArray_ also has no means to indicate that the intent is to write an empty field value the form data over the data that it was reset to.
> 
> I think personally, that defaultValue should only be used to initialize the form state on initial render, and never come back to haunt anyone later. Moreover, it is unintuitive that calling "remove" on useFieldArray now appears to have a side-effect.

Thanks for the feedback. we are addressing this issue at v7 (already working in progress). However, I think that's not a problem right now at v6, can you share a codesandbox to demonstrate the issue?

**Comment by shinpou** [comment]
Thank you for the quick answer @bluebill1049 :) 

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-vkx7k?file=/src/index.js

We tried with our team to demonstrate the exact problem with the abstractions here. In doing this, we really carefully tried to understand the difference between getValues and watch being done from a higher order component. The way we understand it is that watch always returns a "prevalidated" state of the form and any value, which is in a prevalidated form state has this behaviour where it is reset to the defaultValue. 

I added a comment into the specific spot where the issue with the abstraction exists. There is no way to fix the data that our subcomponent is returning from watch inside the parent component because it shouldn't have to know, that the child component is using useFieldArray.

Maybe we are missing a way to make the subcomponent in a such a way, that it can set the fieldvalues to a empty array which would override the defaultvalue being set from a parent level inside watch?

To see our test, just click on remove 3 times, and note the difference in the outputs of submit, watch and getValues. We couldn't use the output of the watch value for any logic or saves. I think our confusion, and why we have trouble with this comes largely from not understanding the nuance differences in when should one use watch vs. getValues.

The documentation states:

> An optimized helper for reading form values. The difference between watch and getValues is that getValues will not trigger re-renders or subscribe to input changes.
> 
> Important: You shouldn't use this method inside render. This is suitable for reading values in an event handler.

I think, there is an important unmentioned difference in them that causes the defaultValue behaviour and we just don't understand it.

**Comment by bluebill1049** [comment]
@shinpou validate the points above. 

- `getValues()` doesn't return `defaultValues` 
- `watch('fieldArrayName)` for useFieldArray should only watch specific field array (design limitation with v6)
- `defaultValues`is made for the initial render, now it gets injected into the watch as defaultValue and also as a fallback for undefined value, this is confusing and I am addressing this in v7

**Comment by shinpou** [comment]
I would agree with all of those points indeed. 

To further clarify the architectural concern, what we're trying to do with our architecture, is have the logic for when to perform saves, updates, get requests - what buttons are shown and what I would call "form boilerplate" to live in a higher order component. We've had great success with this for all things other than useFieldArray for two reasons:
- it has this defaultvalue behaviour which we cannot reason about from the higher order component (we can't discern valid from invalid empty state)
- useFieldArray also requires useFieldArray to be called before reset() - which is impossible in this hierarchy - our parent component knows when the backend sends new data, and calls reset() accordingly for the whole set of subcomponents - useFieldArray should simply conform to this reset data

**Comment by DylanVann** [comment]
Just an idea, maybe there should be a concept of `initialValues` instead of `defaultValues`:

- I would expect a `defaultValue` to be defaulted to if a value is `undefined`.
- I would not expect a `initialValue` to be defaulted to if a value becomes `undefined`.

Aside from that though I would think a field array when all items are removed should become `[]`, not become `undefined`, so maybe it shouldn't even apply in that case.

Personally I was trying to get a field array to persist across reloads. Existing persist solutions for `react-hook-form` rely on `setValue`, which means you cannot render the form in the correct state on the first frame. My solution was to wrap `useForm` and use `defaultValues`. What would happen is that when all items were removed the value for the form state returned by `watch` would return what had been the persisted values.

This was my solution:

```tsx
import { useEffect, useState } from 'react'
import { useForm, UseFormMethods } from 'react-hook-form'
import { FieldValues, UseFormOptions } from 'react-hook-form/dist/types'

const empty: string[] = []

export function useFormPersisted<
  TFieldValues extends FieldValues = FieldValues,
  TContext extends object = object
>(
  options: UseFormOptions<TFieldValues, TContext> & {
    storage?: Storage
    name: string
    fieldArrays?: string[]
  },
): UseFormMethods<TFieldValues> & { clear: () => void } {
  const {
    name,
    defaultValues,
    storage = sessionStorage,
    fieldArrays = empty,
  } = options
  const [savedValues] = useState(() => {
    try {
      return JSON.parse(storage.getItem(name) as string)
    } catch (e) {
      return {}
    }
  })

  const formMethods = useForm<TFieldValues, TContext>({
    ...options,
    defaultValues: {
      ...savedValues,
      ...defaultValues,
    },
  })

  const { watch } = formMethods

  const values = watch()
  const fieldValues = fieldArrays.reduce((acc, name) => {
    let value: any[] | undefined = watch(name)
    if (value instanceof Array) {
      value = value.map((v) => ({ ...v, id: undefined }))
    }
    return {
      ...acc,
      [name]: value,
    }
  }, {})

  const allValues = {
    ...values,
    ...fieldValues,
  }

  useEffect(() => storage.setItem(name, JSON.stringify(allValues)))

  return {
    ...formMethods,
    clear: () => storage.removeItem(name),
  }
}
```

This does require you to know the names of your field arrays ahead of time.

**Comment by bluebill1049** [comment]
Thanks, @DylanVann for share your feedback and solutions. It's an indeed tricky one for field array, hook form's input value stored at the input level, so when all inputs get removed by action, there is no field any more on the screen, which results in `undefined` instead of empty `[]`, now I completely understand this is a pain for certain usages. I am working on V7 right now, feel free to include your solution or idea in there, hopefully, we can come up with a good solution on this. https://github.com/react-hook-form/react-hook-form/discussions/3714
