### ISSUE TITLE
MUI Checkbox not working from v6.0.3 onwards

### ISSUE THREAD

**Issue by prasadsrg** [react-hook-form/react-hook-form#2439]
MUI Checkbox not working from 6.0.3 onwards, below 6.0.2 working fine.

In the below link  go dependency  and  reach-hook-from change the latest version change the checkbox andMUI Switch is not working.

https://codesandbox.io/s/react-hook-form-controller-xnqs4?file=/src/index.js

**Comment by bluebill1049** [comment]
hey @prasadsrg, take a look at this codesandbox: https://codesandbox.io/s/react-hook-form-v6-errormessage-dn4y8

you should start to use `render` for any of those boolean value, this was causing an issue at the lib level, and we fixed by removing that internal logic to determine `checkbox`, i should have made a minor version for this "fix", which is my bad. 

you can keep an eye on the changelog next time as well :)

https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md
