### ISSUE TITLE
🏎 Performance of ref API

### ISSUE THREAD

**Issue by pandaiolo** [react-hook-form/react-hook-form#26]
Hi, I am opening a regular issue as I was not sure what to open, feel free to close if inappropriate.

You chose a different API than other library authors on how to register input elements in the form state. Most other libs use some kind of helper like `<input {...registerField({ name: 'abc', ...)} />`.

I tend to prefer yours because it looks cleaner in the code. Do you see any downsides? Is there a performance tradeoff that you know of? What happens under the hood? Are you bailing out of standard react APIs? Do you have to use DOM elements directly, or use DOM event binders? (which other may not have to, as they use standard props / event binders)

Any insight appreciated, on performance or otherwise.

Thanks for the library 👍

**Comment by bluebill1049** [comment]
Hey @pandaiolo,

aha I love this question and I am more than happy to answer the question!

##Story:

Ok a bit of story mode here, if you don't mind, I work for a startup company which involves working on forms every day, formik and redux form you probably heard them all, then React Hook came out I was like maybe we can simplify the shit out of these forms. The first approach was just like others spread operator, so no point at all. the second approach was thinking about useContext API from Hooks, oh boy It didn't turn out pretty... and work colleges telling me I am wasting my time and just use X. so I said 'fuck off', let me do my shit, haha and finally I have this idea to use `ref` and having validation stuff similar to `Angular 1` (i think angular 1 dealing with form is excellent)

##Insight:

React hook form is taking a different approach than others library because it's not typically controlled input 
`<input onChange={this.handler} value={this.state.value />` 
instead, it's uncontrolled
`<input ref={regsiter} />` (basically naked version)
so benefit out of the box is 0 re-render onChange with state update, and you are no longer need to have a Component wrapper around or things like `<input {...registerField({ name: 'abc', ...)} />` because it's uncontrolled. the only source true which it's holding is the ref, now ref is really the HTML dom and you can retrieve and validate value without any harm. so what about invalidate inputs, yes I have attached each input with event listeners as a safeguard to revalidate inputs error. so what about GC, you will end up 2000 thousand event listeners end of the day, thanks to mutation observer https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver I can safely remove event listener when the input gets removed. 🍾 

##Performance benchmark time:

http://react-forme.now.sh

Hook Form
![image](https://user-images.githubusercontent.com/10513364/57109225-3be6df00-6d78-11e9-8922-795cd79f3dd1.png)

Formik
![image](https://user-images.githubusercontent.com/10513364/57109232-3f7a6600-6d78-11e9-9a50-8b9b8cea48f8.png)

ReduxForm
![image](https://user-images.githubusercontent.com/10513364/57109237-430ded00-6d78-11e9-8e42-4db09c91ed97.png)

as you clearly see less mount, quick execute and the following link show 1000 fields bit of crazy case:
https://github.com/bluebill1049/react-hook-form-performance-compare

Conclusion, I am not competing with Formik and Redux Form here, I am not a rock star dev like these guys, just play around with my shit as an average dev. it's a completely different approach which some people may find it useful and enjoy using (hopefully) we are using in production at work, so far it's approved its simplicity and value. (devs here love it, even the guy told me I am wasting of my time heheh) 😋 

my English is bloody terrible so hope these make sense. Enjoy coding :)

Cheers
Billy

**Comment by pandaiolo** [comment]
Hey @bluebill1049, thanks a lot for the detailed answer. Really appreciated. You are abstracting the "non-react" way to the consumers of your lib, so I guess it's perfectly fine!

I'll definitely give it a try especially if you say you're using this in production without hiccups.

**Comment by afgallo** [comment]
@bluebill1049, you are a legend mate! Very happy to see the progress of your library, well done 👍

**Comment by bluebill1049** [comment]
welcome back @afgallo ❤️

**Comment by et** [comment]
@bluebill1049 - thanks for the benchmarks. Any chance you could add [react-final-form](https://github.com/final-form/react-final-form) to the mix?

**Comment by bluebill1049** [comment]
@et sure, I can take a look that as well, the general idea is React Hook Form is uncontrolled component other controlled, so it has the advantage of mounting faster cause it doesn't require extra render/mount (controlled component or render props)

basically this
```
<ControlInput>
  <input />
</ControlInput>
```

with uncontrolled, you only do this 
```
  <input />
```

in turns of re-render, because it's uncontrolled hence the library itself is driving and optimizing when to re-render.

**Comment by et** [comment]
@bluebill1049 - Fantastic response! Thank you for that.

> because it's uncontrolled hence the library itself is driving and optimizing when to re-render.

Is this safe? In other words, won't this be susceptible to bugs that are hard to catch?

**Comment by bluebill1049** [comment]
it's safe :) @et, because it's a form lib hence it's constrained to only trigger a re-render with relevant tasks, eg when a user `onBlur`, when user change `input` and etc... 
(re-render is trigger by `useState`)

**Comment by cihataykas** [comment]
> **Story**
> 
> Ok, a bit of story mode here (if you don't mind). I work for a startup company, which involves working on forms pretty much every day, technologies like Formik and Redux form which you probably heard them all. About two months ago, React Hook came out, and I was like maybe I can simplify the shit out of these forms. The first approach was just like others by using spread operator on input props, so I guess no point at all to do the same stuff again. The second approach was thinking about useContext API from Hooks, oh boy It didn't turn out pretty... and workmate was telling me that I am wasting my time and just use X. so I said fuck off, let me do my shit, haha and finally I have this idea to use `ref` and having validation stuff similar to `Angular 1` (i think angular 1 did a great job on form)

@bluebill1049 this is the story that i'm in it 😄 . Thank you for this awesome library. I love it. I saw it when i was trying to achieve same thing and when i almost coded my approach, i was thinking; "Yeah i think it is good now", and i saw your approach. Then i was like "Man! fuck it! this is far better 😄"  

I have a question in my mind.  For the adding/removing side effects like event listeners, Why you did not use useEffect() for the process. Can't we achieve the same result with it rather than MutationObserver?

Cheers

**Comment by bluebill1049** [comment]
Thank @cihataykas! Your words made by day! 😸Because all the inputs are essentially uncontrolled component (basically raw DOM element the `ref`), there won't be any lifecycle with them and `useEffect` wouldn't work. The only solution for me was to use native DOM methods `MutationObserver`.

**Comment by cihataykas** [comment]
@bluebill1049 Man your idea is cool ❤️.  to reach the point, react way has more boilerplate than yours imho. My breakpoint was which one of the deadpoints,  is, to bind a `ref` in render, we can't use a function which holds `useRef` and returns it which breaks rules hooks. Or generating references dynamically.

**Comment by bluebill1049** [comment]
@cihataykas do you mean to share the ref with others usage?

```
import React, { useRef } from "react"
import useForm from "react-hook-form"

function App() {
  const { register, handleSubmit } = useForm()
  const firstNameRef = useRef()
  const onSubmit = data => alert(JSON.stringify(data))

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input name="firstName" ref={(e) => {
        register(e)
        firstNameRef.current = e // you can still assign to your own ref
      }} />
      <input name="lastName" ref={(e) => {
        // register's first argument is ref, and second is validation rules
        register(e, { required: true })
      }} />

      <button>Submit</button>
    </form>
  );
}
```

**Comment by cihataykas** [comment]
@bluebill1049 Well, not really 😃. My bad that my english is not enough to tell the right topic. Actually i need an insight. And i wonder what you think.  let me tell you more specific:

You said, you tried to do same thing before with `useContext` or `useState`. And you did not like it the result. Hence you made your pattern. I'm trying to think another way just for brainstorming.

What if i make it this way:
```
import useForm from "react-hook-form"

function App() {
 // using a hook rather than regular register()
  const { useRegister, handleSubmit } = useForm()
  const onSubmit = data => alert(JSON.stringify(data))

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      // The point is, i want to perform the same idea with hooks. 
      // I want to store all the field refs in useState. 
      // So i can handle the state with react way. 
      // below example is might not be an appropriate usage.
      <input name="lastName" ref={useRegister(e, { required: true })} />
      <button>Submit</button>
    </form>
  );
}
```
What are your insights about it?

**Comment by bluebill1049** [comment]
@cihataykas I don't think that would work, because when you using `ref` you are leveraging uncontrolled input features. 

if you want to use `useEffect` you can do the following tho

```
// the register will have `value` and `onChange` as props

<input {...register} />
```

**Comment by cihataykas** [comment]
@bluebill1049 Exacly. that makes them controlled.

i can get the ref via a custom hook and i make it controlled like this:
https://codesandbox.io/embed/infallible-tdd-hbrb1 

 So we loose re-rendering optimisation right?

to solve the problem i was thinking that if i use debounce pattern, it might bring a solution but not enough comparing your approach imo.

**Comment by bluebill1049** [comment]
It's perfectly fine to build a form hook with controlled input. :) 

you will have to `setState/useState` during input `onChnage`, which is fine to re-render too.

I think `react-hook-form` leverage both `uncontrolled` and `custom hook`, which making form building a bit closer to build native HTML form because you only have to do 

`<input name="test" ref={register} />`

**Comment by cihataykas** [comment]
> It's perfectly fine to build a form hook with controlled input. :)
> 
> you will have to `setState/useState` during input `onChnage`, which is fine to re-render too.
> 
> I think `react-hook-form` leverage both `uncontrolled` and `custom hook`, which making form building a bit closer to build native HTML form because you only have to do
> 
> `<input name="test" ref={register} />`
> 
> I am not a big fan of doing spread operator on the props but doesn't mean it's a bad thing to do. I personally prefer to see each `prop` on the component.

Definetly. thank you for the perspective. i think i'm satisfied enough 😄

**Comment by JeromeDeLeon** [comment]
Thanks for this awesome library 😁! I just converted one of my forms from formik because it uses an array of inputs then calculate the sum and it causes a lag whenever it reaches more than 10 rows because it keeps re-rendering for every keystroke. I tried using debounce just to ease the pain of my form 🤣. When I switched to this, I didn't have that problem anymore. Thanks 😄

**Comment by bluebill1049** [comment]
thank you @JeromeDeLeon and most welcome ❤️ going to follow up those issues that you reported.

**Comment by michaeltomasik** [comment]
How Can I test that values are changing? After using `jest` and  `mount` from `enzyme` it returns 
` <input className="oldPassword" name="oldPassword" type="password" />` when usually I have value set and I can easily check what is rendered

**Comment by bluebill1049** [comment]
@michaelbirchler what do you try to test?
