### ISSUE TITLE
Display automatically an error message

### ISSUE THREAD

**Issue by sonatard** [react-hook-form/react-hook-form#2659]
**Is your feature request related to a problem? Please describe.**

I don't want to add `ErrorMessage` Component in my React Component.

**Describe the solution you'd like**
HTML 5 input attribute validation.
https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

HTML5 form validation display error message automatically.

![error-firefox-win7](https://user-images.githubusercontent.com/1586910/90758480-10478980-e31a-11ea-8df1-9e562e2d7925.png)

If I set validation and message to React Hook Form like following code, I want to display HTML5 form validation error message like the above image.

```tsx
      <input
        id="password"
        name="password"
        ref={register({
          required: "required",
          minLength: {
            value: 5,
            message: "min length is 5"
          }
        })}
        type="password"
        setCustomValidity // Option: Display automatically an error message or not
      />
```

**Additional context**
setCustomValidity Function enable to change HTML5 form validation error message.

**Comment by bluebill1049** [comment]
we did that in V3: https://react-hook-form.com/v5/api#Browserbuiltinvalidation but the feature never pick up in the community, so probably not going to reimplement it anytime soon, but will tag it with a feature request.

**Comment by sonatard** [comment]
I see.  Thank you for tagging it as a feature request.

**Comment by bluebill1049** [comment]
no worries @sonatard once the upvotes is increased, we will bring it back.

**Comment by bluebill1049** [comment]
Please cast your vote: https://twitter.com/HookForm/status/1402189525057638413

**Comment by CSFlorin** [comment]
@bluebill1049 shouldUseNativeValidation seems to not use the validationRule's message. This could be implemented using the setCustomValidity API @sonatard originally mentioned. It's odd because it seems you do use that API in https://github.com/react-hook-form/react-hook-form/blob/dd547079dc12b55fa44bd0135a94a8f5d595dfcc/src/logic/validateField.ts#L54 but I don't see it working in version 7.32.1

**Comment by CSFlorin** [comment]
@bluebill1049 shouldUseNativeValidation seems to trigger even when there isn't a validation error yet. Even if I change mode and revalidateMode to onSubmit. Opening the form for the first time already shows the native validation message whereas I only intend to show it when there is an error. Since there's no error, it just shows the default message. Also it seems to apply some new rule that doesn't allow me to submit even when it is correct. Only removing shouldUseNativeValidation fixes it.
