### ISSUE TITLE
Holes in array

### ISSUE THREAD

**Issue by onionhammer** [react-hook-form/react-hook-form#2714]
**Describe the bug**
If your array has holes in it; i.e. fields[0].name, fields[2].name, the last item renders empty.

**To Reproduce**
Take a form with three items, and then remove the middle item.

**Desired behavior**
React-hook-form should ignore holes in the array so that react field names are not disrupted. Browsers do not like form field name changes for things like <input type="file">, so renaming all the fields so there are no holes would automatically clear out any file selections.

**Comment by onionhammer** [comment]
I see now why there are no open issues on this repo lol

**Comment by bluebill1049** [comment]
> I see now why there are no open issues on this repo lol.

That's some bullshit right there, I maintain the issues here.  dude go check all the issues, I have responded to all of them.

**Comment by onionhammer** [comment]
@bluebill1049 apologies for offending you, but submitting a detailed issue would also take a good amount of effort on my own part, so I was hoping for some form of conversation prior to submitting more detail. Otherwise I could dedicate a good amount of time into detailing out this issue only to have it dismissed out of hand

**Comment by bluebill1049** [comment]
> @bluebill1049 apologies for offending you, but submitting a detailed issue would also take a good amount of effort on my own part, so I was hoping for some form of conversation prior to submitting more detail. Otherwise I could dedicate a good amount of time into detailing out this issue only to have it dismissed out of hand.
> 
> For example it might be a known issue, or even desired behavior that anyone familiar with the development of this library would know out of hand that it's not worth pursuing, or it might be unique, but without a conversation I can't know that

@onionhammer comment like that (above) is completely ungrateful and meaningless. This is not a product **support line** as you could imagine, I spend my own time (night and weekends) to maintain and resolve issues here. what you saying might sound funny to you, but it's not in my end. I don't make this lib for living, I am building and maintaining for the sake to achieve something meaningful in my life and at the same time help many others around the community. I wish you could take a look at my notification board if everyone submits an unclear and incompletely issue like this for me and not following the issue template at all, i will never be able to resolve issues or problems. It's such a shame to see you mention it will take your time to detail out the issue, then my time is not worthy of considering? That doesn't help, especially with shitty messages like oh "that's why there are no issues". I don't make money or living out of open source project (i wish), so I refused to take bullshit like that, if you having an issue I am happy to **help**, but you need to help me at the same, otherwise I am not going to waste my time here!

**Comment by onionhammer** [comment]
@bluebill1049 again, I'm not trying to waste your time, I'm trying to connect with someone to help improve *your* product for *your* benefit, I had already worked around this issue myself before submitting this issue - although the workaround is ugly.

I apologize (again) for making a joke at your expense, I didn't mean to offend you; I'm not looking for an e-battle, so if you are interested in the issue where an array of file inputs is modified clears out the selection I'm happy to discuss that issue and submit a code sample if anyone is willing to look into it.

**Comment by bluebill1049** [comment]
let's move on with this problem, I think my message is delivered. 

Please provide a codesandbox for me to reproduce this issue if you can, I am happy to take a look at it. the issue will be re-open with that as well as appropriate fix (if any).
