### ISSUE TITLE
successive removes on recursive nested field array leaves behind empty fields

### ISSUE THREAD

**Issue by ilovett** [react-hook-form/react-hook-form#2728]
**Describe the bug**

I have a [query builder codesandbox](https://codesandbox.io/s/react-hook-form-query-builder-mmx3r?file=/src/QueryBuilder.tsx) in which you can recursively build a query.  I am having a problem removing multiple conditions after adding them...

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-query-builder-mmx3r?file=/src/QueryBuilder.tsx
2. Open Console
3. Click on "Add Condition" twice
4. Click on any "Remove Condition" twice
5. Note 2nd remove click throws an error and the field sticks around after `remove` from the field array set

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-query-builder-mmx3r?file=/src/QueryBuilder.tsx

**Expected behavior**

Those items are removed with no errors

**Screenshots**

![2020-08-26 10 36 21](https://user-images.githubusercontent.com/1776100/91337349-16a98b80-e788-11ea-9fb0-1b29ab58f5ee.gif)

**Comment by ilovett** [comment]
So I just had the idea to switch the uncontrolled register ref to controlled and the bug is fixed... https://codesandbox.io/s/react-hook-form-query-builder-forked-g48lw

But I would still expect the uncontrolled hidden input to be removed?

**Comment by bluebill1049** [comment]
hey @ilovett thanks for the detailed issue report, at the moment, we don't support conditional field array just yet. 

maybe try to use CSS to toggle the visibility? https://codesandbox.io/s/react-hook-form-query-builder-forked-u8gvm?file=/src/QueryBuilder.tsx

I think that's the root cause of the issue. 

still working in progress with this: https://github.com/react-hook-form/react-hook-form/pull/2691 but i think this will resolve the conditional field array problem, but for now, you will have to use visibility.

**Comment by bluebill1049** [comment]
I think the other problem I can see updates nested field array through parent useFieldArray.

✅
```
append({
  name: ''
})
```

❌
```
append({
  name: ''
  child: [
    { name: ''}
  ]
})
```

update child field array should use child's useFieldArray

**Comment by ilovett** [comment]
Thanks @bluebill1049 I think this is just a dupe of #2691

**Comment by bluebill1049** [comment]
Thanks @ilovett FYI, it will take me sometimes to wrap that PR. 🙏
