### ISSUE TITLE
React Hook formstate (FormStateProxy) isValid value always false

### ISSUE THREAD

**Issue by Mansi1** [react-hook-form/react-hook-form#2740]
Want to use the isValid property of formstate but its always false
```
const {formState: { isValid }, trigger,
    } = useForm({
        mode: 'all',
        reValidateMode: 'all',
        defaultValues: {
            firstName: '',
            lastName: '',
            country: '',
            email: '',
            street: '',
            streetNo: '',
            zipCode: '',
            city: '',
            companyName: '',
       },
    })
```

**Comment by freenetbrasil** [comment]
Same happens here, I've found that since v6.5.0 it's not working correctly anymore. If you downgrade to 6.4.1 it works fine. I've seen on the release page for 6.5.0 changed formState to useState, maybe this is what's going.

Will have to wait for someone to help us

**Comment by Derzone** [comment]
Some more information with a sandbox.
In my case, I got the issue with yupResolver.

**Describe the bug**
Since `react-hook-form@6.5.x`, `formState.isValid` remains `false` when using a yupResolver and `onChange` mode.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to https://codesandbox.io/s/purple-grass-1fhke
2. Fill the input field
3. Observe that `formState.isValid` is still `false`
4. Update `react-hook-form` dependency to a version in range of `6.0.x` to `6.4.x`.
5. Repeat step 2
6. Observe that `formState.isValid` is now `true`

**Expected behavior**
When a custom resolver is set with an `onChange` mode, it should update `formState.isValid` state on input value change.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 84.0.4147.135

**Comment by bluebill1049** [comment]
Thanks, guys and especially @Derzone's detailed report.

**Comment by bluebill1049** [comment]
> Forgot to mention, I'm using and also isDirty is not working

@freenetbrasil can you provide some more detail?

**Comment by ErikAGriffin** [comment]
This was fixed @bluebill1049 ?  I'm still having the issue where formState.isValid remains false.  mode: `onBlur` and reValidateMode: `onChange`.

Version 6.9.6

**Comment by bluebill1049** [comment]
@ErikAGriffin hmmm... can you share a codesandbox with this?

**Comment by ErikAGriffin** [comment]
@bluebill1049  so by continuing to dig I narrowed this down to what seems to be a persistent issue around `mode: onBlur` and required radio inputs.  Making the radio inputs not required solves the issue, or changing `mode` to `onChange`.

I had opened a similar issue before on this topic, never got around to trying to contribute a fix.  For now my work around was the following: 

Ensure only one of the radio inputs is `ref={register({ required: true })}`
On each of the radio inputs add an `onChange` handler with the following function:

```
function onRadioChange(e) {
  trigger(e.target.name);
}
```

This causes the radio inputs to successfully register as having a value.  `mode: 'onBlur'` simply does not work out of the box with required radio inputs

**Comment by bluebill1049** [comment]
Thanks, heaps for the detail and info @ErikAGriffin. What about building those radio into a controlled component and wrapped with Controller.

**Comment by ErikAGriffin** [comment]
> Thanks, heaps for the detail and info @ErikAGriffin. What about building those radio into a controlled component and wrapped with Controller.

I see, that could be another workaround that is more DRY.  I'll look into it the next time we touch the form
