### ISSUE TITLE
Slow perf and value updates skipped with Controller and control using react-color

### ISSUE THREAD

**Issue by SharadKumar** [react-hook-form/react-hook-form#2856]
**Describe the bug**
I am trying to use react-color with Controller and turns out it is updating value very slow and I am not able to have a responsive UI.

**To Reproduce**

1. Setup Controller/Control with `react-color`
2. Click on any color
3. See how slow are updates to `getValues`

**Codesandbox link (Required)**
https://codesandbox.io/s/vigilant-williams-10350?file=/src/App.js

**Expected behavior**
Responsive update for the selected color. Values and console.logs out of sync!

**Comment by bluebill1049** [comment]
I would recommend you to try a version without `Controller`, because it's the same perf with my testing. `Contorller` doesn't do any heavy work, either `getValues` (probably those extra print you had on the result with value)
<img width="1437" alt="Screen Shot 2020-09-09 at 9 00 18 pm" src="https://user-images.githubusercontent.com/10513364/92590389-799a3700-f2df-11ea-8112-2ea674757564.png">

**Comment by SharadKumar** [comment]
Well, with Controller there are no updates. Many updates are skipped or too slow!

https://codesandbox.io/s/vigilant-williams-10350?file=/src/App.js
![image](https://user-images.githubusercontent.com/5488144/92594188-c7b23900-f2e5-11ea-9cf1-848c0298f5f1.png)

you can see that the values on console are all there but they never made it to UI (getValues). In fact, last color selection on console is not on UI, as in screenshot above.

I tried with useState without Controller, and perf was significantly and so was the consistency. No value updates missed. But I am not sure whats the right pattern to `register` such a custom control (with yup validation in use). But thats a separate issue.

**Comment by bluebill1049** [comment]
> you can see that the values on console are all there but they never made it to UI (getValues). In fact, last color selection on console is not on UI, as in screenshot above. (#7b1fa2)

That's a misunderstanding of what's `Controller` and `getValues` in the first place. so I can conclude slow perf has nothing to do with this lib, it's a false assumption. 

Now let me explain the missing piece:

1. `Controller` is isolating the re-render within the `Controller` hence you see the `onChange` return `value`, which otherwise will return at your entire component level with `useState`
2. why getValues is not subscribed or reflect the UI, because it was never meant to subscribe or watch changes: https://react-hook-form.com/api#getValues it simply returns what's in the form.
3. if you want to reflect the change, then you should use `watch` API: https://react-hook-form.com/api#watch or https://react-hook-form.com/api#useWatch

**Comment by SharadKumar** [comment]
Thanks Bill, for clarifying. 
It worked with `watch`... I am incorporating in main project and will confirm and close the issue.

Great stuff with your rapid response. Thank you.
