### ISSUE TITLE
formState is not updated after input unmount

### ISSUE THREAD

**Issue by yashok111** [react-hook-form/react-hook-form#2937]
**Describe the bug**
When you delete input, the formState's isDirty is not changing to true
**To Reproduce**

1. Go to the sandbox
2. Notice isDirty === false
3. Click on the delete button
4. Notice isDirty remains false
5. (Optional) You can click on the submit button to ensure that the input's values are removed from the form

**Codesandbox link (Required)**
- https://codesandbox.io/s/amazing-voice-e6339?file=/src/App.js

**Expected behavior**
formState should change after unregistering input

**Additional context**
Using react-hook-form v6.8.2

**Comment by MatiasCiccone** [comment]
It is working as expected if you change and remove the **last** registered input. If you add a third one it will work with the third one. At least it should be consistent between inputs. It seems that it is triggering extra renders with the last input. Also, if instead of doing `register()` you do `register` it works fine with all of them

**Comment by yashok111** [comment]
According to docs state should change after input unmount. 

<img width="975" alt="Screenshot 2020-09-17 at 17 24 44" src="https://user-images.githubusercontent.com/19926392/93476473-e4b0c280-f90a-11ea-8c7a-c5a54f63dee1.png">

**Comment by bluebill1049** [comment]
<img width="692" alt="Screen Shot 2020-09-18 at 8 48 51 am" src="https://user-images.githubusercontent.com/10513364/93536163-c8a13580-f98b-11ea-8d47-c9a4601a2929.png">

please read the warning the console and the doc.

<img width="962" alt="Screen Shot 2020-09-18 at 8 49 29 am" src="https://user-images.githubusercontent.com/10513364/93536226-deaef600-f98b-11ea-8ea8-ddeca7d4122a.png">

**Comment by ElForastero** [comment]
@bluebill1049 Hi, can you explain if this indeed is expected behavior?

The input was removed from the context, its value was removed as well. But the `formState.isDirty` is still `false`.

I mean, what is considered as a mutation that changes dirty state? Only changes in values, not in the fields set?

**Comment by bluebill1049** [comment]
oh wow, sorry I overlooked the issue, though was `isValid`...

**Comment by bluebill1049** [comment]
ok, I looked closer to this issue.

This example is not using `useFieldArray`, which is almost impossible to track input is dirty or not, because the form state live in the input itself. I would recommend using useFieldArray when you remove/insert/shuffle inputs.

**Comment by yashok111** [comment]
Thank you! I'll stick to useFieldArray solution.

**Comment by bluebill1049** [comment]
I think i figure out something... let me give it a try tmr.
