### ISSUE TITLE
onBlur mode does not work until `triggerValidation` is called

### ISSUE THREAD

**Issue by michal-samluk** [react-hook-form/react-hook-form#295]
I am registering a bunch of fields using: `register({ required: true })`. After filling in all the fields, `formState.isValid` returns false. I am using `mode: 'onBlur'`
I added a button to manually trigger: `triggerValidation()`.  

After it was called once, then blur works perfectly. If I clear one of the fields I am getting `isValid = false`. When I fill fields again it becomes `isValid = true`. 

Let me know if you need some more details. 

**[EDIT]** I am using `TextField` component from `material-ui`
**[EDIT2]**
I was able to reproduce it: 
https://codesandbox.io/embed/serene-pare-vokcf

so if there is at least one select (from Mui) then `onBlur` or `onChange` modes are not working. If you make a selection first and then type in `text` input it still does not work. 
Adding `triggerValidation` in `onChange` callback fixes the issue. Is this the right way to do it?

**Comment by bluebill1049** [comment]
I think i know the reason why:

can you try to use `setValue("select", event.target.value, true);` i need to trigger validation in order for react hook form to register isValid. The reason is that you are using custom `regsiter`. The ref is not binding into the registration. 

test it and let me know if that fix the issue.

**Comment by michal-samluk** [comment]
Thank you, that works fine :)
