### ISSUE TITLE
When using `shouldUnregister: false` and using the `Controller` for defaultValue cached after unmount

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form#2955]
When using `shouldUnregister: false` and using the `Controller` for some custom components, the fields do not reset to use defaultValues. I think this has something to do with the defaultValues object being mutated somewhere.

see the scodesandbox: https://codesandbox.io/s/react-hook-form-get-started-forked-2tdli?file=/src/index.js

something seems to modify the defaultValues object itself (you can see the logged `defaultData`)

A workaround for this is to not use a default values object outside the component (and not use a prop) and construct it in the component's body.

_Originally posted by @jhsu in https://github.com/react-hook-form/react-hook-form/discussions/2940_

**Comment by ambewas** [comment]
Issue should be re-opened -- This is still the case in latest release: 6.9.2.

Defining the defaultValues in  render as the workaround describes works.

**Comment by bluebill1049** [comment]
> Issue should be re-opened -- This is still the case in latest release: 6.9.2.
> 
> Defining the defaultValues in render as the workaround describes works.

- provide a reproducible codesandbox
- steps to reproduce the issue.

**Comment by ambewas** [comment]
Absolutely, sorry about that. 

Here's a fork of your original codepen. The only change is the controller value is now nested in the defaultValues - and this doesn't get reset. With a flat state it works fine. 

Steps:
- edit value in controller field
- toggle the form

expected behavior: controller field value should be reset - but it's not.

https://codesandbox.io/s/react-hook-form-get-started-forked-j4lxc?file=/src/index.js

**Comment by bluebill1049** [comment]
@ambewas the toggle button on the top unmounted the entire `useForm`, which means the whole useForm is destoried

**Comment by ambewas** [comment]
@bluebill1049  yes - indeed the toggle optional input button works as expected, and so does the `Name field` when unmounting the entire useform. 

However, the `Controller Field` (below the name field), does not get reset when unmounting the entire form, which is exactly the bug described. It should be reset to it's default value when unmounting and re-mounting the entire form, and it does not.

The difference between `Name field` and `Controller field` is only the use of the Controller component. Both are in a nested state and `Name field` gets reset just fine - controller field is not reset. 

So steps to reproduce in the codepen provided earlier:

- type something in  `Controller field`, then use the *global* toggle to unmount and re-mount the entire form. 
Expected outcome: The `Controller field` value gets reset to its default value. 
Actual outcome: the `Controller field` value does _not_ get reset to its default value, it actually retains the value from before destroying the form.

- To confirm that the bug is fixed with non-nested field paths, but pertains with nested field paths: type something in  `Name field`, then use the *global* toggle to unmount and re-mount the entire form. Expected outcome: The name field value gets reset to its default value. This actually happens, so it is fine.

**Comment by bluebill1049** [comment]
Thanks for the detailed explanation. I think you are misunderstanding what's `shouldUnregister: false` and `shouldUnregister: true`

`shouldUnregister: false` 
input unmount state will be renamed similar to Controlled form

`shouldUnregister: true` 
input unmount state gets removed (remount will restore defaultValue) and similar to Native input.

**Comment by ambewas** [comment]
Then why does the Name field actually get reset, and the controller field does not? It isn't consistent behavior. The `defaultValues` object should never be mutated, yet it does?

**Comment by ambewas** [comment]
I'm not sure that you understand my issue here... 

expected behavior: when using `shouldUnregister: false`, and I unmount the entire form (e.g. navigating to a different route), if I then go _back_ to the form, I expect that the form contains defaultValues again. But this is not happening. The form still contains all my previous values. 

This is _not_ an issue when using a flat state -- so that leads me to believe it is a bug with a _nested state_ such as:` {address: {streetName}}`.
