### ISSUE TITLE
Make types work with custom event types for handleSubmit

### ISSUE THREAD

**Issue by allforabit** [react-hook-form/react-hook-form#3056]
**Is your feature request related to a problem? Please describe.**
I'm using the library with react spectrum and while in general it works really well and almost seamlessly there is one small thing that would be nice to have and that's the ability to directly using `handleSubmit` with the button `onPress` method. Please note there's a very simple workaround but it would make it slightly nicer and maybe might benefit other libs.

**Describe the solution you'd like**
I would like `handleSubmit` to allow for more event types. For react spectrum it's a custom press event and I'm sure it's different in other libraries too. Would it be possible to either make the type of the event to `any` or make it an optional generic? E.g. `useForm<FormValues, SubmitEvtType>`.

**Describe alternatives you've considered**
The alternative is to do something like this:
```
<Button onPress={() => handleSubmit(onSubmit)()} />
```
Not the end of the world but it's quite noisy in comparison to the normal syntax.

**Comment by risardi123** [comment]
Here this one, if i am not wrong
https://codesandbox.io/s/competent-engelbart-ycvt1?file=/src/App.js

I use ReactNative method that have mention in documentation. Since react native still from react
https://react-hook-form.com/ 

![image](https://user-images.githubusercontent.com/29408156/94844503-875b5c00-0448-11eb-8402-e792578e6c94.png)

**Comment by bluebill1049** [comment]
leave on the board and see if our users have a similar request.
