### ISSUE TITLE
Reordering field array causes input to modify value from previous position row

### ISSUE THREAD

**Issue by michalkvasnicak** [react-hook-form/react-hook-form#3132]
**Describe the bug**
When `useFieldArray` is used with `react-sortable-hoc` and rows are reordered, moved row also changes the value of the following row.  Weirdly `useWatch` works correctly and uncontrolled components work correctly too.

**To Reproduce**

1. Add 4 rows using `Add item` button
2. Fill values to all rows
3. Move last row to 2th position
4. Try to change it's values
5. It will also change the values of the row below it (but useWatch is triggered correctly only on the changed row)

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-v6-usewatch-forked-v86ly?file=/src/App.js

**Expected behavior**
It should work exatcly the same as if `move up/move down` button has been clicked, only the values of moved row should be manipulated.

**Desktop (please complete the following information):**

- OS: MacOS 10.15.6 
- Browser: Safari  4.0 (15610.1.28.1.9, 15610)
- Version: 6.9.2, but same for 6.5.0, etc

**Comment by bluebill1049** [comment]
Could you please reproduce the issue at this Codesandbox without the dependency of other packages?

https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Comment by michalkvasnicak** [comment]
I wasn't able to reproduce this using the native drag/drop api. Seems that `react-sortable-hoc` somehow clones elements or I don't know exactly what is happening.

Possible fixes I tried are to assign a `key` to `Controller` that depends on `itemIndex` or to use `window.setTimeout` in `onSortEnd` to call `move`.

Code sandbox is updated for both implementations. Feel free to close this one as it seems to not be a problem with `react-hook-form`.

**Comment by bluebill1049** [comment]
I would try the `Controller` otherwise this lib could be not compatible with hook form. 👍

**Comment by Chaoste** [comment]
I'm a bit late to the party but this bug made me struggle for a whole day. The workarounds I tried so far:
- Reset with `setValue` rerenders everything but had some drawbacks like replaying my collapse transitions
- `unregister` and `register` field array again with the dirty values didn't change anything
- I investigated whether it's caused by the cloned DOM node but appears to be not the case. I dropped all the sortable HOCs and still saw the array just by calling `move(0, 1)`.
- Tried hard overwriting `checked` on the radio buttons. That fixed it visually but made them unusable.
The final workaround for me was

**Comment by bluebill1049** [comment]
@Chaoste can you reproduce it in a codesasndbox (not the upload whole project)?

**Comment by Chaoste** [comment]
Sorry, I tried to reproduce it without `react-sortable-hoc` in a codesandbox but failed. I just wanted to share my experiences so far since I believe that others might run into the same issue. But I can't explain exactly where this originates from. Maybe, I will spend another few hours soon and reproduce it in a sandbox.
