### ISSUE TITLE
Field array not submitting

### ISSUE THREAD

**Issue by matheusgrieger** [react-hook-form/react-hook-form#3139]
**Describe the bug**
The hook `useFieldArray` is not being submitted even though the `fields` property has values (visible with `.map`).

**To Reproduce**
1. Create component with `useForm` and `useFieldArray` and set them up together
2. Separate list of fields in a different component
3. Submitting doesn't work anymore, but fields list is working just fine

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-bug-g3dqj

**Expected behavior**
The form should submit with field array in along with the values

**Screenshots**
![image](https://user-images.githubusercontent.com/6992464/95642790-256ea800-0a81-11eb-9052-111050dc2f7e.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser: Chrome
- Version: 86.0.4240.75

**Additional context**
This is a very advanced use case with specific business rules, but either way, it isn't working and is set up correctly (as far as I could see at least):

- There must be a separate form to add and edit fields
- Fields should only be added/replaced (edited) when user clicks on Save
- Second form should clear (reset) when clicking any of the buttons

**Comment by bluebill1049** [comment]
This is not a bug. there are no inputs on the script for your field array. Imagine if you building this form natively without react as an HTML native form.

I would recommend you read the doc because if you would like to react hook form, not auto unregister your input, use `shouldUnregister: false`.

https://react-hook-form.com/api#useForm

<img width="940" alt="Screen Shot 2020-10-10 at 1 06 18 pm" src="https://user-images.githubusercontent.com/10513364/95643185-64404480-0af9-11eb-8355-a8919d2ce023.png">
