### ISSUE TITLE
Helper methods for errors object

### ISSUE THREAD

**Issue by sinnlosername** [react-hook-form/react-hook-form#318]
**Is your feature request related to a problem? Please describe.**
Many component libraries have a property on their fields which decide whether is is invalid or not. For example, in the case of material ui this is the "error" property. It's a boolean, so you always need a != null there, as errors.fieldName is an object, not a boolean.

Also when writing the error message somewhere you'll always have to check if the object at errors.fieldName exists before you access the message at errors.fieldName.message, or else you'll get an exception if there's no error. 

This looks the following in material ui:

`error={errors.fieldName != null} helperText={errors.fieldName && errors.fieldName.message}`

**Describe the solution you'd like**
I think this could be solved by adding two simple helpers.
error.message('fieldName') -> Returns either the error message or undefined, if there's no error
error.has('fieldName') -> Returns true if there's an error, or else false

Then you could go like the following:

`error={errors..has('fieldName')} helperText={errors.message('fieldName')}`

I think that's more clean and simple.

**Comment by bluebill1049** [comment]
> so you always need a != null there, as errors.fieldName is an object, not a boolean

you don't have to do null check? why not just `errors.test`

**Comment by bluebill1049** [comment]
Thanks for the suggestion. ❤️  I would like to add such a helper but at the same time, it increases the bundle size of this lib, I personally care a lot about the size of the package. I believe this also can be achieved easily with lodash get or even write a utility function at your own project. let me know what do you think?

**Comment by bopfer** [comment]
I am using Material UI + TypeScript + react-hook-form and I do this:

`error={!!errors.fieldName} helperText={<FieldError error={errors.fieldName} />}`

The `!!` makes it a boolean, which is required in MUI's types.  Then the component for `helperText` gives me one place to handle the rendering for all form fields.  In there I can check to see if there is a message to show.  If there is no error message to show, then `FieldError` just returns an empty fragment: `<></>`.

**Comment by bluebill1049** [comment]
awsome! thanks @bopfer

**Comment by sinnlosername** [comment]
I think if people use your library in bigger projects then they'll actually end up having a lower total file size with a helper, because the overhead of the suggested way (`errors.fieldName && errors.fieldName.message`) will probably be larger than such a simple helper.

However, it depends on where you put the line between usability and file size.

@bopfer Could you share the source of your FieldError Component? I don't really get it how you put a component in a string property (or is it even for strings only)

**Comment by bopfer** [comment]
Here's my `FieldError` component.

The main thing it does for me right now is convert validation errors, which are camelCase, into user friendly errors.  Long story but this is due to how i18n works in my app.  The general idea is that it does whatever processing and styling is needed for the error before displaying it.

```javascript
import React from 'react';
import { FieldError as ReactHookFormFieldError } from 'react-hook-form/dist/types';

// This is my own form context (separate from react-hook-form's context).
import { useFormContext } from '../Form';

type Props = {
  error?: ReactHookFormFieldError;
};

const FieldError = ({ error }: Props) => {
  const formContext = useFormContext();

  if (!error || !error.message) {
    return <></>;
  }

  /* Get the user friendly error from the errorMap */
  const errorMessage = formContext.errorMap[error.message] || error.message;

  return <>{errorMessage}</>;
};

export { FieldError };
```

**Comment by bluebill1049** [comment]
> I think if people use your library in bigger projects then they'll actually end up having a lower total file size with a helper, because the overhead of the suggested way (`errors.fieldName && errors.fieldName.message`) will probably be larger than such a simple helper.
> 
> However, it depends on where you put the line between usability and file size.

Did you try with lodash? you can do this in oneline with lodash `get(errors, 'name', false)`

**Comment by sinnlosername** [comment]
> Did you try with lodash? you can do this in one line with lodash `get(errors, 'name', false)`
> 
> I think helper method probably shouldn't be part of this library, it's never easy to fulfill everyone's need in terms of helper (and people will ask for more helpers), I believe it's much easier to write one yourself in your own project and fulfill your own need. we use this library in a large project as well and having similar utility function as above while keep react hook form as primitive.

I don't wanna pack lodash into my project, it contains like a billion functions I don't need.

Hm k.

**Comment by stramel** [comment]
> I don't wanna pack lodash into my project, it contains like a billion functions I don't need.

If you are doing proper tree-shaking you should be able to drop out any functions you aren't using.

**Comment by bluebill1049** [comment]
@sinnlosername FYI https://stackoverflow.com/questions/35250500/correct-way-to-import-lodash/35251059#35251059

**Comment by bluebill1049** [comment]
I am going to close this issue for now, feel free to reopen if my above answer doesn't help your issue or having more questions.

**Comment by hbarcelos** [comment]
I'd like to +1 this.

> I would like to add such a helper but at the same time, it increases the bundle size of this lib [...]

I don't think 2 helper functions with 1 or 2 lines each add significant overhead in terms of bundle size.

I just discovered this library and so far I think it is awesome, however, I do not think it is reasonable to ask users to include something like `lodash` for very simple functionality that is basically the core of the lib.

I've implemented helpers like this:

```js
const hasError = inputName => Boolean(errors && errors[inputName]);
const getError = inputName => (hasError(inputName) ? errors[inputName].message : '');
```

Problem is that such functions are not pure, since they close over the `errors` object which is returned from `useForm`. So I end up with one of the following scenarios:

## 1. Declare such helper functions inside every component I have
**Problem:** it is very repetitive and boring having to copy and paste it for every form I have. Some applications might have dozens of different forms.

## 2. Make the functions pure 
And use currying to ease the use:
```js
const hasError = errors => inputName => Boolean(errors && errors[inputName]);
const getError = errors => inputName => (hasError(inputName) ? errors[inputName].message : '');
```
Then in my component I would have:
```js
const { register, handleSubmit, errors } = useForm();
const formHasError = hasError(errors);
const formGetError = getError(errors);
```
**Problem:** This would also be very repetitive if spread throughout many forms in a given application.

## 3. Using `lodash`
I would have to do something like:
```js
<TextField
    error={_.has(errors, 'email')}
    helperText={_.get(errors, 'email.message', '')}
```
**Problem **: if I don't use `lodash` anywhere else in the project, it is yet another dependency that I'll have to add. I'm not even talking about the bundle size impact of adding `lodash`, because we have tree-shaking. I'm simply advocating against adding another dependency itself.

---

## ⚠️ Main problem ⚠️

With any of the above approaches, I would be creating a coupling between my app and this lib's internals. I'm assuming that errors is a plain object with a `message` property inside an `email` one.

This might hold true for now, but maybe in the future you can come up with another internal structure for this library, which would break my application. It would be very painful to change all my forms to comply to the new structure.

Ideally, you should probably not export the raw `errors` object at all. What I think would be useful for most users would be something like the following interfaces:

```ts
type ValidationPredicate = (value: string | boolean | number) => boolean;

type ValidationType = |
  | 'required'
  | 'maxLength'
  | 'minLength'
  | 'max'
  | 'min'
  | 'pattern'
  | ValidationPredicate
  | Record<string, ValidationPredicate>;

interface ValidationError {
  type: ValidationType;
  types: Record<string, string | boolean>;
  message: string;
  ref: React.RefObject;
}

interface Validation {
  hasErrors(): boolean;
  hasError(name: string): boolean;
  getErrorMessage(name: string): string;
}
```
If you really need to expose the `errors` object (maybe to not break retro-compatibility), then there could have something like:

```ts
type ErrorsObject = Record<string, ValidationError> & Validation;
const errors: ErrorsObject = { /* ... */ };
```
Usage would be like:
```js
const { validation, register, handeSubmit } = useForm();
// ...
<TextField
    error={validation.hasError('email')}
    helperText={validation.getErrorMessage('email')}
```

Since the code that returns the `Validation` object closes over the raw `errors` object, you could easily export the detached versions of those methods. Then usage could be more like:

```js
const { hasError, getErrorMessage, register, handeSubmit } = useForm();
// ...
<TextField
    error={hasError('email')}
    helperText={getErrorMessage('email')}
```

**Comment by sinnlosername** [comment]
I agree with this

**Comment by hbarcelos** [comment]
@bluebill1049 I can work on a PR for this during the weekend.

**Comment by bluebill1049** [comment]
hey, @hbarcelos sorry for the late reply (too many things in my hands at the moment 🤘)  thanks for your detailed feedback. I didn't force everyone to install `Lodash` (definitely not my intention only if your project already includes it) :) in fact, I wrote a small section for Error Message:

> If your project is using lodash, then you can leverage what lodash get function. Eg:

https://react-hook-form.com/advanced-usage#ErrorMessage

recently there is a new ES feature release which probably would help us better to deal with error message: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining i will include that in the website soon.

However, you have some valid and good point there, and i don't mind to have a generic component to handle those errors. similar for what i did for controlled inputs:

https://github.com/react-hook-form/react-hook-form-input

if you would like to create such a component (embed some of the logic inside without growing the core lib) and i am more than happy to include on the website and let users know to use it if it makes their life easier.

again thanks very much for your constructive feedback 👍

**Comment by hbarcelos** [comment]
I don't think adding a HOC would be the right approach here. HOCs are exactly one of the things that hooks made deprecated.

In case such helper methods cannot be added to this library, I'll probably define a custom hook like this and use it:

```js
import { useCallback } from 'react';

export default function useFormEnhanced({
  mode,
  reValidateMode,
  defaultValues,
  validationSchema,
  validationSchemaOption,
  validateCriteriaMode,
  submitFocusError,
  nativeValidation
}) {
  const {
    register,
    unregister,
    errors,
    watch,
    handleSubmit,
    reset,
    setError,
    clearError,
    setValue,
    getValues,
    triggerValidation,
    formState
  } = useForm({
    mode,
    reValidateMode,
    defaultValues,
    validationSchema,
    validationSchemaOption,
    validateCriteriaMode,
    submitFocusError,
    nativeValidation
  });

  const hasError = useCallback(inputName => Boolean(errors && errors[inputName]), [errors]);
  const getError = useCallback(inputName => hasError(inputName) ? errors[inputName].message : "", [errors]);

  return {
    register,
    unregister,
    watch,
    handleSubmit,
    reset,
    setValue,
    getValues,
    triggerValidation,
    formState,
    setError,
    clearError,
    hasError,
    getError
  };
}
```

**Comment by bluebill1049** [comment]
> I don't think adding a HOC would be the right approach here. HOCs are exactly one of the things that hooks made deprecated.

What do you mean HOC? I thought the idea was to just to create a component. (similar to https://github.com/react-hook-form/react-hook-form-input)

**Comment by hbarcelos** [comment]
This is a HOC ([Higher Order Component](https://reactjs.org/docs/higher-order-components.html))!!!

A Higher Order Component is a Component that receives other components as a parameter and/or returns a new one.

That's exactly what you do here:
```js
    return React.cloneElement(as, {
      ...rest,
      onChange: handleChange,
      ...(isOnBlur ? { onBlur: handleBlur } : {}),
      value: value || inputValue,
      ...(isCheckbox ? { checked: inputValue } : {}),
    });
```

In that case, it actually kind of makes sense using a hooked HOC, it's actually pretty neat (:

However, I can't see how that could apply to the use cases we are discussing here. Would you have an example?

**Comment by bluebill1049** [comment]
The error message component doesn't have to be a HOC.

That's in my head `<RHFError errors={errors} name={name} />` i will create the repo now.

**Comment by hbarcelos** [comment]
```jsx
<RHFError errors={errors} name={name} as={<span />} /> 
```
The code above **IS** a HOC because it receives a component as a prop and returns a new one.

**Comment by bluebill1049** [comment]
`<RHFError errors={errors} name={name} />` as it can return just string too.

**Comment by hbarcelos** [comment]
I am so sorry, I didn't meant to be petty about names, but in this case the name helps us to understand what is going on, regarding patterns that emerged from React hooks and the ones that were kind of discontinued.

The object returned from `useForm()` already has a `setError` and a `clearError` message. It would make sense that `getError` (or `getErrorMessage` for clarity) and `hasError` to be present here as well.

I think having another component as a dependency just to handle these cases is too much. Furthermore, it is unintuitive. The main issue I see here is the asymmetry of the APIs.

That is very different from `[react-hook-form-input](https://github.com/react-hook-form/)`. In that case, it actually makes sense because you are fundamentally changing something at the core of the library: the choice of uncontrolled components, to allow users to handle controlled components more easily, without having to deal with `useEffect` and other stuff.

`hasError` and `setError` don't change anything at all, in fact, they are just a façade to what you already have. It provides users less coupling and could make your life easier as a maintainer, since you would not be exposing the internals of the lib.

Again, I am sorry for making a big deal about this. As I said, I have just discovered this library and I its DX is so much better than the others available. That's the one little issue bugging me :sweat_smile:.

Anyway, I don't mean to impose anything. I would be happy with the custom hook as well. Probably I will never make it a package though.

**Comment by bluebill1049** [comment]
that's all good @hbarcelos as long as we are making improvements on this package. I am working on this little component at the moment: https://github.com/react-hook-form/react-hook-form-error feel free to contribute and leave feedback there.

**Comment by ignapas** [comment]
Hello! In my case, I am using your package (which I find awesome) to model generate complex form with nested inputs (objects and arrays).
While generating the form, I construct the jsonPath of every node as I go deeper into the model, and use it as the name. It was very convenient to access the validation errors just by their field's name or jsonPath.
Now the ``ErrorMessage`` component successfully solves the issue of showing the message, but I need to apply some other classes to show some red borders.
It is easy to solve writing a ``getByPath`` function or using lodash's ``get`` but before it was just perfect.
What are the advantages of this new nested objects system?
Thank you for your awesome work.

**Comment by bluebill1049** [comment]
@ignapas i love flat error object... but he community wants Type support... sad :( gotta follow the community's needs.

**Comment by ignapas** [comment]
> @ignapas i love flat error object... but he community wants Type support... sad :( gotta follow the community's needs.

yes. I stay v3 because of that one
