### ISSUE TITLE
Watch not re-rendering when input value property changes

### ISSUE THREAD

**Issue by cwagner22** [react-hook-form/react-hook-form#3338]
**Describe the bug**
Assigning `value` directly to an input is not triggering `watch` re-render when `value` changes.

**To Reproduce**
https://codesandbox.io/s/react-hook-form-watch-v6-forked-ydwdn?file=/src/index.js

Enter a value in the first field. The second field is correctly updated but in the console, the value returned by `watch("name2")` is outdated. (no re-render were triggered)

**Comment by mrlubos** [comment]
Hi @cwagner22, your CodeSandbox link seems to be a broken build (referencing undefined value `test`)

**Comment by cwagner22** [comment]
@mrlubos You're right, sorry about that... Could you try again? 🙏

**Comment by mrlubos** [comment]
@cwagner22 Works now! May I ask what's the use case for this? I'm not sure if it's really a bug as you'd be getting double render on every key stroke

**Comment by cwagner22** [comment]
Something like that, when the value depends on other variables:
```
          <input
            name="fullName"
            ref={register}
            value={firstName + ' ' + lastName}
            readOnly
          />
```

You're right that maybe a double render in not wanted. In my case I needed it because I made it hidden (`type="hidden"`), it's a big form and I used form context to watch that value from deeply nested children components. This is not the best use case though, since I probably should be using React context I think...

**Comment by bluebill1049** [comment]
i think the easiest solution is just 

`onChange={(e) => setValue('name', e.target.value')}` 

you don't even need `watch` :)

**Comment by david-morris** [comment]
This seems to be related to the following documentation snippet of the useForm - watch docs:

watch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.

I would really like to see more specific discussion of how we are _supposed_ to subscribe a component to updates in a field.  It's something I find myself doing often, and I'm now seeing why I find that frustrating.  I would really appreciate documentation that clearly states how we are supposed to subscribe to updates on the value of another field linked in `watch` docs, since I naively assumed multiple times that `watch` or `useWatch` would watch the specified value for updates.

@bluebill1049, what is the intended solution to the general case problem of wanting to trap into react updates from form updates?  Obviously it's better if form updates don't trigger react updates, but sometimes, in web forms as in life, the choices you make affect what choices you can make later on.
