### ISSUE TITLE
handleSubmit returns incorrect data when using react-select + yupResolver

### ISSUE THREAD

**Issue by rinatsakaev** [react-hook-form/react-hook-form#3383]
**Describe the bug**
When I use validation with yupResolver for Select component (react-select), handleSubmit returns [Object object] as a value of Select.

**To Reproduce**
See https://codesandbox.io/s/react-hook-form-v6-validationschema-forked-z832l

**Expected behavior**
handleSubmit should return actual value of Select.

**Comment by bluebill1049** [comment]
react select return object by default, so you should use `render` instead of `as` 
https://codesandbox.io/s/react-hook-form-v6-validationschema-forked-jopm9?file=/src/index.js;

if you expected to retrieve react select's correct data format `label` and `value` as an object, then u can fix your schema as well.
