### ISSUE TITLE
[Feature Request] Field Focus

### ISSUE THREAD

**Issue by BrunoQuaresma** [react-hook-form/react-hook-form#349]
A simple way to focus a field.

```js
const { focus } = useForm({ ... })

useEffect(() => { focus('name') }, [])
```

**Comment by bluebill1049** [comment]
hey @BrunoQuaresma that's a pretty good idea 👍 i will look into it.

**Comment by BrunoQuaresma** [comment]
@bluebill1049 when I open a modal and I want to focus an input. Since the modal is just replacing `.open` and `.close` class names, the default HTML API does not work.

**Comment by bluebill1049** [comment]
I think you can use HTML API, with focus

https://react-hook-form.com/faq/ How to share ref usage?

you just need to use `useRef()` with React  and use `.focus()`

**Comment by BrunoQuaresma** [comment]
Yes, I can. I just suggested it to have a syntactic sugar.

**Comment by bluebill1049** [comment]
oh cool! thanks for understanding. I guess the main reason is that I want to keep the API small and simple. every time when I am getting request or thinking about add API, I will battle again simplicity and utility. I think for this instance I will go with keep API simple, since doing useRef is not too tricky with React. 🙏

**Comment by BrunoQuaresma** [comment]
Sure! Thanks.
