### ISSUE TITLE
Can't get register to work on ref for Material UI Select

### ISSUE THREAD

**Issue by zeckdude** [react-hook-form/react-hook-form#380]
**Describe the bug**
I am trying to use the `register()` method on the `ref` prop on the `Select` component for Material UI. According to their docs, the `ref` prop gets passed to the root element, but when I change the select option, it doesn't change visually and when I then hit the submit button, it consoles out all the form values which doesn't include the select value.

**To Reproduce**
https://stackblitz.com/edit/react-hook-form-mui-select

**Expected behavior**
The Material UI Select should show the chosen value

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra
 - Browser Chrome
 - Version 76

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by bluebill1049** [comment]
hey @zeckdude thanks for the detailed issue report. (really helpful) so the problem is material UI not expose the input ref, rather than a `div`. I did a quick console.log and this is what it returns 

<img width="538" alt="Screen Shot 2019-10-17 at 12 04 03 pm" src="https://user-images.githubusercontent.com/10513364/66969679-3be45c80-f0d6-11e9-918a-73ab12a58953.png">

It's pretty sad material UI is not easily working with react-hook-form, because of material UI still in favor of controlled component. (hopefully, one-day things will change a bit for uncontrolled components)

**Solution:** 

you have had to use custom register during `useEffect`, 
https://react-hook-form.com/api#register

and update value via `setValue`
https://react-hook-form.com/api#setValue

**Comment by zeckdude** [comment]
Hi @bluebill1049! First of all, I love the work you've done with `react-hook-form`. It's pretty easy to follow and full of features. All of the code samples in code and code sandbox links are super helpful! And your documentation is absolutely stunning. That is some sexy documentation! I want to frame it and hang it on my wall lol!

I don't have much of an opinion on controlled vs uncontrolled form elements, but my impression of React has always been that the values of an element should "react" to the values in state, which is what a controlled element is all about. Uncontrolled elements seem to contradict that convention, so I assume that's why controlled elements have mostly been used.

Question for you, how did you console out that ref element? I'm confused about that.

**Comment by bluebill1049** [comment]
hey @zeckdude thank you very much for your kind words! ❤️ 

yes, I think controlled component have been giving a lot of love (mainstream), but we miss the benefits of uncontrolled inputs, skip re-rendering, faster mount and just cheaper to run things uncontrolled. off course, there are benefits using controlled too :) I want to give developers the best performance and experience which they deserve ❤️, hence build this package and spend my time to document down things. at the end of the day, we all want to go home on time and make things as easy as possible 👍 

this is what i did

`ref={d => console.log(d)}`

**Comment by waynebloss** [comment]
All the elements of controlled mode are there with `getValues()` and `setValue()`. `errors` and validation from `useForm` work as well, as should `watch`.

See
- https://codesandbox.io/s/vigorous-jones-pyee5
- via https://github.com/react-hook-form/react-hook-form/issues/373#issuecomment-542311522

I am thinking that without `ref`, the only thing you might lose will be `formState.touched`. I generally don't care if something was `touched` as much as I care if it changed from the original though. Perhaps `touched` already toggles upon `setValue` in this case? If not, it would be an easy fix and I think it's the right thing to do anyway, since `setValue` is already exposed and supported as a way to change a value without using a reference.

Also, if you want to load your inital values from `props`, I think you can use `useForm({ defaultValues })` _but I'm not sure what happens if I re-render with a new set of defaultValues, e.g. if my `props.defaultValues` prop changes after I load some data into the prop via a redux action_. If you want to load your values from an async call right in your component, you can see my example there where I use `reset` to update the form after my async call.

I'm going to test it out because I certainly don't want to build a layer around `material-ui`. It would be easier to just spread 4 props onto every input, `value`, `onChange`, `error` and `helperText`.

So, with that I think you can probably shim a controlled mode over `react-hook-form` very easily. Perhaps I'll work on a material-ui demo. Date input is shown the issue I referenced above and there are only 9 other input types.

**Comment by bluebill1049** [comment]
> So, with that I think you can probably shim a controlled mode over react-hook-form very easily. Perhaps I'll work on a material-ui demo. Date input is shown the issue I referenced above and there are only 9 other input types.

@waynebloss that would be really nice. I am more than happy to include them on the website to help others.

`setValue` do update `dirty` and `touched`

**Comment by john182** [comment]
Not working para value in object exemple :

`const orderSchema = yup.object().shape({
   name:  yup.string().required(),
    end: yup.object({
      name: yup.string().required(),    
    }),
  });`

not change name of end

**Comment by bluebill1049** [comment]
what? @john182

**Comment by john182** [comment]
That's what I mentioned in the other issue

**Comment by waynebloss** [comment]
@john182 As I remember - material ui select uses `e.target` or `e.currentTarget` where the rest of the controls use the opposite... perhaps that is driving your issue?

**Comment by hulivets** [comment]
![Screenshot from 2020-05-30 20-30-21](https://user-images.githubusercontent.com/48622868/83335607-b30de000-a2b6-11ea-8821-284287cd64e6.png)

**Comment by daveOnactive** [comment]
Hi @zeckdude I came across this same issue, and this is how i solved mine 
`  const { register, handleSubmit, errors, } = useForm({
    resolver: yupResolver(schema)
  });
<FormControl variant="outlined" style={{ width: '100%' }}>
                <InputLabel error={errors.nationality }id="demo-simple-select-outlined-label">Nationality</InputLabel>
                <Select
                  labelId="demo-simple-select-outlined-label"
                  id='nationality'
                  label="Nationality"
                  variant="outlined"
                  style={{ width: '100%' }}
                  error={errors.nationality}
                  name='nationality'
                  onChange={e => register({ name: 'nationality', value: e.target.value})}
                >
                  {countryList.map(option => (
                  <MenuItem key={option.number} value={option.name}>
                    {option.name}
                  </MenuItem>
                ))}
                </Select>
                <FormHelperText error={errors.nationality}>{errors.nationality?.message}</FormHelperText>`
i invoked the register method and passed it an object with name(key) value(value) in the onChange props

**Comment by sthakkar0687** [comment]
> onChange={e => register({ name: 'nationality', value: e.target.value})}

This works only on first time selection.
Afterwards dropdown value is always the same no matter whatever option is selected.

**Comment by sthakkar0687** [comment]
The only option which worked for me is with the Controller component : 
Reference : https://dev.to/raduan/4-ways-to-use-material-ui-select-with-react-hook-form-41b2

**Comment by waynebloss** [comment]
Sorry I didn't work on this everybody. I actually switched to using a different kit for forms.
