### ISSUE TITLE
Change of dirtyFields logic after 6.14.0

### ISSUE THREAD

**Issue by OlehRb** [react-hook-form/react-hook-form#3873]
Hi @bluebill1049 , first of all, thanks for this amazing library, it's been a real pleasure working with it so far.
However recently, we've faced with a minor issue, which affects logic of our apps

**Description**
As of version 6.14.0 the logic behind `dirtyFields` and `isDirty` from `useForm / useFormContext` seems to be changed quite drastically.

Before 6.14.0 it worked in a following way:

https://user-images.githubusercontent.com/24420540/104209027-de0a0600-5439-11eb-984b-8f58ca56f14f.mov

But, from 6.14.0 it started working in a completely different way:

https://user-images.githubusercontent.com/24420540/104209207-14e01c00-543a-11eb-9000-d4f900abeff3.mov

So, previously we relayed on this behaviour in order to define if user changed anything in the form in order to prevent accidental redirects

Was it an intentional change of behaviour? 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go [to](https://codesandbox.io/s/react-hook-forms-6140-dirty-computation-inconsistency-z0gi7)
2. Make sure you are using version 6.14.0 or 6.14.1 (the most recent once, at the time of bug report)
3. Enter any value in one of the fields
4. Check that output for "DirtyField" shows `true` for the altered field
5. Clean the touched field
6. Check that output for "DirtyField" still shows previous state

**Expected behaviour**
On step 6 "DirtyField" the altered field should be removed from the list of `dirtyField`

**Desktop (please complete the following information):**

- OS: MacOS Big Sur 11.1
- Browser: Chrome
- Version: 87

If you need any additional info about the reported issue, please, let me know

**Comment by bluebill1049** [comment]
you will need to supply `defaultValues` to make it work correctly with dirty fields. This was fixed by quite a few bugs which is a result of us predicting the default value to be an empty string.

one of the bug below:
🐞 fix #3261 dirtyField with object or array value compare (#3262)

so for `isDirty` and `dirtyFields` should always supply a `defaultValue` for us to do the comparison to avoid issues.

looks like in the doc only mention the need for `isDirty`, I will include that info in the `dirtyFields` as well. I know this is not convenient, but as the lib grows we need to seek a more stable and safe approach.

**Comment by OlehRb** [comment]
@bluebill1049 , thanks for a super fast response
Yep, it looks like, providing of `defaultValues` makes `isDirty` and `dirtyFields` work as expected

I am gonna close this issue

**Comment by bluebill1049** [comment]
No worries, buddy.
