### ISSUE TITLE
shouldUnregister: false breaks class instances

### ISSUE THREAD

**Issue by nucleartux** [react-hook-form/react-hook-form#3877]
**Describe the bug**
I use datepicker controls with [luxon library](https://moment.github.io/luxon/) and everything was fine until I changed `shouldUnregister` to `false`. Now I get wrong object instead of luxon date instance.

**To Reproduce**

1. set `shouldUnregister` to `false`
2. set defaultValues with some fields where one of them is class instance
3. console.log `value` of such field in `render` of `Controller` for example
4. instead of class instance now we have object (we are losing class context here)

**Expected behavior**
We should have same values for shouldUnregister equals false or true

 "react-hook-form": "6.14.1"

**Comment by bluebill1049** [comment]
can you provide a codesandbox?

**Comment by nucleartux** [comment]
Sure https://codesandbox.io/s/bitter-moon-viy4z?file=/src/App.js

**Comment by bluebill1049** [comment]
Thanks will look into this, FYI v7 we are removing `shouldUnregister` at `useForm`.

**Comment by bluebill1049** [comment]
we are doing a deep clone of `defaultValues` with `shouldUnregister: false`, and that `object` from `Luxon` is not a `Date` object and hence we can't correctly determine its a Date object and clone it correctly. I would say it's a limitation with `shouldUnregister: false`, instead of making a hack to the library by specific what object to clone or not, I think we will solve this issue at V7, if you still want to keep the input value during unmount, I would recommend using toggle CSS as a solution.

**Comment by bluebill1049** [comment]
Going to close this issue, we will resolve this problem in v7. registered input will no longer be automatically unregistered. more detail here: https://github.com/react-hook-form/react-hook-form/discussions/3714
