### ISSUE TITLE
Chromium browser can't offer save password

### ISSUE THREAD

**Issue by chungweileong94** [react-hook-form/react-hook-form#395]
**Describe the bug**
Having filed like `email` & `password` cannot trigger the chrome offer save password prompt. The problem will only happen if I use the `handleSubmit` from the hook

**To Reproduce**
1. Create a form standard login form which includes "email" and "password" inputs
2. Fill-in the email and password then press the submit button

**Codesandbox link**
[Sample](https://codesandbox.io/s/react-hook-form-basic-8vqok?fontsize=14)

**Expected behavior**
Offer save password prompt should popup after submit

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge (Chromium)
 - Version 79.0.301.2

**Comment by bluebill1049** [comment]
Are you sure this a bug from react hook form?

On 21 Oct 2019, at 6:06 pm, Chung Wei Leong <notifications@github.com<mailto:notifications@github.com>> wrote:


Describe the bug
Having filed like email & password cannot trigger the chrome offer save password prompt. The problem will only happen if I use the handleSubmit from the hook

To Reproduce

  1.  Create a form standard login form which includes "email" and "password" inputs
  2.  Fill-in the email and password then press the submit button

Codesandbox link
Sample<https://codesandbox.io/s/react-hook-form-basic-8vqok?fontsize=14>

Expected behavior
Offer save password prompt should popup after submit

Screenshots
None

Desktop (please complete the following information):

  *   OS: Windows 10
  *   Browser Microsoft Edge (Chromium)
  *   Version 79.0.301.2

**Comment by chungweileong94** [comment]
@bluebill1049 Hi, after some investigation, I pretty sure the bug is from `react-hook-form`. As it was working in the previous version (however I'm not really sure which one was it).

**Comment by bluebill1049** [comment]
Ok thanks @chungweileong94 I will try to reproduce and investigate.

**Comment by bluebill1049** [comment]
Can u do me a favor and try one of the old version? See if it’s working for you, consider you are using chromium as well, handle submit hasn’t touched for long.

**Comment by bluebill1049** [comment]
I don't think, this is ever worked, remove `handleSubmit` is doing a direct post to the page itself.

**Comment by chungweileong94** [comment]
@bluebill1049 I think I'm wrong, it might due to the recent few updates of my browser, it might be bug on chromium or something

**Comment by bluebill1049** [comment]
oh ok. no worries then. 👍
