### ISSUE TITLE
`unregister` doesn't update formState to `dirty: true`

### ISSUE THREAD

**Issue by johncalvinroberts** [react-hook-form/react-hook-form#406]
**Describe the bug**
When calling `unregister`, the `formState` `dirty` field doesn't get updated to `true`.  Consider the scenario where `useForm` is used on an `edit` view, and using `defaultValues`. 

**To Reproduce**
1. Create a form using `react-hook-form` with defaultValues `{name: 'hi', thing2: 'hey'}`
2. Call `unregister('hey')` (before editing)
3. Formstate is not updated to dirty

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-array-fields-szyru?fontsize=14
This is a bit of a contrived example, but demonstrates the bug in two ways:

* On the `title` field. Default value is provided, when unregistering the field, the `formState` is not updated to `dirty: true`
* On the `friends` array, removing a friend doesn't update the `formState` to `{dirty: true}`

I included two examples because the first one (unregistering `title` field) is a bit less of a common use case. The second example, however, is a lot more common. Go to edit friends list -> remove friend -> this should update `formState` to dirty.

**Expected behavior**
Expected unregistering a field to update formState to `dirty: true`. IMO, this is the expected behavior BECAUSE: calling `unregister` changes the outputted value of the form. 

**Additional context**
Shout out @MinaAmrouche for the codesandbox, I think I forked yours.

**Comment by bluebill1049** [comment]
hey @johncalvinroberts 

thanks for your detailed issue report. 

1) why are you calling `unregister` manually? when an input get removed, it will get automatically removed from react hook form (calling unregister)

2) I don't think calling `unregister` should trigger `dirty` to true, at least from my understanding.
Dirty true is if the user has already interacted with the form, which means unless you interacted with the form instead of calling `unregister`, beucase `unregister` is just an API from react-hook- form.

**Comment by johncalvinroberts** [comment]
>  Go to edit friends list -> remove friend -> this should update formState to dirty.

This would be the user interacting with the form IMO, because a value has been updated (the `friends` array is dirty.) It may not be interacting directly with the DOM input element, sure, but I think the case still needs to be addressed. Or would be nice if it was addressed. 

Great library btw :) @bluebill1049 you are a true hero

**Comment by bluebill1049** [comment]
Thanks, @johncalvinroberts for your kind words, lovely encouragement <3. it's a tricky one because let's think about it for a second, if `unregister` should manipulate `dirty`, then it probably should set `dirty` to false, because you could treat it as reset the `form`. 

I do have a possible solution in my head if that's something you are stuck with:

we can use `setValue()` to force dirty to be `true`, when you remove `friends`, but then you probably need a hidden `input` to capture that.

**Comment by bluebill1049** [comment]
happy for other users' input on this one as well :)

**Comment by JeromeDeLeon** [comment]
Is it not possible to consider toggling conditional fields, deletion of fields through unregister as form manipulation thus making form dirty? It means if we changed the state of the form in any way, it is considered dirty.

**Comment by bluebill1049** [comment]
I agree with you @JeromeDeLeon . Thanks for your feedback as well

**Comment by bluebill1049** [comment]
going to close this issue, for now, feel free to add your opinion or thoughts on this issue.
