### ISSUE TITLE
Watched form has a different reference on each render

### ISSUE THREAD

**Issue by AlexanderMeheus** [react-hook-form/react-hook-form#4105]
**Describe the bug**
Hello, I don't know if this is intentional behavior or not but watched values are different on each render meaning hook depending on value references (like useMemo or useEffect) will rerun even if the rerender has nothing to do with the form.

**To Reproduce**

1. Go to the codesandbox
2. Click on the 'count' button.
3. See a log in the console on every click.

**Codesandbox link (Required)**

- https://codesandbox.io/s/react-hook-form-watch-reference-oj3vh

**Expected behavior**
If the form didn't change I expect the watched values to be the same reference.

**Desktop (please complete the following information):**

- OS: macOS Catalina v10.15.7
- Browser: Google Chrome Version 87.0.4280.88

**Additional context**
Using react-hook-form v6.15.1

**Comment by wdfinch** [comment]
The intention of `watch` is the capture the current state of form which is does. Does it matter how this is achieved? It's generally safer to return as a new object so this is likely what happens. For your `useEffect` logic, you can check primitive properties of `watch`, which won't have reference vs value issues.

**Comment by italomlp** [comment]
It's something that is blocking us to update to the latest RHF version too. We are using the 6.11.0 version, and always when we update to the latest, we have issues with multiple rerenders caused by watchs. Specifically, there is a screen much complex, with a big form, and there is a lot of watchs because of dependencies in the fields. Not keeping the same reference, React understands that it changed, and rerender many times. In 6.11.0 it does not happen. Is there a way to achieve this in the latest version without deeply checking form values?

**Comment by wdfinch** [comment]
I wouldn't try to base logic on reference vs value objects. Even if this works now in some version, this isn't reliable/safe as it could change down the road if a different object management strategy is used. The best you could here is watch the specific value you are interested in. What is the issue using `watch('some.deeply.nested.value)`?

**Comment by bluebill1049** [comment]
@italomlp use `useWatch`, so it wouldn't impact your root/form level. you only subscribe to whatever you want to watched and re-render only appeared in the component level.

**Comment by AlexanderMeheus** [comment]
My use case is an auto save feature which watches the whole form and debounces a save function sending the values to the backend. This uses a useEffect to react on changed values. Watching separate values would be a bit verbose here in my opinion.

**Comment by bluebill1049** [comment]
in V7, we will have `watch((data) => { console.log(data) })`, in v6, you will have to attach onChange to those inputs and save your data input from a common method.

**Comment by italomlp** [comment]
@wdfinch I haven't tried it. But, as the same case as @AlexanderMeheus, I think it would be a little verbose.
@bluebill1049 I tried it. I tried both, with `form.watch` and `useWatch`, but have no success because of different references. My use case can be compared to the author one, who needed to add a form watched value to useEffect hook. 

Getting your idea, I think it's possible to add a custom hook that attaches the onChange by registered input (I use react-native and all inputs are Controlled) and uses it as a custom useEffect while we don't have V7 yet. I'll give it a try. What do you think about it?

**Comment by bluebill1049** [comment]
> @wdfinch I haven't tried it. But, as the same case as @AlexanderMeheus, I think it would be a little verbose.
> @bluebill1049 I tried it. I tried both, with `form.watch` and `useWatch`, but have no success because of different references. My use case can be compared to the author one, who needed to add a form watched value to useEffect hook.
> 
> Getting your idea, I think it's possible to add a custom hook that attaches the onChange by registered input (I use react-native and all inputs are Controlled) and uses it as a custom useEffect while we don't have V7 yet. I'll give it a try. What do you think about it?

you can build a custom hook in your app, with a deepEqual. pretty sure it's doable.

**Comment by AlexanderMeheus** [comment]
> > @wdfinch I haven't tried it. But, as the same case as @AlexanderMeheus, I think it would be a little verbose.
> > @bluebill1049 I tried it. I tried both, with `form.watch` and `useWatch`, but have no success because of different references. My use case can be compared to the author one, who needed to add a form watched value to useEffect hook.
> > Getting your idea, I think it's possible to add a custom hook that attaches the onChange by registered input (I use react-native and all inputs are Controlled) and uses it as a custom useEffect while we don't have V7 yet. I'll give it a try. What do you think about it?
> 
> you can build a custom hook in your app, with a deepEqual. pretty sure it's doable.

I do this at the moment. Made a custom useDeepMemo hook. Will post it here when I get behind a computer.

**Comment by bluebill1049** [comment]
sweet thanks @AlexanderMeheus for sharing in advance.

**Comment by AlexanderMeheus** [comment]
I can't get to a computer right now for my code but this hook from Apollo client does the same thing (you can use your own equal function or an other library like lodash).

https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/utils/useDeepMemo.ts

**Comment by bluebill1049** [comment]
Thank for sharing @AlexanderMeheus
