### ISSUE TITLE
handleSubmit clears the complete form, error fields blur out on typing anything

### ISSUE THREAD

**Issue by naseemali925** [react-hook-form/react-hook-form#4107]
**Describe the bug**
On clicking the submit button(NEXT as text) all fields data is wiped even if some of the fields are valid. 
After clicking submit and if some fields are invalid the modifying them removes the focus(blurs out) from input making it impossible to type and requires a click of mouse and also clears out the error.

**To Reproduce**
https://codesandbox.io/s/ecstatic-cori-45g3i?file=/src/App.tsx

1. Go to 'https://codesandbox.io/s/ecstatic-cori-45g3i?file=/src/App.tsx'
2. Click on 'NEXT'
3. See error
4. Try to enter text into any of the fields that is invalid and shows error

**Codesandbox link (Required)**
https://codesandbox.io/s/ecstatic-cori-45g3i?file=/src/App.tsx

**Expected behavior**
On clicking submit if fields are invalid, then error must be shown and firstError should be in focus. 
When modifying a field which is invalid, the field should not blur out(leave focus) after hitting a key.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Brave
- Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)

**Additional context**
The TextFieldNew component is a customized Material UI InputBase.

**Comment by wdfinch** [comment]
If all the data is filled out correctly it will work as expected. Your issue is failed validation triggers a rerender and you are dynamically calculating which step to show. This means all the input are remounted again and the form values lost. react-hook-form V6 does **not**  save form values on unmount. So in other words when an input is unmounted then the formValue will be discarded. V7 changed this behavior which is in alpha right now. This is not an issue with react-hook-form, but rather how you handle your rerendering logic.

**Comment by naseemali925** [comment]
@wdfinch Thanks for the reply. I have updated the sandbox link. This time I am not calculating the step dynamically and still the problem is same. Please recheck the sandbox.

**Comment by naseemali925** [comment]
Thanks for the help @wdfinch I figured out the issue and it was resolved.
