### ISSUE TITLE
When registering a field manually, defaultValues no longer prefill

### ISSUE THREAD

**Issue by jsteiner** [react-hook-form/react-hook-form#411]
**Describe the bug**
Starting with react-hook-form version `3.24.2-beta.2`, when registering a field manually (instead of inside a ref), `defaultValues` are no longer filled.

**To Reproduce**
1. Using the codesandbox below, in package.json change the `react-hook-form` version from `3.24.2-beta.1` to `3.24.2-beta.2`.
2. Note that the default value of "josh" is no longer prefilled

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-defaultvalues-t8js7

**Comment by bluebill1049** [comment]
hmmm thanks @jsteiner looks like we broke something in the last release...

**Comment by bluebill1049** [comment]
any chance you can help investigate, i gotta get ready for work, i will take a look when i am in the office too.

**Comment by bluebill1049** [comment]
hmmm just took a closer look
```
register(someRef.current, {
  name,
})
```
don't think we were supposed to have this syntax?

**Comment by jsteiner** [comment]
Hmm. That may be internal (though does seem to be documented in the types there). I was trying to work around an issue with `react-hook-form` not working with [a separate library](https://github.com/buildo/react-autosize-textarea) when passed directly to `ref`.

Agreed that commit looks like the culprit, since it'd ignore the ref in that case.

**Comment by bluebill1049** [comment]
```
register({
  ...someRef.current,
  name,
})
```
what about this?

**Comment by barrymay** [comment]
'boo' on me :)  I'll make a fix tonight and will add a test to match :)

**Comment by barrymay** [comment]
that said, the workaround you mentioned @bluebill1049 should definitely but it's potentially a  bit ugly to read...

**Comment by bluebill1049** [comment]
thanks @barrymay

**Comment by barrymay** [comment]
Hi @jsteiner - upon reviewing this,  I'm going to state this is not a bug but a improved clarity in implementation.

Your code in your sandbox is this
```
      register(someRef.current, {
        name,
      })
```
but what that's doing is setting a new name property in the second param to an *unwanted*   variable, since name is never defined as a variable elsewhere in that code (that's the code sandbox redline is complaining about).
 
(What's worse in this specific scenario is that name is NOT undefined, it's actually setting to window.name, which is a typeof string, which is causing more confusion). If you set name: undefined there, the code actually runs.

In the newer versions of react-hook-form, in order to support scenarios like react-native, we're allowing the name object property to be specified there and using it.  If you're not using that, then you should leave that name prop undefined/unset.

Therefore, In your case you should just say:
```
      register(someRef.current)
```
which was better in the first place IMO :)

Therefore I'm not going to make a change here, I believe this is working as we want it to.  If you had another idea about this let me know.

**Comment by bluebill1049** [comment]
i like what you suggested :) @barrymay

**Comment by barrymay** [comment]
thx - btw, the reason the old code didn't have this issue was because we just ignored whatever was there in the second param - now we do care about it.

**Comment by bluebill1049** [comment]
cool thanks @barrymay

**Comment by jsteiner** [comment]
Nice one @barrymay.

Not defining `name` there was a mistake when transferring to the codesandbox, but removing `name` from the passed options does work. Thanks!

And thanks @bluebill1049 for being so on top of things!

**Comment by muhamad-rizki** [comment]
it looks broken too in React native, my default values got reset whenever registering component manually @bluebill1049

**Comment by bluebill1049** [comment]
which version @muhamad-rizki ?

**Comment by bluebill1049** [comment]
can you give more detail @muhamad-rizki ?

**Comment by muhamad-rizki** [comment]
@bluebill1049 I used version 3.26.4, I have a wizard form that generating child form using json schema, defaultValues getting undefined whenever I jump to the next step and re register new child component. But it's work perfectly whenever it's on first step.
Whenever I jump to the next step, I do reset({}), and re register component

**Comment by bluebill1049** [comment]
actually let's open a new issue for this @muhamad-rizki please paste your code in that issue.
