### ISSUE TITLE
V7 Bug - setValue doesn't work when field array name changed

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4152]
**Describe the bug**
It seems that if a field array item has its name changed and then `setValue` is used to try and update the name, it will not work and nothing will happen. This is somewhat of an edge case so here is my use case:

I have a field array. Unlike most field arrays where the inputs would be displayed right there, my field array has a lot of fields per item and is too big to display all at once. Therefore, I want to display the field array as a list. The user can then edit, delete or add to the list. The add and edit would happen in a separate component somewhere else. 

In the case of creating a new element, I want to:

1. Render the component 
2. Call append to add the element
3. Set an initial value from a server

This means that until append is called, the field array index and therefore name will be different from the final result. This then causes the bug to occur.

**To Reproduce**

1. Go to the sandbox
2. Click on add new element
3. Notice that the `setValue` call on line 37 has no effect

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-t9dnl

**Expected behavior**
I think that `setValue` should work even if a mounted inputs name has changed. I would like to note there is an easy workaround in my case which is to wait untill `append` has finished before rendering the form. However, I would still like to bring this up as other users might not be able to do this.

**Comment by bluebill1049** [comment]
<img width="1502" alt="Screen Shot 2021-02-11 at 4 53 52 pm" src="https://user-images.githubusercontent.com/10513364/107606283-ba7cea00-6c89-11eb-9adb-d75662006a3b.png">

I am not sure if I follow your issue: 

https://codesandbox.io/s/react-hook-form-controller-template-forked-kq47u?file=/src/index.js

can you elaborate a bit more?

**Comment by leapful** [comment]
@bluebill1049 : I think wdfinch is expecting the added input should have value "newValue".

@wdfinch: It's not a bug. The issue is from "Add new item" button. You should prevent default the click event, otherwise, it will trigger submit on form.

Working sample:http://codesandbox.io/s/react-hook-form-controller-template-forked-5johl?file=/src/index.js

**Comment by wdfinch** [comment]
@leapful this shows "newValue" initially, but if the user clicks on the page, it will revert back to "test".

@bluebill1049 So the issue here is the latest input displayed is `names.1.name`. This is proven by the console log. Additionally, the form values object shows that "newValue" is the value of the second element. Therefore, I would expect the value of the input as shown on the screen to be "newValue" as this would align with what's being logged in the console. However, it's not. It's still showing the value of "test" which is the value for the first and originally mounted element.

**Comment by leapful** [comment]
@wdfinch : The value is reverted to "test" because React is confusing on attribute "value" from "field" of custom component "Input" at line 12.

By default, when adding new input like your example, tag <input> will be rendered as <input value=undefined /> but then it will change value on the next rendering. It will lead to case "uncontrolled input is changing to controlled input" and make a wrong setting on attribute "value" of tag <input>.

We can easily fix the issue by set default value of attribute "value" to empty string.

Working sample: https://codesandbox.io/s/react-hook-form-controller-template-forked-5johl?file=/src/index.js

**Comment by bluebill1049** [comment]
Thanks @leapful for jumping in and help.

**Comment by wdfinch** [comment]
Gotcha. Ok, that makes sense. I guess the issue here there is the button trying to submit the form and we have to manually stop the event. I think that a submit should **only** occur if the button/input type is `submit`. Otherwise, this could lead to some edge cases like this as it's common practice to place buttons inside form tags. What are your thoughts on adding a check to the library to make sure the button/input type is `submit` before triggering a submit event?

**Comment by bluebill1049** [comment]
> What are your thoughts on adding a check to the library to make sure the button/input type is `submit` before triggering a submit event?

Don't think we should add that check. It's HTML standard.

**Comment by wdfinch** [comment]
Ok, then I guess we can close this then. Maybe just make a note about this case in the docs if you think it's relevant.
