### ISSUE TITLE
IonInput doesn't register properly without setting its' `type` property

### ISSUE THREAD

**Issue by OmriAroesti** [react-hook-form/react-hook-form#4189]
**Describe the bug**
I am unsure whether this bug is due to a behaviour quirk of Ionic, or of react-hook-form. But it is really peculiar -
It seems as if registering an `<IonInput>` component without specifying its' type causes it to not be updated as its' value changes.

**To Reproduce**

1. Go to the codesandbox.
2. Write anything in the input.
3. Notice how the valid: false/true is updated, and the console fills with form value and validation logs, as expected.
4. Remove the `type="text"` in line 32.
5. Write anything in the input, again.
6. Notice how now, the validity doesn't update, and there are no logs until when the minLength validation is changed.

**Codesandbox link (Required)**
[Here](https://codesandbox.io/s/ionic-react-forked-5jdf0?file=/src/pages/Home.tsx)

**Expected behavior**
The input should register.

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- Version 88.0.4324.150 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
I think for IconInput, you should use `useController`. 

https://react-hook-form.com/resources do s research there, i think there is some articles for ionic

**Comment by leapful** [comment]
@OmriAroesti @bluebill1049 

Ionic Framework is built by using Web Component, the real HTML DOM is rendered as:

```
<ion-input>
   <input class="native-input" />
</ion-input>
```

while the method register() from react-hook-form is expecting attribute "type" to be exist so it can attach change handler on the input element.

https://github.com/react-hook-form/react-hook-form/blob/45e869486b97e5ff5c23be901bea7746a02a0ef9/src/useForm.ts#L1031-L1038

By default, native input tag will have default value "text" for attribute "type" therefore it's fine for using input without specifying its attribute "type" but Ionic custom element "ion-input" is extending HTMLElement and has no default value of "type".

Since ion-input element is implemented with all behaviors of native input, setting default value "text" for "type" will work as normally too.

For example:

```
const CustomIonInput = ({ type = 'text', ...props }) => {
   return <IonInput type={type} {...props} />;
}

<CustomIonInput name="test" ref={register()} />
```

**Comment by bluebill1049** [comment]
That's an awesome investigation! @leapful FYI We shouldn't have this issue in the incoming V7.

**Comment by bluebill1049** [comment]
actually, `type` is required, that's how we determined which `type` input it is.

**Comment by OmriAroesti** [comment]
@bluebill1049 So this will persist in V7, then?

**Comment by bluebill1049** [comment]
please use `useController` for iconic inputs.

**Comment by bluebill1049** [comment]
here is a v7 solution for V7: https://codesandbox.io/s/ionic-react-forked-6v9ut?file=/src/pages/Home.tsx still i would use useControler, because it would not work nicely with reset, setValue APIs

**Comment by blatoo** [comment]
Hi all, I also stuck into this problem now... I found here solution with useController, but stuck into the Typescript types for IonInput. I have totally no idea how to make an modified IonInput for react-hook-form... 

Can someone make an codesandbox example for V7 with `useController`??? 

Here is my try, but the `props` is somehow wrong...

```
const  IonInput_RHF = (props: UseControllerProps<IFormInputs> & Parameters<typeof IonInput>) => {

  const { field, fieldState } = useController(props);

  return (
    <div>
      <IonInput {...field} placeholder={props.name} />
      <p>{fieldState.isTouched && "Touched"}</p>
      <p>{fieldState.isDirty && "Dirty"}</p>
      <p>{fieldState.invalid ? "invalid" : "valid"}</p>
    </div>
  );
}
```
