### ISSUE TITLE
react-router-dom Route weird interaction with Controller

### ISSUE THREAD

**Issue by palcikaman** [react-hook-form/react-hook-form#4199]
**Describe the bug**
Providing props for the component used in the Route component as seen in the codesandbox example causes in infinite loop, if the component uses the Controller component. I'm not exactly sure what causes it, I'm not sure if I'm using the Route component properly. This might not be a bug, but it's better to report it i think.

The following error is thrown:

Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at Controller (https://emw8p.csb.app/node_modules/react-hook-form/dist/index.esm.js:1689:17)
    at Form (https://emw8p.codesandbox.io/src/form.js:23:19)
    at component

**To Reproduce**

1. Go to https://codesandbox.io/s/awesome-star-emw8p?file=/src/App.js
2. Click on submit button (might get the infinite loop without the click)
3. See error (WARNING: There is an infinite loop on the page, so it will drain the resources of your PC as much as the browser lets one tab drain them)

**Codesandbox link (Required)**
https://codesandbox.io/s/awesome-star-emw8p?file=/src/App.js

**Expected behavior**
If this is an actual bug with this library, it shouldn't go in an infinite loop.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Opera
- Version 74.0.3911.107

**Smartphone (please complete the following information):**

**Additional context**
I got around this issue by not providing props for the component used in Route, so even if this is a bug, it's probably not a high prio one. I might be using the Route component wrong in the example.

**Comment by bluebill1049** [comment]
I would recommend doing this instead: https://codesandbox.io/s/determined-sound-uyos8?file=/src/App.js (I think it's probably the correct way to use react-router as well)

otherwise, this line will kick in when Controller gets mount and unmounted: 

https://github.com/react-hook-form/react-hook-form/blob/master/src/useController.ts#L155

```tsx
import { FormProvider, useForm, useFormContext } from "react-hook-form";
import { BrowserRouter, Route, Switch } from "react-router-dom";
import "./styles.css";
import Form from "./form";

const Test = () => {
  const methods = useFormContext();

  return (
    <form
      onSubmit={methods.handleSubmit((values) => {
        console.log(values);
      })}
    >
      <Form name={"input1"} />
      <button>submit</button>
    </form>
  );
};

export default function App() {
  const methods = useForm();

  return (
    <BrowserRouter>
      <FormProvider {...methods}>
        <Switch>
          <Route exact path="/" component={Test} />
        </Switch>
      </FormProvider>
    </BrowserRouter>
  );
}
```

**Comment by leapful** [comment]
@palcikaman @bluebill1049 

The root cause of infinite loop on rendering is from <Route component />. According to React Router documentation:

> When you use component (instead of render or children, below) the **router uses React.createElement to create a new React element** from the given component. That means if you provide an **inline function to the component prop**, you would **create a new component every render**. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. When using an inline function for inline rendering, use the **render** or the children prop (below).

Referrer: https://reactrouter.com/web/api/Route/component

Action submit form will trigger a re-rendering on App and also Route with an inline function of prop "component". The Route component will render new Form (Controller) component and the old one will be destroyed. At that time, the old Controller component will perform clean up life cycle which calls "unregister" inside useController hook and force update form state but when form state is updated, App (currently using useForm hook) will re-render again and fall into a loop hole with Route.

Switching to render will fix the issue: https://codesandbox.io/s/still-moon-zi99s?file=/src/App.js

But please use the suggestion of @bluebill1049 instead of handle routing inside a form because it might lead into unexpected issue on both routing and form library.

**Comment by palcikaman** [comment]
Thanks for the clarification. I see why my original sandbox didn't work now. Should I just close this issue now?

**Comment by bluebill1049** [comment]
> @palcikaman @bluebill1049
> 
> The root cause of infinite loop on rendering is from . According to React Router documentation:
> 
> > When you use component (instead of render or children, below) the **router uses React.createElement to create a new React element** from the given component. That means if you provide an **inline function to the component prop**, you would **create a new component every render**. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. When using an inline function for inline rendering, use the **render** or the children prop (below).
> 
> Referrer: https://reactrouter.com/web/api/Route/component
> 
> Action submit form will trigger a re-rendering on App and also Route with an inline function of prop "component". The Route component will render new Form (Controller) component and the old one will be destroyed. At that time, the old Controller component will perform clean up life cycle which calls "unregister" inside useController hook and force update form state but when form state is updated, App (currently using useForm hook) will re-render again and fall into a loop hole with Route.
> 
> Switching to render prop will fix the issue: https://codesandbox.io/s/still-moon-zi99s?file=/src/App.js
> 
> But please use the suggestion of @bluebill1049 instead of handle routing inside a form because it might lead into unexpected issue on both routing and form library.

wow, thanks @leapful i didn't even digging into that react router doc. thanks very much for the help.
