### ISSUE TITLE
formState.isValid behaviour changed between version 6.11.3 and 6.11.4 when using resolver.

### ISSUE THREAD

**Issue by micnil** [react-hook-form/react-hook-form#4219]
**Describe the bug**
In version 6.11.3 and before, the formState.isValid was true when the forms defaultValues are valid but not rendered in the DOM.
In version 6.11.4 and after, the formState.isValid is initially set to true, but is immediately set to false after the resolver has run, even if the defaultValues are valid.

**To Reproduce**

1. Go to https://codesandbox.io/s/rhf-incorrect-isvalid-wluyk?file=/src/App.tsx
2. Open console and see that: isValid is initially true, but later set to false after resolver has been run.
3. Click "Toggle form" and see that the Confirm button is disabled (and the isValid flag continues to be false)

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-incorrect-isvalid-wluyk?file=/src/App.tsx

**Expected behavior**
I expect the isValid flag to be true when clicking "Toggle form" to display the form.
Expected behavior can be reproduced by opening the above codesandbox (https://codesandbox.io/s/rhf-incorrect-isvalid-wluyk?file=/src/App.tsx) and changing the react-hook-form version to 6.11.3

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser Chrome  88.0.4324.146 
- Version  6.11.4 and later

**Comment by leapful** [comment]
@micnil @bluebill1049 

There was a change on useForm.tsx that causes this unexpected behavior at commit: 

https://github.com/react-hook-form/react-hook-form/commit/9ccec798e7a976871ef3d8b9a742e533ed97cc40#diff-07a36f93b9f2954db217ab021a0444c89c5fabc9506b8c390db329e5e74b9f06L714-L720

where the "defaultValuesRef" is removed on values to be validated by resolver.

@bluebill1049 Could you please check again why we need to remove "defaultValuesRef" ?

**Comment by bluebill1049** [comment]
Thanks for the investigation! @leapful you want to send a PR (since you find it out) to revert that code? I think I was trying to trim some extra logic.

**Comment by leapful** [comment]
@micnil @bluebill1049 

PR is created at https://github.com/react-hook-form/react-hook-form/pull/4229

**Comment by leapful** [comment]
@bluebill1049

There is one failed automation test for the use case show/hide required input. 

When a required input is hidden, the test case expected formState.isValid is false but now because "defaultValues" is added on validation resolver, formState.isValid is now true.

While @micnil use case is to show the whole form, formState.isValid is expected to be true (by using added "defaultValues"), the failed automation test case, it only hides one required input, formState.isValid is expected to be false. 

I think this test case is the reason why "defaultValues" is removed in the previous commit.

What do you think about this case ?

https://github.com/react-hook-form/react-hook-form/runs/1925961233?check_suite_focus=true
