### ISSUE TITLE
useFieldArray fields doesn't change on name prop update

### ISSUE THREAD

**Issue by andfk** [react-hook-form/react-hook-form#4220]
**Describe the bug**
Im not 100% sure if this is a bug or is an expected behaviour but im in a scenario where i have to handle a multi level list and i thought it could be possible with `useFieldArray` and change the name as needed but i've found this is not totally possible as when the name is changed, the values still remains the same.

**To Reproduce**

1) useFieldArray is initialised with the items at index 0 by `activeStep`
2) Click `Step +` or `Step -` to change `activeStep`
3) As you can see, the fields values remains the same but `activeStep` is updated, so name passed to `useFieldArray` should be too, then i guess it is memoized?

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-4ihjc?file=/src/index.js

**Expected behavior**
The fields values are refreshed on name update

**Additional context**
Anything i can help to fix the issue? (unless this is the way it should work)

**Comment by leapful** [comment]
@andfk 

Your CSB sample currently sets wrong value for attribute "name" of the input:

```
// If useFormArray is using `names[${activeStep}].users`

useFormArray({
  name: `names[${activeStep}].users`
})

// then the Controller must be used for all inputs with the correct name as

<Controller name={`names[${activeStep}.users.[{$index}].firstName]`} />

```

Working sample: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-cppmi?file=/src/index.js

**Comment by andfk** [comment]
awesome @leapful so i was doing the bug and didnt noticed of it until you mentioned.

Hopefully this helps someone else blind like me in the future. Many thanks!

**Comment by andfk** [comment]
@leapful i've noticed from your CSB there are 2 "bugs".

1 - Form values are not the same as default values. It looks like only the "active step" is available. If you're on index > 0, the previous becomes `undefined`.
![Screenshot 2021-02-17 at 17 53 20](https://user-images.githubusercontent.com/1377735/108238233-07a90200-7149-11eb-8b61-6e2382b837f3.png)
2 - If a value of the step has been edited and you change the step, the edited stuff is lost. May be related to the previous bug.

Should i create another issue for this?

**Comment by leapful** [comment]
@andfk 

When using a specific index with useFieldArray() like your example, the form only renders exactly number of input that is match with the index.

For example: If current index is 1 and"names[1].users" has 2 items then only 2 items are rendered inside form tag. 

While onSubmit() method just collects current data from the form, the submitted value at the end is always the data of current index.

In order to achieve the behavior like your expectation, a.k.a wizard form, you will need to use state management to keep track on the previous step data, something like this one: https://react-hook-form.com/advanced-usage#WizardFormFunnel

**Comment by andfk** [comment]
@leapful great! I really appreciate your help, many thanks. I'll follow the approach you suggest.

**Comment by bluebill1049** [comment]
Thank you very much @leapful
