### ISSUE TITLE
Remove is not working with nested field arrays on 6.15.2 and above

### ISSUE THREAD

**Issue by Elia-Darwish** [react-hook-form/react-hook-form#4259]
**Describe the bug**
When using nested field array, remove has stopped working properly on version 6.15.2 and 6.15.3.
Calling remove on the parent field array is not behaving as expected. Instead, the fields are somehow being replaced with empty fields while maintaining the same array length. Also, the field id `undefined` for the new fields.

I created a minimal CodeSandbox to demonstrate the bug:

**To Reproduce**

1. Go to the CodeSandbox provided below.
2. Click on add child.
3. Click on remove child.
4. The child is not removed and react will show a warning saying `Warning: Each child in a list should have a unique "key" prop.`
5. downgrade to version 6.15.1
6. add children and nested children and remove them.
7. notice how no errors are shown and that remove is behaving as expected!

**Codesandbox link (Required)**
https://codesandbox.io/s/hook-form-nested-field-array-t4m3g?file=/src/App.js

**Expected behavior**
Remove should behave like it did before on earlier versions.

**Desktop (please complete the following information):**

- OS: macOS
- Chrome 88
- 6.15.3

**Additional context**
I might be wrong, but I think this is related to #4172

**Comment by leapful** [comment]
@Elia-Darwish @bluebill1049 

It seems the root cause is from line 511 of useFieldArray.ts, not from #4172.

https://github.com/react-hook-form/react-hook-form/blob/c67d145fdd123f9e197a22140cf27fd8f4d4c247/src/useFieldArray.ts#L506-L512

It should be 

```
unset(fieldArrayValuesRef.current, name);
```

But fixing this line it's not enough because it will lead into another issue because "fieldArrayValuesRef.current" after appending new item is something like:

```
{
   children: [{ ...First added item }]
}

```

When removing that item, with the name is "children[0].nested" in this case, the method "unset" from utils/unset.ts only removes the reference of item by using native method "delete" therefore the whole array "children" is now an empty array but length is still 1. It will lead into undefined error when trying to add child again because position "0" will be undefined and the new added item will be at position "1"

```
{
  children: [ undefined, {... Second added item }]
}
```

https://github.com/react-hook-form/react-hook-form/blob/c67d145fdd123f9e197a22140cf27fd8f4d4c247/src/utils/unset.ts#L53

@bluebill1049 : Can we use Array.prototype.splice() if the target object to be unset is an array ?

**Comment by bluebill1049** [comment]
The good news is v7 doesn't have this problem: https://codesandbox.io/s/hook-form-nested-field-array-forked-ud19v?file=/src/App.js

i will take a look for a solution.

**Comment by bluebill1049** [comment]
@leapful i just quick tested with your fix above: https://codesandbox.io/s/hook-form-nested-field-array-forked-2or6p?file=/src/App.js functional test pass.

**Comment by bluebill1049** [comment]
Do you want to send a PR @leapful since you are the one (once again) solves the puzzle?

**Comment by leapful** [comment]
@bluebill1049 

Okie, I will open a pull request. BTW, shall we update the method "unset" too (At least for the current v6) ? Because in your quick fix CSB sample https://codesandbox.io/s/hook-form-nested-field-array-forked-2or6p?file=/src/App.js, re-adding child after first removing will get undefined error as the array value is empty array with length = 1.

**Comment by bluebill1049** [comment]
> @bluebill1049
> 
> Okie, I will open a pull request. BTW, shall we update the method "unset" too (At least for the current v6) ? Because in your quick fix CSB sample https://codesandbox.io/s/hook-form-nested-field-array-forked-2or6p?file=/src/App.js, re-adding child after first removing will get undefined error as the array value is empty array with length = 1.

sounds good to me! 👍

**Comment by leapful** [comment]
@bluebill1049 @Elia-Darwish 

PR is created at https://github.com/react-hook-form/react-hook-form/pull/4262

We don't need to correct unset :D It's my mistake to not correct the nest child in the sample.

**Comment by justjuank** [comment]
Hi there, first of all thanks for this awesome library.
Just wanted to let you know this issue is still happening on v6.15.4

**Comment by bluebill1049** [comment]
> Hi there, first of all thanks for this awesome library.
> Just wanted to let you know this issue is still happening on v6.15.4

can you share a reproducable CSB?

**Comment by justjuank** [comment]
> > Hi there, first of all thanks for this awesome library.
> > Just wanted to let you know this issue is still happening on v6.15.4
> 
> can you share a reproducable CSB?

I used that same CSB from above and upgraded react-hook-form to the latest: https://codesandbox.io/s/hook-form-nested-field-array-forked-5nl8i
Does this work for you?

**Comment by Elia-Darwish** [comment]
I played around with that and this is what seems to be happening.

When using nested field arrays, remove is not removing the field but setting it to undefined instead. fields.length will maintain in this case the same length.

I created a new issue here: #4364

**Comment by yaeSakuras** [comment]
Remove is not working with nested field arrays on 7.19.5
