### ISSUE TITLE
Use a third-party UI to set default values asynchronously, and style issues occur

### ISSUE THREAD

**Issue by flycj** [react-hook-form/react-hook-form#453]
**Describe the bug**
Please see the following link for details:
https://codesandbox.io/s/hungry-haze-65mlr

Why is the value of the first input box being overwritten?

第一个输入框中的值，被标签label 覆盖了，但是第二个没有
这个问题很奇怪

**Comment by bluebill1049** [comment]
because material-ui is not supporting uncontrolled input, we had submitted a PR before by @stramel and it was rejected. would you like to submit an issue at material-ui, hopefully, they will address that soon. 

for now, you will have to `register` during useEffect and use `setValue`.

问题出在MUI他们暂时不愿意支持非控制组件。可以的话在他们那里发个问题。

**Comment by bluebill1049** [comment]
This is an issue with material UI :(
