### ISSUE TITLE
Chakra checkbox returns "" instead of true when is checked

### ISSUE THREAD

**Issue by violabg** [react-hook-form/react-hook-form#4603]
I don't know if is a react-hook-form or a chakra-ui bug, but after updating  to  react-hook-form version 7, I'm getting "" instead of true for checkbox value when selected. It only happens on Chakra checkbox, not input checkbox.

I'm attaching a codesandbox with both inputs to reproduce this bug.

https://codesandbox.io/s/react-hook-form-get-started-forked-gjcbs?file=/src/index.js

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by violabg** [comment]
Sorry but I didn't know ha to explain better than attaching a codesanbox. I'll try again

Describe the bug
I don't know if is a react-hook-form or a chakra-ui bug, but after updating to react-hook-form version 7, I'm getting "" instead of true for checkbox value when selected. It only happens on Chakra checkbox, not input checkbox.

To Reproduce
Steps to reproduce the behavior:

Go to https://codesandbox.io/s/react-hook-form-get-started-forked-gjcbs?file=/src/index.js
check both checkboxes 
open code sandbox console
press submit button
it prints:
`{test: "", test2: true}`


Codesandbox link (Required)
https://codesandbox.io/s/react-hook-form-get-started-forked-gjcbs?file=/src/index.js

Expected behavior
should print:
`{test: true, test2: true}`

**Comment by j-dominguezp** [comment]
Can confirm this. 

The only difference I found between HTML native checkbox and Chakra UI checkbox is that onChange event returns different values in **e.target.value** HTML native returns **"on"** and chakra-ui returns **""**.

**Both e.target.checked have the right value.** I had to use Controller to make it work.

Hope that helps.

**Comment by violabg** [comment]
I have also created e forked sample with react-hook-react version 6 that works:

https://codesandbox.io/s/react-hook-form-get-started-forked-6k5yc?file=/src/index.js

**Comment by violabg** [comment]
> 
>  I had to use Controller to make it work.
>

I'll try that

**Comment by manzoorwanijk** [comment]
I can confirm this with Chakra UI Switch, which is nothing but a checkbox.

**Comment by violabg** [comment]
> > I had to use Controller to make it work.
> 
> I'll try that

Yes with the Controller is working, but as you can see from here:
https://codesandbox.io/s/react-hook-form-get-started-forked-6k5yc?file=/src/index.js

in version 6 was working without Controller.
It's not a problem for me I can easily use Controller, just want to report in case is a bug

**Comment by leapful** [comment]
@violabg @bluebill1049 @j-dominguezp @manzoorwanijk 

When using method "register" on a native checkbox element, the value of attribute "value", if exists, will be the truthy value of checkbox instead of boolean "true".

By default, Chakra UI always puts attribute "value" to checkbox element, for example:

```
<input value />
```

but with this setting, default value of attribute "value" is always empty string, that's why it returns empty string when the checkbox is checked.

@bluebill1049 

Back in v6, there is a check if attribute "value" is empty in order to return boolean true but it has been removed in v7, could you please confirm it's an expected behavior ?

![Screenshot_20210404_031722](https://user-images.githubusercontent.com/18494222/113490519-b4222600-94f4-11eb-8a66-f905f38b3cc3.png)

**Comment by bluebill1049** [comment]
@leapful hmmm I was trying to reduce code, I don't think the value prop should be omitted if not used. If this causing issues for everyone, happy to revert it back. @leapful would you like to send a PR? Thanks very much for the investigation as well.

**Comment by leapful** [comment]
@bluebill1049 PR is created at https://github.com/react-hook-form/react-hook-form/pull/4614
