### ISSUE TITLE
v7: Does not work <input {...register('example')} onChange={...}>

### ISSUE THREAD

**Issue by kensukesaito** [react-hook-form/react-hook-form#4616]
**Describe the bug**

You cannot input it.

**To Reproduce**

```typescript
import * as React from 'react'
import * as reactHookForm from 'react-hook-form'

type FormValues = {
  example: string
}

const ExampleForm: React.FunctionComponent = () => {
  const form = reactHookForm.useForm<FormValues>()
  console.debug('form.watch()', form.watch())
  console.debug('form.formState.errors', form.formState.errors)
  return (
    <form>
      <input type="text" {...form.register('example')} onChange={() => { form.trigger() }}></input>
    </form>
  )
}
```

This code works on v6.

**Codesandbox link (Required)**

https://codesandbox.io/s/cool-moon-73lj9

**Desktop (please complete the following information):**

- OS: macOS Big Sur (latest)
- Browser: Chrome (latest)

**Comment by leapful** [comment]
@kensukesaito 

There is already an option "mode" = "onChange" for useForm hook to trigger validation on change of the input. Furthermore, method "register" of react-hook-form v7 will also inject "onChange" to input element in order to handle on change data, therefore the onChange handler with "form.trigger()" will cause unexpected result on the form.

Working sample: https://codesandbox.io/s/mystifying-chandrasekhar-3hs70?file=/src/App.tsx

**Comment by bluebill1049** [comment]
because your onChange will overwrite what's returned by `register`, so nothing gets send to hook form. i would move `register` out from render 

```
const props = register('test')

<input onChnage={(e) => {
  props.onChange(e);
  // do your stuff here
}} />
```

or you should follow what @leapful has suggested above.
