### ISSUE TITLE
V7: Dynamic names of inputs and default values

### ISSUE THREAD

**Issue by KiwiKilian** [react-hook-form/react-hook-form#4794]
**Describe the bug**
When inputs are rendered with dynamic names V7 is not displaying the proper default values. Uncontrolled inputs show the correct new default value once, but not on further name changes. With V6 the controlled input always updates the value based on the default value, the uncontrolled is never changed.

**To Reproduce**
1. Click the "Change name" button in both sandboxes for the controlled and uncontrolled example
2. Observe the value display in the input

**Codesandbox link**
V7 https://codesandbox.io/s/rhf-v7-dynamic-name-5dfhq
V6 https://codesandbox.io/s/rhf-v6-dynamic-name-ubgtf

**Expected behavior**
The controlled input should always display the default value of the name given – like the controlled input with V6. Also the behavior of the uncontrolled input seems unusual, but I'm not sure what's correct.

**Comment by bluebill1049** [comment]
`defaultValue` is meant to be made for the first initial re-render (for uncontrolled), it's working for Controller because inside it's a controlled component.

**Comment by KiwiKilian** [comment]
> it's working for Controller because inside it's a controlled component

@bluebill1049 but this behavior is only true for V6, it’s not working with V7 as you can see here in the first example: https://codesandbox.io/s/rhf-v7-dynamic-name-5dfhq

**Comment by bluebill1049** [comment]
first of all, thanks for the issue, after careful investigation, I think it's a design limitation on our part. here is why? 

in RHF, comonet/controller unmount/remount will remain its value, so once it's mounted the value will be hosted internally at hook form, which results when you toggle the name is not updating from the default value. To fix your issue is rather simple which is the following code: 

```
setInputStateValue(
  isUndefined(defaultValue)
    ? get(defaultValuesRef.current, name)
    : defaultValue,
);
```

at `useEffect` by `name` dep, however, this means when a component unmount and remount will taking value from defaultValues/deafultValue, which is not the current value.

here is a unit test:


```ts
it('should set initial state from unmount state', () => {
    const Component = ({ isHide }: { isHide?: boolean }) => {
      const { control } = useForm();
      return isHide ? null : (
        <Controller
          defaultValue=""
          name="test"
          render={({ field }) => <input {...field} />}
          control={control}
        />
      );
    };

    const { rerender } = render(<Component />);

    fireEvent.input(screen.getByRole('textbox'), { target: { value: 'test' } });

    rerender(<Component isHide />);

    expect(screen.queryByRole('textbox')).not.toBeInTheDocument();

    rerender(<Component />);

    expect(screen.getByRole('textbox')).toHaveValue('test');
  })
```

so you will have to host two separate `Controller` for the name switching, now I know this is not convenient, however, I think to keep consistent with such a feature we introduced in v7 is important. Hope you understand.

**Comment by KiwiKilian** [comment]
My solution for now is to use the key prop. If somebody has a different, more performant solution let me know!
```js
<Controller
    key={dynamicName}
    name={dynamicName}
    render={({ field }) => <input {...field} />}
    control={control}
/>
```

**Comment by bluebill1049** [comment]
All valid feedback above and thanks for understanding! 

That's actually a really smart idea. I have listed similar idea here too: https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator
