### ISSUE TITLE
V7 useFieldArray if value null application crushes

### ISSUE THREAD

**Issue by rvashchenko** [react-hook-form/react-hook-form#4826]
**Describe the bug**
When i request data from server, optional array value retuned with value - null, i send it in defaultValues form or reset form and after it application crushes

**To Reproduce**

1. Go to [sandbox example](https://codesandbox.io/s/keen-pine-fsmoz)
2. Click on button 'Reset items to null'

**Codesandbox link (Required)**
https://codesandbox.io/s/keen-pine-fsmoz

**Comment by bluebill1049** [comment]
please make sure to reset to empty `[]`, it's a field array and we don't support other data type other than array.

**Comment by dylanlt** [comment]
It looks like there is a problem in the get utility, which should be returning an empty array for the null value.
`const fieldValues = get(values, _name.current, []);`

**Comment by slax57** [comment]
I came to the same conclusion as @dylanlt 

This is problematic for us, because in our app we have no initial knowledge of whether a given field will be used as an array or not, so we cannot blindly transform all null values into empty arrays.

It would be much simpler for us if react-hook-form could do this transformation internally, ie. if the `get(values, _name.current, [])` line would actually return `[]` when the field value is `null`.

@bluebill1049 would it be worth considering to change this in https://github.com/react-hook-form/react-hook-form/blob/master/src/useFieldArray.ts#L123, so that if the field value is `null` the returned `fieldValues` is actually `[]` (hence preventing the `Cannot read properties of null (reading 'map')` error with `fieldValues.map(generateId)` 2 lines below) ?

**Comment by bluebill1049** [comment]
thanks for the investigation and digging into the source code. I think i prefer not to manipulate with the date type here by forcing null to become array type.

**Comment by relferreira** [comment]
Is there any workaround to this problem? I'm in the same situation as @slax57
