### ISSUE TITLE
Reset values ignored when keepDefaultValues is true

### ISSUE THREAD

**Issue by cameronevans** [react-hook-form/react-hook-form#4830]
**Describe the bug**
If `{ keepDefaultValues: true}` is passed to `reset()` the `values` prop will be ignored.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-reset-form-forked-2jzn9?file=/src/index.js
2. Click on 'Reset with new values & keepDefaultValues = true' button
3. The form's values do not change

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-reset-form-forked-2jzn9?file=/src/index.js

**Expected behavior**
The form is reset with the new values and isDirty = true

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version: 87

**Additional context**
If I am misunderstanding the intended behaviour should the docs be updated to show that the values prop and keepDefaultValues option are mutually exclusive?

**Comment by bluebill1049** [comment]
Thanks for the issue report, there are couple of things.

- `defaultValues` is what's populate those native inputs, so when you keeping the `defaultValues` the original value remains unchanged. so alternative
- I think you are better of using `setValue` if you just want to change the values of the input. 
- you should be able to use Controller to achieve this (after the fix) because Controller has its own local state for value, so we can update the value without touching the defaultValues.
