### ISSUE TITLE
field array loses values using Controller

### ISSUE THREAD

**Issue by nucleartux** [react-hook-form/react-hook-form#4857]
**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-78qdb?file=/src/fieldArray.js:665-670
2. Click "Append", enter any text
3. Click "hide" button and then "show"
4. See default values in text input

If I use `register` instead of `Controller` everything is fine. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-78qdb?file=/src/fieldArray.js:665-670

**Comment by bluebill1049** [comment]
Let me know if this beta version fixes the issue: `v7.2.3-beta.0`

**Comment by bluebill1049** [comment]
I just tested it and it works fine on my end, let me know we can release this in the next couple days.

**Comment by nucleartux** [comment]
Just checked, everything works fine now.

**Comment by Raphaww** [comment]
It works fine for me too thanks

**Comment by bluebill1049** [comment]
Thanks guys ❤️

**Comment by bluebill1049** [comment]
I am going to roll back this fix guys, as this is breaking a deeply nested field #4941 https://github.com/react-hook-form/react-hook-form/issues/4941, so to work around this issue.

let me explain the problem because useFieldArray needs defaultValue as the initial input state. Toggling input doesn't really change the defaultValue stored in useFieldArray resulted in the above issue.  

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-31soo

so work around this issue for toggling input, you can use getValues to set the defaultValue, well I know this is not convenient, but it's about to cover all use cases, and I hope for your understanding. also you can use `useWatch` API for the individual's defaultValue as well.

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-ez7un?file=/src/fieldArray.js

**Comment by bluebill1049** [comment]
I am going to roll back this fix guys, as this is breaking a deeply nested field #4941 https://github.com/react-hook-form/react-hook-form/issues/4941, so to work around this issue.

let me explain the problem because useFieldArray needs defaultValue as the initial input state. Toggling input doesn't really change the defaultValue stored in useFieldArray resulted in the above issue.  

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-31soo

so work around this issue for toggling input, you can use getValues to set the defaultValue, well I know this is not convenient, but it's about to cover all use cases, and I hope for your understanding. also you can use `useWatch` API for the individual's defaultValue as well.

https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-ez7un?file=/src/fieldArray.js

I have also included a new section in the doc: 

<img width="959" alt="Screen Shot 2021-04-25 at 1 36 29 pm" src="https://user-images.githubusercontent.com/10513364/115979781-3e791980-a5cb-11eb-99c0-bb939435e303.png">

**Comment by FDiskas** [comment]
is this related?
working version 7.0.0rc.2 https://codesandbox.io/s/usefieldarray-conditional-forked-ft4xf?file=/src/App.tsx:821-834
all other versions does not works.

**Comment by shestakov-vladyslav** [comment]
This is very unobvious 🙁
And I can't find this information in documentation anymore

**Comment by shestakov-vladyslav** [comment]
Why useFormContext and FormProvider aren't used in the example? Is it important or not?
