### ISSUE TITLE
Cannot read property 'split' of undefined and Validation Problem

### ISSUE THREAD

**Issue by gianluca1606** [react-hook-form/react-hook-form#4863]
Hello guys,
I keep getting the error: Cannot read property 'split' of undefined furthermore my validation with Yup does not look like it is working.

[Sandbox](https://codesandbox.io/s/restless-cdn-0w0qp?file=/src/App.js)

I would expect the form to work normally as it did in the past and I would also expect my validation to trigger and get the errors from the resolver.

- Browser [ chrome]

*

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by gianluca1606** [comment]
> #2848

I corrected the Issue is it okay now ?

**Comment by bluebill1049** [comment]
The problem is you are using v6 syntax: https://react-hook-form.com/api/useform/register

<img width="662" alt="Screen Shot 2021-04-20 at 8 21 06 am" src="https://user-images.githubusercontent.com/10513364/115310578-5b6bb200-a1b1-11eb-8bdb-d05d9bb355bd.png">

**Comment by surjithctly** [comment]
I had the same issue today because I didn't realize the new update. Was just using working code from old project. And showed this message without any meaning. 

@bluebill1049 Is it possible to show a meaningful error message in this case? eg:

`ref={register()} is no more valid since v7, please check the upgrade guide`

Otherwise, I'm sure a lot of people have this issue and spend their time looking through what the `split` means to their code.

**Comment by bluebill1049** [comment]
Thanks for the feedback @surjithctly we don't have dev/prod build anymore, so getting those warning message is a bit tricky with esm, and I did consider throwing a better error, but the trade-off is it will increase the package size quite a bit, I think I will leave as it is for a while until more users r landing on v7. I am happy to answer those questions or even better refer to the doc.
