### ISSUE TITLE
V7 useWatch returns undefined after reset.

### ISSUE THREAD

**Issue by manzoorwanijk** [react-hook-form/react-hook-form#4938]
**Describe the bug**
The bug #4912  is still there. This issue has been hampering the progress for many days now.

**To Reproduce**

1. Go to Sandbox link
2. Click on Submit two times
3. Check the console for the value of Last Name
4. Now change the value of only the First Name
5. Click Submit
6. Check the console for the value of Last Name

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usewatch-bug-r9qj9

**Expected behavior**
The value returned from `useWatch` should be the current value of the field.

**Screenshots**
![image](https://user-images.githubusercontent.com/18226415/115952462-ae23d180-a503-11eb-849a-e5da3fb4e303.png)

**Desktop:**

- OS: Windows 10
- Browser Chrome
- Version 90

**Comment by manzoorwanijk** [comment]
The issue is still not fixed. 😢 I guess the problem is with nested fields.

Sandbox: https://codesandbox.io/s/react-hook-form-usewatch-bug-731-beta0-b6k6x

Steps:
1. Submit the form once
2. Change the value of only the First Name
3. Now submit again
4. Check the value of First Name in console, it's `undefined`

![image](https://user-images.githubusercontent.com/18226415/115958112-ae33c980-a523-11eb-90af-7c9c099f339b.png)

**Comment by bluebill1049** [comment]
I think the problem is reset within handleSubmit callback, this is what doing in the code

1. onSubmit 
2. handle submit 
3. pass validaton
4. callback(
  updateState( // internal 
    reset()
  )
)

The correct order should be the following:

https://codesandbox.io/s/react-hook-form-usewatch-bug-731-beta0-forked-l4flr?file=/src/App.js:431-484

1. onSubmit 
2. handle submit 
3. pass validaton
4. callback(
  updateState() // internal
)
5. reset()

which is also the example in the doc:
<img width="961" alt="Screen Shot 2021-04-24 at 10 21 52 pm" src="https://user-images.githubusercontent.com/10513364/115958613-7b053080-a54b-11eb-951c-b36650ab8ae8.png">

**Comment by manzoorwanijk** [comment]
Aha, that fixed the issue. Thanks.
