### ISSUE TITLE
getValues is empty or with default values on component unmount

### ISSUE THREAD

**Issue by Grimones** [react-hook-form/react-hook-form#494]
Hey! Thanks a lot for this amazing lib. That's what i was waiting for since hooks were released :)
I've easily migrated forms from redux-form and formik to react-hook-form but faced one issue.
So I've spotted a bug or maybe that's how it should work. I have few forms which have like 5-6 fields in common. You could type in one form, accidentally close, or decided to switch to other form - all values you've entered were saved and new form was initialized with that values. Before I've got in parent component which renders all these forms a `useState` to save form values
```js
const [savedValues, saveValues] = React.useState({})
```
Forms are rendered in modals and when I was closing the modal I was calling `saveValues` in return function of `useEffect`. Next time opening the form, values from `savedValues` were spreaded into initialValues of form.
In react-hook-form I've found out that when you do like this
```js
React.useEffect(() => () => {
  console.log(getValues());
}. []);
```
it is returning an empy object or default values if set.

[Here is a reproducible example](https://codesandbox.io/s/react-hook-form-basic-q3r7u?fontsize=14 )

**Expected behavior**
`getValues` should return the last values

**Additional context**
I've checked the sources and it seems that unmount and cleaning order should be different
https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L948
https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L647
https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L465

Found out an adhoc solution - watch needed fields and save everything in ref. When unmount - get values from ref. Not very optimized because it will rerender form on every keystroke of watched fields

https://codesandbox.io/s/react-hook-form-basic-48z70?fontsize=14

**Comment by bluebill1049** [comment]
Thanks @Grimones :) and your detailed issue report.

> it is returning an empy object or default values if set.

This is actually by design, because `getValues()` suppose to get everything on the form. 

`<input name="test" defaultValue="test" />`

by running `getValues()`, it should return what's in the default value and hence this should apply the same to `useForm({ defaultValues: { test: 'sdf' }})`

in terms of return `{}`, it's by design as well, because I don't want to break your app when you running `getValues().test`.

I am looking at your example now and try to understand the problem.

**Comment by bluebill1049** [comment]
Ok, I think I see the problem here. I think you are calling `getValues()` late*.

I would suggest you call it during the onClick event before all the inputs get removed from DOM.

**Comment by Grimones** [comment]
My apologies for the confusion :) forgot to add closure in `useEffect` in my first post. Updated.

Unfortunately that's not an option for me because I don't have by designs an option for user to save form values. 
But I found a better solution rather than using `watch` and it doesn't feel like an Adhoc, I guess :) 

So the idea is to put unmount `useEffect` before `useForm`. Because in hooks order matters, the first `useEffect` would run before `react-hook-form` would run his own unmount `useEffect` cleaning the values. But we need to save reference to the `getValues`. 

That's how it looks

```js
const getValuesRef = React.useRef(null);

React.useEffect(() => () => {
  if (getValuesRef.current) {
    console.log(getValues.current());
  }
}, []);

const { register, handleSubmit, getValues } = useForm();

// Save getValues reference on each rerender
React.useEffect(() => {
  ref.current = getValues;
});
```

Here is a [working codesandbox](https://codesandbox.io/s/react-hook-form-basic-s4ckd?fontsize=14)

I think it'll be good if we can add this to examples or FAQ on website because it's a valid and widely used usecase so other people can easily find it.

**Comment by bluebill1049** [comment]
aha awesome! glad you work it out. I will move it into the advanced section later. This answer can help others too :)  thank you <3

**Comment by omikulcik** [comment]
React warns you that variable was used before it was defined so maybe a different implementation would be apropriate

**Comment by allicanseenow** [comment]
@bluebill1049 Also regarding the example in this question, is it necessary to put `getValues` as one of the dependencies of the `useEffect`? Does it mutate and does a field value rely on the mutation of `getValues`?

**Comment by bluebill1049** [comment]
hey @allicanseenow can you share more code context? i should be fine to put it as dep tho.

**Comment by allicanseenow** [comment]
Thanks for your response. I mean like just in the general context that was mentioned in the OP's question:
`
React.useEffect(() => () => {
  console.log(getValues());
}. []);
`
Here in the dependency, should I be worried that omitting getValues() might cause some kinds of bugs due to the mutability of the function? A rule of thumb from the React team is you should always put everything you have in `useEffect` function inside its dependency list. However, from my experience of working with React hooks and functional components, some devs declare functions inside a functional component without wrapping them in `useCallback`. This can potentially trigger unneccesary re-rendering that affects the performance. But if I omit something from the dependency list, the value inside that `useEffect` might not be the latest value set inside the functional component. For example:

`
const [aVar, setAVar] = useState()
React.useEffect(() => () => {
  console.log(aVar);
}. []);
`
If `setAVar` is called and `aVar` is not in the dependency list, the value the console.log() will no longer be accurate.

**Comment by bluebill1049** [comment]
@allicanseenow I think you should put those methods as dep, and if that trigger unnecessary re-render, you can always useCallback or useMemo them.

**Comment by allicanseenow** [comment]
Would you mind showing a simple code sample that I can reference from?

**Comment by bluebill1049** [comment]
```
useEffect(I() => {
  register('test')
}, [register])

const test = useMemo(() => data, [data]) // data from external api

useEffect(() => {
  console.log(data)
}, [data])
```

@allicanseenow

**Comment by allicanseenow** [comment]
@bluebill1049  By `register`, did you mean `getValues` instead?

**Comment by bluebill1049** [comment]
yes @allicanseenow any API from react-hook-form

**Comment by klawingco** [comment]
Oh god I was dumbfounded since a normal effects works at development, but I got the exact Issue when in Production.

Thanks @Grimones , I got it working, though I wrote a  small hooks to avoid duplication of codes.

Hereis the hook, usePersist

```
const usePostPersist = onFormUnMounting => {
  const getValuesRef = useRef(null)
  // Save RHF data when form is unmounted
  // Used to persist data when switching post Data
  useEffect(
    () => () => {
      const values = getValuesRef?.current && getValuesRef?.current()
      if (onFormUnMounting && values) {
        onFormUnMounting(values)
      }
    },
    []
  )
  const setGetValuesRef = getValues => {
    getValuesRef.current = getValues
  }
  return setGetValuesRef
}

```

Then I can just used it on any page that I need it like this
```
  const setGetValuesRef = usePersist(onFormUnMounting)
  const {
    register,
    handleSubmit,
    errors,
    control,
    reset,
    getValues,
  } = useForm({
    mode: 'onSubmit',
    resolver: yupResolver(mySchema),
    defaultValues: {},
  })
  useEffect(() => {
    setGetValuesRef(getValues)
  })

```
Then I can reuse this logic, without putting many codes that do similar.

Thanks a lot again

**Comment by T41WO** [comment]
> onFormUnMounting

Any explanation as to why this would work on a local development environment but not in a production one?

**Comment by klawingco** [comment]
@T41WO Sadly I haven't got the root issue on why, Normal Effects works on my development but not when I built the pages in Production mode. The only thing I can think that can factor of is because I am using NEXT.

**Comment by T41WO** [comment]
This is very strange.

Using Create-react-app with typescript and having the same issue.. Even strange is I have 3 files with similar implementation, 2 out of 3 is not working as expected in the non-local dev environment.

**Comment by Anatoool** [comment]
I have the same issue with production mode.
