### ISSUE TITLE
useFieldArray + drag drop issues

### ISSUE THREAD

**Issue by JakeGinnivan** [react-hook-form/react-hook-form#5002]
**Describe the bug**

There is a really odd interaction bug between react-movable and react-hook-form. Swapping items ends up reverting the values.
Also when you go to drag it accesses a stale value. 

**To Reproduce**

Open code sandbox, add a second item, drag/drop to swap them. Or add 3 rows, then click swap (does nothing)

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker. I upgraded the v6 useFieldArray code sandbox to v7 and produced the issue there

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-2yxep?file=/src/index.js

**Expected behavior**

To be able to use react-movable with useFieldArray

**Screenshots**

![Kapture 2021-04-29 at 22 29 32](https://user-images.githubusercontent.com/453152/116567715-76b98880-a93a-11eb-84c0-81c1b54eb3bc.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser FireFox 
- Version 88

**Additional context**

I thought i'd report the issue, happy to manage the state outside the form but would be good to understand what is happening

**Comment by BTiers** [comment]
Hi @JakeGinnivan !

I believe your issue comes from the fact that the `props` that `react-movable` give you inside of the `renderItems` function includes a `key` as well, so when you're spreading then to the `li` element, it overrides the one that you gave before.

So basically, you can modify your code to be something along the lines of:
```jsx
renderItem={({ value, props, isDragged, isSelected, index }) => {
  const { key: _, ...withoutKeyProps } = props;

  return (<li key={value.id} {...withoutKeyProps}>...</li>);
```

Hope it help :)

**Comment by leapful** [comment]
@JakeGinnivan 

The root cause of wrong value after moving item is caused by "key" prop like @BTiers pointed out. 

By default, react-moveable will update directly DOM element position to show drag and drop effect then delegate to "renderList" and "renderItem" to perform the real re-rendering with React. But because the prop "key" value has been overridden by item index (from 0 to 2 in the sample, React will keep using the old order.

The second issue of stale value when dragging is caused by drag handling from react-moveable. The library will clone the drag element by using same props data of the original element. At that time, only default value of original element (input fields) is available, the current value of those input fields is stored inside the DOM reference of original element and cannot be used in a new cloned element.

The workaround is to use method "getValues()" from react-hook-form in order to get current value in case "isDragged" = true.

Working sample: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-yvub3?file=/src/index.js

**Comment by bluebill1049** [comment]
Thanks very much @leapful for the investigation. Drag and drop is always something hard to manage with external library and depend on how they implement it.

**Comment by JakeGinnivan** [comment]
That worked beautifully, thanks heaps for the help!

**Comment by JakeGinnivan** [comment]
The second issue I would not have got, I was trying to fetch the value in the render method of the Controller for the drag item. I needed to do it outside and provide the defaultValue.
