### ISSUE TITLE
useFieldArray (and useController) should allow specifying value type constraints

### ISSUE THREAD

**Issue by mayorandrew** [react-hook-form/react-hook-form#5055]
**Is your feature request related to a problem? Please describe.**
In our project we have several different forms which have a field represented by an array of objects with specific type.
We have created a reusable React component to edit this arrays, basically a custom field (in abstract sense).
This component accepts `control` and `name` properties and uses `useFieldArray`.

Because this component is generic, we can not infer the value type from `FieldValues` since the specific schema of `FieldValues` is unknown at that point. 
But our component expects `fields` returned from `useFieldArray` to have specific type.
Currently typings in `react-hook-form` do not provide sufficient capabilities, and we have to rely on manual type casting via `field as unknown as MyType`.

Note that this is only a type system problem, javascript code works fine.

[See the example in CodeSandbox](https://codesandbox.io/s/react-hook-form-use-field-values-generic-problem-oi5qz)

This problem also arises for simple custom fields when we use `useController` hook. 
For example, if we have a custom text field, we would like to restrict value type to be `string`.

[useController exampe in CodeSandbox](https://codesandbox.io/s/react-hook-form-use-controller-generic-problem-dcp3s?file=/src/App.tsx)

**Describe the solution you'd like**
The solution I envision consists of two parts:
1. We need to allow specifying type constraints in `FieldArrayPath` and `FieldPath` so that when defining custom field components we could restrict `TFieldArrayName` and `TFieldName` to extract only those paths which have the desired type. This would allow for type safety for users of our custom field component in concrete forms.
2. Hooks `useFieldArray` and `useController` should allow for custom type specification for cases where concrete shape of `FieldValues` is unknown. This could be a third type argument which defaults to `FieldArrayWithId` / `PathValue`. This would allow for type safety inside our custom field component.

These two parts work together to ensure complete type safety given that we correctly specify the same custom type constraint in both of them. 

If we only have the first part of the solution, typescript is not smart enough to extract the correct value type when using the `useFieldArray` or `useController` hooks.

Here is the CodeSandbox with some of the library types changed which kinda shows the complete solution:
https://codesandbox.io/s/react-hook-form-use-controller-generic-33yo5

**Describe alternatives you've considered**
No other API in `react-hook-form` seems to provide the desired functionality for custom field components.

**Comment by bluebill1049** [comment]
cc @kotarella1110

**Comment by MonsterDeveloper** [comment]
Hey! I've just encountered almost the same problem. I am creating a custom input component, and I want to restrict the field name, so it
1) exists in T (form interface)
2) the type of the field name in T is either A or B (can't figure this out now)

This is what I came up with for now:
```tsx
interface Props<T, TName extends FieldPath<T> = FieldPath<T>> {
  name: TName;
  control: Control<T>;
}
```
However, this only makes sure that TName exists in T...

**Comment by diracs-delta** [comment]
I've encountered this too. It's pretty difficult to debug because there is a fair amount of TypeScript wizardry that is involved in the `Path<T>` and `PathValue<T>` generic type definitions. 

I think a good direction to look into is the definition of `TFieldPath` type parameter (i.e. the second one in `Control`, `useController`, `UseControllerReturn`) has a specific field value, specifically how to optimize the definition of `PathValue<Path<T>>`.

For example: I have a `CloudFileField` component that renders a file upload field, and propagates an object of `CloudFile` type back to the controller. In an ideal world, I should be able to define:

```
type CloudFilePath<T> = PathValue<T, Path<T>> extends CloudFile ? Path<T> : never;

type CloudFileFieldProps<Form, CloudFileFieldKey extends CloudFilePath<Form>> = {
  controller: UseControllerReturn<Form, CloudFileFieldKey>;
}
```

What this type definition **should** say is "hey, the controller you're passing to me as a prop should have a `CloudFile` type and nothing else! Otherwise, throw a type error because I should never receive anything but a `CloudFile` controller!"

But sadly the built-in type definitions are a bit too complex for TypeScript to infer that `Form[CloudFileFieldKey] == File`. 😢

**Comment by bluebill1049** [comment]
update: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.18.0-next.0

**Comment by MonsterDeveloper** [comment]
Wow, that’s some great news! Looking forward to trying this feature!
9 окт. 2021 г., 09:34 +0300, Bill ***@***.***>, писал:

**Comment by bluebill1049** [comment]
will resolve and improve this in v8

https://github.com/react-hook-form/react-hook-form/discussions/7354
