### ISSUE TITLE
Include default values for field arrays

### ISSUE THREAD

**Issue by ccheney** [react-hook-form/react-hook-form#5056]
**Describe the bug**

When injecting default values into `useForm` which include field arrays that data doesn't seem to be collected `onSubmit`

**To Reproduce**

1. Go to Sandbox link below
2. Click on Submit
3. Note the form data in the console does not include default value data for the field array `items[]`

**Codesandbox link**

https://codesandbox.io/s/old-voice-wv5lh?file=/src/App.tsx

**Expected behavior**

The default values within the field array are included with the form data

**Desktop:**

- OS: macOS 11.3.1
- Browser Chrome
- Version 90.0.x

**Additional context**
A workaround for this would be to set the data on a series of hidden fields in a `fields.map()`, see sandbox for an example of this

**Comment by bluebill1049** [comment]
let me explain:

`defaultValues` was meant to be the initial value for all the inputs, it's actually not the default state for the form. However, most users request to have `defaultValues` as part of the submitted value, so we are doing a shallow merge to include them in the form values. As my personal preference, I prefer `defaultValues` as what it intended to be, again it's a community-driven project and I should listen to feedback. so why it's not working, because `useFieldArray` by default will create field value as empty [], and when you have nothing `registered`, the value will be remained as `[]` and hence the shallow merge leads to taking the `[]`.

**workaround** 

- obviously, let's the `fields` map and do its thing as that's what useFieldArray was made for form. (which is what you had in your CSB)
- register the root input at `useEffect`

```
React.useEfffect(() => { register('fieldArray') }, [register])
```

this way at least useFieldArray there are inputs getting registered

hope above make sense.

**Comment by ccheney** [comment]
Yep, makes perfect sense. I assumed it was a shallow merge issue here but was unsure if that was intentional since the other top-level default values _are_ included, even w/o any additional field registration (e.g. `id` in my CSB).

Thanks for your explanation 👍
