### ISSUE TITLE
`useWatch` is unhappy when used with `useController` in `useFieldArray` item (`shouldUnregister: true`)

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#5162]
**Describe the bug**
I'm using the 4 combo of: `useWatch` + `useController` + `useFieldArray` + `shouldUnregister: true`, found 2 unexpected behaviors when inserting-removing item that cause crucial bugs in my project. Please refer to the section below for more details (finally I can create a minimal reproducible CSB after fiddling for hours! 😄).

**To Reproduce**

1. Go to the below CSB link.
2. Click on 'insert' button of the second item ("test1").
3. See the value of the inserted item. **➜ unexpected "test2"**
4. Now, click on 'remove' button of the inserted item = the third item.
5. See buggy `useWatchedItems` array in the console. **➜ unexpected array length / containing only 2 items**

**Codesandbox link (Required)**
https://codesandbox.io/s/usewatch-is-unhappy-with-usecontroller-77v3i?file=/src/App.jsx:1536-1573

**Expected behavior**

- In step (3), the value of the inserted item should be "testx" instead of "test2".
- In step (5), the `useWatchedItems` array should contain 3 items instead of 2 items.

**Comment by bluebill1049** [comment]
thanks @dwiyatci i will look into that.

**Comment by tquocan** [comment]
@dwiyatci @bluebill1049 

1. The first issue where inserted item value should be "testx" instead of "test2" is caused by wrong setting "defaultValue" at line 77.
2. The second issue of "useWatchedItems" is caused by the setting "shouldUnregister: true" at line 17.

After inserting new item "testx", the field array name is now:

```
["items.0.prop", "items.1.prop", "items.2.prop" => new item "testx", "item.3.prop"]. 
```

When removing new item "testx" with "shouldUnregister: true", the watch subscription will remove subscriber on "items.2.prop", but at that time, the "items.3.prop" value will be re-rendered at "items.2.prop" which is now ununscribed and cannot be shown in "useWatch" hook.

Remove "shouldUnregister: true" will fix the issue.

Working sample: https://codesandbox.io/s/usewatch-is-unhappy-with-usecontroller-forked-ruxgc?file=/src/App.jsx

**Comment by bluebill1049** [comment]
Thank you so much for the investigation @tquocan ❤️ 

This is a tough one due to `shouldUnregister` set true which leads to input will get removed during shuffling, I think of a patch to set a flag during shuffle action, this is one of the weaknesses when set `shouldUnreigster` to true for `useFieldArray`. It normally works much better with `shouldUnregister: false `, however, I will come up with a patch or enhancement tonight.

**Comment by dwiyatci** [comment]
@tquocan Oh my gosh, thank you so much for catching the first one!! I believe I didn't see/think so clearly last night. 😅  As for the `shouldUnregister: true`, yeah sorry, I need it badly in my code and removing it is not an option for now.

@bluebill1049 Thank you for your endless support, as usual, Bill. I'll be sure to quickly giving it a spin again tonight. Cheers! 🍻
