### ISSUE TITLE
Some definitions are not exported

### ISSUE THREAD

**Issue by yi-tuan** [react-hook-form/react-hook-form#536]
My project needs definitions like `ValidationOptions` 、`FieldError` and so on, but they are not exported

**Comment by bluebill1049** [comment]
This probably one of the mistakes that I did during the API design. I should have exported everything out instead make life easier with useForm... (import useForm from '...') I am planning for the next major change to export everything.

instead of this: 

```
export { default } from './useForm';
export { FormContext, useFormContext } from './useFormContext';
```

```
export * from './useForm';
export * from './useFormContext';
export * from './types';
```

well, this is going to be a breaking change, unless you have a better solution for now. otherwise, we have to live with this for awhile until we release a major version update.

**Comment by bluebill1049** [comment]
hey @yi-tuan I am closing this issue, for now, we will address this in v4, otherwise, let me know if you have any alternative solution for the current version.
