### ISSUE TITLE
useForm setValue strange behaviour with arrays

### ISSUE THREAD

**Issue by njarraud** [react-hook-form/react-hook-form#5533]
**Describe the bug**
setValue doesn't seem to save arrays correctly.

**To Reproduce**
See codesandbox example below.

1. Open the console. It shall display ["div1", "div2", "div3"]
2. Click on the "x" next to "div1". It is supposed to remove the item.
3. The console displays ["div2", "div3", "div3"] when it shall be only ["div2", "div3"]

**Codesandbox link (Required)**
[https://codesandbox.io/s/hardcore-framework-y1j09?file=/src/App.tsx](https://codesandbox.io/s/hardcore-framework-y1j09?file=/src/App.tsx)

**Expected behavior**
SetValue doesn't overwrite the array. On the example, it looks like it is shifting the array to the left and keeping the element after unchanged.

**Screenshots**

**react-hook-form version**
7.8.2

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by bluebill1049** [comment]
`defaultValues: { divisions: ["div1", "div2", "div3"] },`

## Reason

because you don't have any input, react hook form will register those values into 3 inputs. 

- div1 
- div2
- div3

## What happened

setValue will not be able to remove nodes rather only update them.

`setValue('divisions', ['1', '2'])`

This leads the last node `div3` to stay as it is.

## Solutions

- have real inputs 
- set `shouldUnregister: true`, so hook form doesn't register those inputs for you.
