### ISSUE TITLE
Adding/removing fields to form triggers rerender for all controlled fields in form

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/react-hook-form#5591]
**Describe the bug**
Performance wise, correct me if I'm wrong - when using only `control` without `FormProvider`, `useController` should only be rendered for the changes regarding the specific field name its subscribed to.
Regarding that assumption, I'd expect that when other fields are removed/added, the component with `useController` won't be rerendered.

Following that introduction, I noticed that:
1. Unregistering a field from form will cause all components using `useController` to rerender (either manually or with shouldUnregister).
2. Appending or removing fields from array field triggers rerender all components using `useController` (including fields that are not inside the array)

**To Reproduce**
The rerenders can be either noticed by the `console.log` in `ControlledInput` or by the react dev tools profiler `Highlight updates when components render.` option (I assume it will be necessary to download & install the repo to view these highlights)

1. Go to CSB
2. Click on the 'Add' button to add controlled input to array field, and on 'Remove' to remove the controlled input from array, do it couple of times and notice the 'firstName' 'lastName' fields rerendered.
3. Click alternatively on 'toggle' button to add/remove controlled input to the form top level

**Codesandbox link (Required)**
https://codesandbox.io/s/elastic-breeze-oy4so?file=/src/App.tsx

**Additional context**
I opened this discussion https://github.com/react-hook-form/react-hook-form/discussions/5569 which has further context
The form I build with react-hook-form is huge and dynamically manipulated (add/remove/change dozens of fields), therefore I'm consistently trying to find ways to improve the performance consequence.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue.

- Unregistering a field from form will cause all components using useController to rerender (either manually or with shouldUnregister).

hook form will need to flush a root re-render due to all the potential formState update, it's really doing a lot more than just remove the value.

- Appending or removing fields from array field triggers rerender all components using useController (including fields that are not inside the array)

This can't be avoided, because each action will lead inputs to get re-mapped again.

hope the above makes sense.
