### ISSUE TITLE
Native browser validation doesn't work with useController

### ISSUE THREAD

**Issue by Pitbi** [react-hook-form/react-hook-form#5712]
**Describe the bug**
I can't get the native browser validations to work with `useController`. It works fine with `useForm` & `register`.
For example, I see that `required: true` is not setted to` field` which is returned by `useController(props)`. See line 7 on my codesansbox.

**Codesandbox link (Required)**
https://codesandbox.io/s/usecontroller-forked-tf7s1?file=/src/App.js

**Expected behavior**
I would like, for example, to see the browser validation for a required field.

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser: chrome
- Version: 91.0.4472.106

**Comment by bluebill1049** [comment]
For native validation, we won't implement for `useController` for now unless there are a lot of demands out there. you can send a separate feature request.

## Why

because for `useController` we don't store input's ref (the same way as `register`)

I will update doc for the above information to highlight we don't support controller/useController at the moment.

**Comment by bluebill1049** [comment]
I will take a look at this after work, in case there is an easy solution to this.

**Comment by Pitbi** [comment]
Thx! :)
