### ISSUE TITLE
Return type of `watch` is `unknown`

### ISSUE THREAD

**Issue by axelboc** [react-hook-form/react-hook-form#576]
**Describe the bug**
The return type of `watch('fieldName')` is `unknown`.

**To Reproduce**

https://codesandbox.io/s/long-hill-p1cyi

```tsx
interface FormData {
  myField: string;
}

function MyForm(): JSX.Element {
  const { watch } = useForm<FormData>({ defaultValues: { myField: 'foo' } });
  
  const myFieldValue = watch('myField');
  // `myFieldValue` has type `unknown`
  // workaround required: `watch('myField') as string`

  return ...
}
```

**Expected behavior**
The return type of `watch` should be the type of the given field's value.

**Context**
 - `react-hook-form` version: 3.28.3
- TypeScript version: 3.7.2
- Strict typing enabled

**Comment by bluebill1049** [comment]
can you provide a TS codesandbox for this issue?

**Comment by axelboc** [comment]
I've updated the issue 👍

**Comment by bluebill1049** [comment]
thanks @axelboc after looking closely unknown is actually right because it's a run-time check there is no way (with my knowledge) to give a type other than `unknown`. Feel free to contribute or giving your suggestion tho. eg:

```
watch('test.data')
watch('test[0].test')
```

with my limited knowledge on typescript, i couldn't figure out how to support type with `watch` other than `unknown`.

**Comment by axelboc** [comment]
The following works for simple field names, but I haven't tested it with complex ones like `test[0].test`:

```ts
function watch<T extends FieldName<FormValues>>(field: T, defaultValue?: string): FormValues[T] { ... }
```

**Comment by bluebill1049** [comment]
would love to a PR if you have sometimes 👍 TS is not my strength :(
