### ISSUE TITLE
Validation error focus state for checkboxes/radios

### ISSUE THREAD

**Issue by raulfelix** [react-hook-form/react-hook-form#581]
**Describe the bug**
Form validation will refocus on an input field if no value is entered. But this does not work for a checkbox or radio control. 

**To Reproduce**
1. Press submit and focus will go back to the first text field
2. Fill in the text field
3. Press submit
4. There will be a validation error on the checkbox field but it will not grab focus

**Codesandbox link**
https://codesandbox.io/s/objective-kirch-uz0e6?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Focus should be placed back on to the radio or checkbox group if this is the next top most error in the form.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser [chrome, safari]
 - Version [lastest]

**Comment by bluebill1049** [comment]
hey @raulfelix ❤️ that's a good pick up! will resolve that soon :)

**Comment by karenling** [comment]
Sorry for bringing up an old thread. I'm currently using v6.9.2, and noticed that I wasn't getting an error focus on checkbox inputs, and then I found this thread. 

It seems it was fixed in [v3.28.8](https://github.com/react-hook-form/react-hook-form/releases/tag/v3.28.8), but even on that version, it doesn't seem to focus on the checkbox.

**CodeSandbox Link**: https://codesandbox.io/s/jolly-shamir-rx2iu (I forked raulfelix's CodeSandbox and just changed the version). I also tried it with v.6.9.2 and the most recent beta (v6.10.2-beta-2).

Here's a GIF of the behavior I'm seeing as well:

![focus](https://user-images.githubusercontent.com/4053800/98334804-9047cc00-1fb8-11eb-9a94-8bd5a5a1c757.gif)

At the end of the GIF, I changed the checkbox into a text input just to show that the error focus is being triggered when it's a text input.

Not sure if I'm doing something wrong or misunderstanding the focus behavior. Thanks!

**Comment by bluebill1049** [comment]
@karenling it's actually focused correctly if you try to tab with a space key when an error.

**Comment by karenling** [comment]
@bluebill1049 Can you clarify what you mean by "tab with a space key"? I understand that I can tab and use the space key to check/uncheck, but I'm still not seeing that the error triggers a focus.

![tab space](https://user-images.githubusercontent.com/4053800/98349723-38688f80-1fcf-11eb-8b7f-763288f19865.gif)

**Comment by bluebill1049** [comment]
- change your CSB to the latest version
- only fill the first textbox
- hit submit
- press space key

**Comment by karenling** [comment]
Ah, thanks! Strange that the focus outline isn't visible, but seems like it's a Chrome-specific behavior. Just tried it out in Safari and Firefox and the outline appears.
