### ISSUE TITLE
setFocus not working with MUI TextField

### ISSUE THREAD

**Issue by cargallo** [react-hook-form/react-hook-form#5947]
I'm trying to use setFocus with MUI TextField. It seems that when you spread the properties of field it gets in conflict with inputRef property of MUI Textfield

**Codesandbox link**
https://codesandbox.io/s/setfocus-forked-oggot

The sandbox is working with the trick I made, but if you erase the code marked in red and it stops working. 

![image](https://user-images.githubusercontent.com/13320290/125670181-c4d1a534-453c-43cb-afec-2e7caf15eb00.png)

**Comment by bluebill1049** [comment]
that's expected, you will have to change the prop name.

```tsx
inputRef={field.ref}
innerRef={field.ref}
```

deepened on the UI libaray.

**Comment by cargallo** [comment]
Hi @bluebill1049 tnx for the response. I ended up doing this. InnerRef doesn't exists in MUI TextField. The question is why the spread of {...field} invalidates inputRef?

![image](https://user-images.githubusercontent.com/13320290/125708327-0cb98982-d352-40f3-abf4-87e37c648eff.png)

**Comment by bluebill1049** [comment]
no worries @cargallo 

because `field` contains `ref`

so what happened is


```
<TextField ref={ref} />
```

and this `ref` is not really a `ref`, that's why you need to change the name of the prop. On top of that, the only reason we need that ref of textField is just focus, I know it's fracturing when UI library has a different `ref` name, but there is little we can do as a library, we had the idea to build adapter but it's even more confusing.

**Comment by cargallo** [comment]
I will try to make time and create an example sandbox with full managment of MUI components with setFocus and other stuffs. Tnx!

**Comment by thachsteven** [comment]
> ref={ref}

Thank you very much. It's work for me
