### ISSUE TITLE
Wrongly sets `isDirty` upon blur when empty array field exists

### ISSUE THREAD

**Issue by dlindenkreuz** [react-hook-form/react-hook-form#5970]
**Describe the bug**
When using `reset` to set default values including an empty array and triggering a blur event, `isDirty` is true although it shouldn't be.

This does **not** happen when not using `reset` and instead passing the default values directly to `useForm({ defaultValues })`.

This also does **not** happen when adding a field to the field array, then removing it again, even though `reset` was used before.

**To Reproduce**
1. In the codesandbox, focus the input
2. Click somewhere else without changing the value
3. Form is dirty (bug!)
4. Click "add"
5. Enter a value in the new input
6. Click "clear"
7. Repeat Steps 1-2 -- form is not dirty (as expected!)

**Codesandbox link (Required)**
https://codesandbox.io/s/keen-nash-zef2f?file=/src/App.js

**Expected behavior**
The form should not be dirty if none of the values have been changed.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox, Safari, Chrome
- Version: 89, 14, latest

**Additional context**
- react-hook-form@7.11.0

**Comment by bluebill1049** [comment]
thanks for the detailed issue report.

https://react-hook-form.com/api/useform/formstate

> Make sure to provide all inputs' defaultValues at the useForm, so hook form can have a single source of truth to compare whether the form is dirty.

<img width="881" alt="Screen Shot 2021-07-16 at 8 59 34 pm" src="https://user-images.githubusercontent.com/10513364/125937761-99f98890-7a49-43e1-829b-104cf42487ed.png">

**Comment by dlindenkreuz** [comment]
In the sandbox, I added `defaultValues` with the same shape to `useForm`. When using `reset` afterwards, the form still sets itself to dirty.

I would expect that I can use `reset` to update the defaults, e.g. after loading from the api, and everything would still work.

Could you please take another look at the codesandbox?

**Comment by dlindenkreuz** [comment]
@bluebill1049 could you reopen this issue? It seems like this does not work as designed.

**Comment by bluebill1049** [comment]
This is not an issue. You are reset the whole form include the `defaultValues`, if you want to keep `defaultValues`, use the option `keepDefaultValues`.

read the doc under reset
https://react-hook-form.com/api/useform/reset

<img width="975" alt="Screen Shot 2021-07-23 at 6 09 44 pm" src="https://user-images.githubusercontent.com/10513364/126754387-97e59e6e-f045-4696-9ec7-874ea3af2595.png">

**Comment by dlindenkreuz** [comment]
Using `reset(..., { keepDefaultValues: true })` does not fix this (and neither does `{keepDefaultValues: false}`). I'm still getting this unexpected behavior:

> 1. In the codesandbox, focus the input
> 2. Click somewhere else without changing the value
> 3. Form is dirty (bug!)

Maybe there's a misunderstanding? It would be great if you could fork the Codesandbox above and add your suggestion there.

**Comment by bluebill1049** [comment]
I see your problem now, the issue is because you don't have an input that is registered as `foo`, the initial mount works because the hook form has registered those absents on your behalf. however, reset will push the value down to your view again and there are no such inputs; hence, the deep equal with dirty fields failed.

### Work around

always try to register your missing inputs from `defaultValues`, in your case if you have `register` that `foo` at useEffect, this issue should be resolved.

### What's next?

This PR should resolve this issue: https://github.com/react-hook-form/react-hook-form/pull/5958 but it still needs some work before it gets released, I suggest you follow the workaround bove.

Here is a codesandbox with above PR.
https://codesandbox.io/s/inspiring-euler-ouj0u?file=/src/App.js
