### ISSUE TITLE
[7.11.1] Incorrect type inferrence of Controller.defaultValue

### ISSUE THREAD

**Issue by thanh-nguyen-95** [react-hook-form/react-hook-form#6015]
**Describe the bug**

`Controller.defaultValue` type is inferred as `undefined` when the field itself is optional or nullable.

I'm not sure if this is a bug or not. Could be an issue related to TypeScript itself. I've tried downgrading RHF to older versions (7.10.x, 7.9.x, 7.8.x) but it didn't work.

**To Reproduce**

1. Open CSB and check type error

**Codesandbox link (Required)**

https://codesandbox.io/s/quirky-night-f3iso?file=/src/App.tsx

**Expected behavior**

`defaultValue` type is inferred correctly for nullable/optional field when using `Controller`

**Screenshots**

![image](https://user-images.githubusercontent.com/44762180/126256025-c59bc230-dcd5-4b4d-aa7b-4cfbd2677a75.png)

**Comment by bluebill1049** [comment]
I think this is a limitation with extending `null | undefined`

```
P extends `${infer K}.${infer R}`
  ? K extends keyof T
```

**Comment by bluebill1049** [comment]
> If you try to access a property of an object that may be null or undefined, you will get a type error.

This is expected behavior from @kotarella1110 

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9gJwLYDUCGAbArhAzlAXigG8BYAKCigDssMM0AjDCdbCALhroygB8SFKlQBmcOF1zAEAS2oBzIVAC+SuGGAy41TGxwB+LmUrDGaBF1pJGEBEtUmEEAI5YZTgCZ7Ogk1QDGiE7+wJLScvL83Na29hQOFIHUUlBiyN74RMTKUGj48OmYOLgA3BSJ2ilicISpiKhFeAB0tPRMLN5N1RXJwFBmCLVpDey4Teqa2rqNTQM9KYEIwX1EwxlNTq7uEF4zi8tAA

**Comment by kotarella1110** [comment]
Since there is currently no way to work around the type error, I will fix this.

**Comment by bluebill1049** [comment]
That's awesome!
