### ISSUE TITLE
Opt-in valueAsNumber for input type number

### ISSUE THREAD

**Issue by isBatak** [react-hook-form/react-hook-form#615]
**Is your feature request related to a problem? Please describe.**
When we have input type number we usually need to send a payload to API as a number, but it is always a string. Changing it inside submit handler is too late because we don't have information if the field is type number or something else.

**Describe the solution you'd like**
Add optional register rule `valueAsNumber`
```
<input
  name="age"
  type="number"
  ref={
    register({
      valueAsNumber: true,
    })
  }
/>
```
It could be handled here 
https://github.com/react-hook-form/react-hook-form/blob/4cce5d7583c5183a5f0f912268a42fc8ba30d509/src/logic/getFieldValue.ts#L31

something like this:
```
if (type === 'number' && field.valueAsNumber) {
  return ref.valueAsNumber; // or use parseFloat because of IE
}
```

**Additional context**
https://www.w3.org/TR/2011/WD-html5-20110405/common-input-element-attributes.html#dom-input-valueasnumber

**Comment by bluebill1049** [comment]
what about this idea? let it drive by your `defaultValues` 

https://react-hook-form.com/api#useForm

```
defaultValues={{
  number: 2, // we can use valueAsNumber,
}}
```

**Comment by isBatak** [comment]
Hmh, what if it's an optional field and you don't need a default value? 
Actually I haven't thought about that case. Currently, if the field is empty it will be set to "" (empty string), what should it be in case valueAsNumber is set to true 🤔 ... probably `NaN`

**Comment by bluebill1049** [comment]
> what should it be in case valueAsNumber is set to true 🤔 ... probably `NaN`

hmmm good point, this creates more unnecessary issues 🤔 

maybe i transform function of submitted data is better and safer.

**Comment by isBatak** [comment]
> maybe i transform function of submitted data is better and safer.

Sure, that could cover even more cases :D

**Comment by bluebill1049** [comment]
i guess we can do that during onSubmit
```
const onSubmit = (data) => {
  fetch({ url: 'xxx', body: yourTransformFunc(data)});
}

handleSubmit(onSubmit)
```

**Comment by bluebill1049** [comment]
going to close this issue, as it's better to solve at app level :)

**Comment by isBatak** [comment]
> Changing it inside submit handler is too late because we don't have information if the field is type number or something else.

Then we need to make something like this.
`convertFieldsToNumbers(data, ['age', 'price', ...])`
That seems redundant...

**Comment by bluebill1049** [comment]
Do you have a better suggestion? To be honest i dont think it's a redundant, more like a utility which you can reuse.

**Comment by isBatak** [comment]
It's redundant in terms when I change input type I have to update array, or when input name is changed I have to remember to update the array. 
If that is forgotten it could produce hard to debug issues. 
The transform function is a good idea, but it should be defined per input.
```
ref={
    register({
      trnsformValue: (value) => parseFloat(value),
    })
  }
```

**Comment by isBatak** [comment]
Is it OK to use `RHFInput` in this case?
```
<RHFInput
        as={<Input />}
        name="age"
        type="number"
        onChangeEvent={(value) => ({ value: parseFloat(option[0]) })}
/>
```

**Comment by bluebill1049** [comment]
oh yeah! @isBatak 100%

**Comment by polc** [comment]
FYI the same problem exist for date values. Some build-in solution may be nice !

**Comment by afzalsayed96** [comment]
Why not directly use the type attribute of the input element if it is explicitly specified by the user? Seems a lot intuitive and harmless IMO.

I have something very simple like below eg. and introducing a wrapper seems unnecessary and diverging from the neat philosophy of the library.

```
<input type="text" name="name" ref={register} />
<input type="number" name="number" ref={register} />
```

**Comment by bluebill1049** [comment]
> Seems a lot intuitive and harmless IMO.

@afzalsayed96 I disagree with above. Did you ever consider with `valueAsNumber` will return `null`? Personally i prefer to keep it as consistent as `string`, which is what the form natively return. If you want to return input as `number`, you can use `Controller` to specifically return `number`, other than that i don't think this lib should do any logic to convert `string` to `number`, `number` to `string`. keep it simple for everyone, all you have to remember is that form input will always return `string`. hope this make sense, the reason behind.

**Comment by afzalsayed96** [comment]
Thanks @bluebill1049
That seems fair. Could you explain how to use `Controller` with uncontrolled `input` element?

**Comment by bluebill1049** [comment]
@afzalsayed96 here is an example: https://codesandbox.io/s/awesome-hopper-bqr84

**Comment by afzalsayed96** [comment]
Thanks a lot!

**Comment by olup** [comment]
Just to add to the discussion here : I would love to get value as number when I have complex types (with typescript) that include numbers, passed as my form values types. Thing is, I need to duplicate all my interfaces that contain number so that they can get a string - just for the for part. It's a bit annoying.

**Comment by bluebill1049** [comment]
hey @olup understanding your concern. Take a look at this example: https://github.com/react-hook-form/react-hook-form/blob/master/examples/parseFormatInputValues.tsx

**Comment by elderapo** [comment]
I think this should be reopened.

1. Changing all normal numeric inputs to "controllerd" ones just to get correct input value type seems like an overkill and bad DX.
2. Parsing string value in `onSubmit` handler is not always an option because it's "too late". With custom validators, one might expect numeric input to be valid (worth further validation) only if the value is typeof `number` ex:

```ts
register({
  validate: v =>
    typeof v !== "number" ? "Invalid amount" : v % 2 !== 0 ? "Only even amounts are allowed!" : undefined,
});

```

Possible solutions:
1. Internally do `parseFloat` for inputs with type "number" and always pass numbers to the userspace.
2. Basically `1.` but make it opt-in with `valueAsNumber` for backward compatibility.
3. Add option in `register` function for custom transformer like:
```ts
register({
  transformValue: (value: string) => parseFloat(value),
});
```

**Comment by paambaati** [comment]
@bluebill1049 I tend to agree with @elderapo; and I'm leaning towards solution 3 — adding a custom `transformValue` option in `register`.

This leads to a vastly better DX, especially when working with large complex forms where you'd want to parse/cast form field values in different ways. Some examples I can think of —

1. Converting numeric input values to `Int` or `Float`.
2. Converting `<input type="date">` values to custom formats.
3. With this approach, I'd also not have to maintain 2 sets of types, because today, it looks like this - 

	```typescript
	type FormData = {
	    name: string;
	    age: string; // Because form will always return string.
	}
	```
	
	Then in my submit handler, I transform it to a `number`, after which the type for that JSON becomes - 
	
	```typescript
	type FormDataParsed = {
	    name: string;
	    age: number; // After being converted 
	}
	```

Would you entertain this if this is added to the [Feature Requests project board](https://github.com/react-hook-form/react-hook-form/projects/1#column-8642460)?

**Comment by bluebill1049** [comment]
Yea thanks @paambaati added.

Take a look at this folder: 

https://github.com/react-hook-form/react-hook-form/tree/master/examples

there is a code example in there: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc

if we introduce transform, then we will need a parser. it's just making API more heavy and things to learn. You can work around pretty easily with `onChange` and `value` with `Controller` or `onChange` and `defaultValue` with native inputs.

Keep APIs small is also something I emphasis a lot.

**Comment by jacknewberry** [comment]
Yup schemas already provide transform functionality. Yup can cast values at the same time as validation.
```ts
schema = yup.number().required()

castValue = schema.validateSync(data)
// if the data passed validation, castValue is now a number, otherwise an error was thrown.
```

Perhaps the existing `register({validate})` function could be used as a transform function.

**Comment by LEinfeldt** [comment]
I agree with @paambaati and @elderapo , wrapping the inputs in a `<Controller>` just to get a number is a lot of work in large forms.

Also your example:

> there is a code example in there: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-furtc
appear to me not to work properly.

Submitting the form returns a number, however after a change to the number input, I get a string again:
![image](https://user-images.githubusercontent.com/12085492/92213000-21080b80-ee93-11ea-9e33-fe03249ce06b.png)
Am I missing something there?

**Comment by adrid** [comment]
@LEinfeldt I've just created a [pull request](https://github.com/react-hook-form/react-hook-form/pull/2831) to fix that example

**Comment by baba43** [comment]
I really think that there should be an easy solution for this common problem. Actually, this has been the only real pain point for me so far.

In your docs, you state that one should specify additional fields (like the already existing id of an entity) as hidden input fields. If I do this, my numeric id becomes a string and I have to convert it before sending it back to the server. Not easy or intuitive at all.

Don't get me wrong. I love RHF and that's why I'm here to say that this is actually an important issue. Having to transform the whole form state before sending it to the server is just bad.

**Comment by stellarbear** [comment]
From my point of view transform is **not** an overkill for API and **not** bloating it at all.
This issue is doubling the pain for TS users: two pretty similar interfaces for handling data coming from 'react-hook-form' and data that is needed to be sent to the backend.

**Comment by bluebill1049** [comment]
Thanks for your guys' feedback. have you considered with this approach:

https://codesandbox.io/s/ecstatic-waterfall-yfsqe

**Comment by baba43** [comment]
> Thanks for your guys' feedback. have you considered with this approach:
> 
> https://codesandbox.io/s/ecstatic-waterfall-yfsqe

My question is if that is a workaround or a nice solution, because I thought that using `ref` is the suggested approach over using a `Controller`?

**Comment by bluebill1049** [comment]
> My question is if that is a workaround or a nice solution

I believe it's nice solution, it gives you the flexibility to convert value into any type that you required. This is probably one of the solution, you can probably do that with just register as well.

```ts
const InputNumber = () => {
  <input ref={register} onChange={() => setValue(name, parseFloat(e.target.value)} />
}
```

> because I thought that using `register` is the suggested approach over using a `Controller`

Yes, `register` it's the suggested approach, at the same time, native input return `string` as a default value, unless you are invoke `valueAsNumber` `valueAsDate`, however, those all have a unexpected result, eg: `valueAsNumber` will lead to `NaN`, this sort logic problem is better to let the user to decided the actual behaviour IMOH, i know many users would argue that this should be a build in functionality, however at the same time, i care about the API, size, perf and etc... don't think would add more functionality to `regsiter` than what we have today. on the other side, you can have all the functionality and build a monster form lib (15kB+), while this lib philosophe remain the same, RHF doesn't have to do everything for the user, but it leave primitive API, so they can compose and build thing on top of it.  I know this will defingely piss off some users, oh you should have this, that and etc, but RHF is special because the way it does form handling in react, the APIs(1 year plus we kept the same amount of APIs for users), bundle size and performance. 

Recently i did produce a video on Controller which giving example on extend functionality on top of Controller: https://www.youtube.com/watch?v=Vkiyg_KfNK4 again this goes the same idea, not introduced more API, but keep API primiteive so users can build component and compose their own recipes.

**Comment by stellarbear** [comment]
This solution is okay (in general) and working.

But i see 2 downsides:
1. It requires a bit more code than the "register" approach (of course much less than introduces 2 interfaces, but still it's more explicit). You have two options from here: convert everything to "controller" style or mix both code styles (which is not as ideal as it could be)
2. If there is an undefined value - errors will be logged to console (component changing from controlled to uncontrolled). And there it is not always easy to find a workaround for undefined value

**Comment by AkselAllas** [comment]
I agree with @stellarbear. 

@bluebill1049 aside from increased library size, what negative effect would implementing a custom transform function inside register bring?

For me using only register seems like the most elegant way to handle inputs, and I would really prefer not to use controller.

**Comment by bluebill1049** [comment]
I haven't forgotten about this issue :) here is my implementation

```tsx
<ControllerPlus<string, number>
  transform={{
    input: (value) =>
      isNaN(value) || value === 0 ? "" : value.toString(), // incoming input value
    output: (e) => {
      const output = parseInt(e.target.value, 10);
      return isNaN(output) ? 0 : output;
    } // what's going to the final submit and store
  }}
  control={control}
  name="number1"
  defaultValue=""
/>
```

going to include this into the doc for extending Controller section: 
https://codesandbox.io/s/ecstatic-waterfall-yfsqe?file=/src/App.tsx:1759-2164

**Comment by ilkeryilmaz** [comment]
Thanks 🚀  @jacknewberry

**Comment by ViieeS** [comment]
Why just not using native html API. type="number" attribute is all we need to receive number IMO...

**Comment by bluebill1049** [comment]
> Why just not using native html API. type="number" attribute is all we need to receive number IMO...

Read the doc... https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Comment by ViieeS** [comment]
@bluebill1049 ok, sorry, I used to leverage Angular directive magic...

**Comment by bednar85** [comment]
@bluebill1049 Is it possible to add custom increment/decrement buttons that update your `<NumberInput />` implementation from [CodeSandbox](https://codesandbox.io/s/ecstatic-waterfall-yfsqe?file=/src/App.tsx:274-285)? I was trying to setup a version like that but I'm not able to get it to work.

**Comment by bluebill1049** [comment]
@bednar85 i think you can use `setValue` API to achieve that.

**Comment by bluebill1049** [comment]
looks like there are so many developers after this feature, I think perhaps I should do and listen to what everyone desired.

anyway enough said, here is the proposal for the API, still going to follow HTML standard:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

Note the following will only work for the input element, not textarea.

```
register({
  valueAsNumber: true,
  valueAsDate: true,
})
```

**Comment by bluebill1049** [comment]
here is an open vote for everyone in the community: 
https://twitter.com/HookForm/status/1330261464792371200

**Comment by bluebill1049** [comment]
here is the RFC: https://github.com/react-hook-form/react-hook-form/discussions/3495

**Comment by douglasrcjames** [comment]
I found this change useful for my number input, but I see that there is no `valueAsBoolean` and thus all my radio/checkbox's are passing a string of "true" or "false", which forces me to do a conversion manually for each input before passing to my database. Is there a similar method for converting booleans to their proper value? Here's my Radio input code:

```
<Column sm={12} md={3} lg={2}>
    <Label htmlFor={"logo.showTitle"} br>Show title?</Label>
    <RadioInput
        name="logo.showTitle"
        defaultChecked={props.site.logo.showTitle}
        value={true}
        error={siteForm.formState.errors?.logo?.showTitle ?? ""}
        {
        ...siteForm.register("logo.showTitle")
        } 
    />
    <Body display="inline" margin="0">Yes</Body>
    <RadioInput
        name="logo.showTitle"
        defaultChecked={!props.site.logo.showTitle}
        value={false}
        error={siteForm.formState.errors?.logo?.showTitle ?? ""}
        {
        ...siteForm.register("logo.showTitle")
        } 
    />
    <Body display="inline" margin="0">No</Body>
    <FormError error={siteForm.formState.errors?.logo?.showTitle ?? ""} /> 
</Column>
```
