### ISSUE TITLE
[Bug]: useWatch value missed prototype methods/values

### ISSUE THREAD

**Issue by olesmarola** [react-hook-form/react-hook-form#6319]
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-dates-forked-3v9ve?file=/DatePicker.js

### Steps to reproduce

1. Go to the sandbox.
2. Click on datepicker.
3. Look at the console.
4. See value object from the controller and from the watch.

### Expected behaviour

Here we have a datepicker that works with **moment.js** and use a **moment** object as a value. This object has a lot of methods in its **Prototype**. When we check this value with **watch** we got only object methods without Prototype.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`watch` only returns the inputs value.

**Comment by olesmarola** [comment]
> `watch` only returns the inputs value.

Yes, but the `moment` object **is** a value. So when I try to use `getValues('date')` I got the right result (fully worked `moment` instance), but when `watch` it's a broken object.

**Comment by julienavert** [comment]
This bug is still present in the `useWatch` hook.

Please someone look into this (@bluebill1049 ?) because it breaks all `useWatch` that observe objects with prototype (such as moment objects, luxon objects...)

It comes from this line https://github.com/react-hook-form/react-hook-form/blob/master/src/useWatch.ts#L79
