### ISSUE TITLE
[Bug]: reset(values) with shouldUnregister: true

### ISSUE THREAD

**Issue by adostal** [react-hook-form/react-hook-form#6482]
### Version Number

7.13.x

### Codesandbox/Expo snack

https://codesandbox.io/s/clever-merkle-fxjbl?file=/src/App.js

### Steps to reproduce

```javascript
const form = useForm({shouldUnregister: true})

React.useEffect(() => {
 form.reset({id: 'xxx', __typename: 'yyyy'})
})

const submit = (data) => {
 // data have __typename property
}

```

### Expected behaviour

```javascript
const submit = (data) => {
 // data have only id property
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior `shouldUnreigster: true` means we will remove input while they getting unmount, it's not a filter.

**Comment by adostal** [comment]
In version 7.12.x, this behavior was different. There, values that were not in the register were not passed.

**Comment by JGibel** [comment]
@bluebill1049 is it possible to re open this? 

The docs say "only registered input will be included as submission data." which this doesn't hold true for, and doesn't mention any differences between reset and setting the initial default values.

I modified @adostal 's CSB to highlight the different behavior between reset and default values: https://codesandbox.io/s/cocky-smoke-phlpz?file=/src/App.js

Also, here's a CSB running 7.12.0 that shows my expected behavior working as described:
https://codesandbox.io/s/spring-pine-hhlf0?file=/src/App.js

My use case is that I have forms where I get the initial data asynchronously , and have been using reset to set the initial state. Is there a way to get this to not merge unregistered inputs when using reset?

**Comment by bluebill1049** [comment]
thanks, @JGibel for the detailed reply and codesandbox, will take a look at the weekend. As far as i know this is expected behavior, i will see if there is any work around for your use case.

**Comment by adostal** [comment]
@JGibel I have same use case.
My solution is with yup validation.

If you use yup validation:
```javascript
useEffect(() => {
  form.reset(yupSchema.cast(data, {stripUnknown: true}));
}, []);
```
stripUnknown - remove all properties where is not set in yup schema validator

**Comment by bluebill1049** [comment]
> @JGibel I have same use case.
> My solution is with yup validation.
> 
> If you use yup validation:
> 
> ```js
> useEffect(() => {
>   form.reset(yupSchema.cast(data, {stripUnknown: true}));
> }, []);
> ```
> 
> stripUnknown - remove all properties where is not set in yup schema validator

This issue is getting resolved, will be released in the next patch.
