### ISSUE TITLE
[Bug]:  watch(from useFormContext) does not subscribe changes in Child Component

### ISSUE THREAD

**Issue by Kiiiwiii** [react-hook-form/react-hook-form#6613]
### Version Number

7

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-watch-bug-uv54e?file=/src/App.js

### Steps to reproduce

1. Go to the sandbox
2. During initialisation, first name & last name form field stay empty

### Expected behaviour

During initialisation, first name & last name form field should be update correctly (value: a & b)

If I downgrade to v6, the watch works (subscribe the change properly)
Or
If I call watch (from useForm) in the parent component(App), it also works.

I investigated a little bit and find out that the `_subjects.state` in `createFormControl` (https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts) is not set correctly(always empty) in the buggy case.
And when setValue, it try to emit changes to all subscribers from `_subjects.state`, but find no subscribers(https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L749).

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
v7 and v6 have a different internal design and there are some fundamental changes, so there is behavior change. 

- instant `register` with `watch`  (without value, default) will definitely not return a structured value pair, this is something I am not going to make it align with v6 because there is some fundamental difference 

Walk around above: always provide `default values`, `defaultValue` or `register` with `value`

- the second render at the child subscription I think I may found a solution for that, so going to try I tout tmr.

**Comment by M2Changezi** [comment]
@bluebill1049  i submitted a bug that unregister method isn't working in version 7 
[unregister method](https://codesandbox.io/s/react-hook-form-unregister-v6-forked-qs8o6) but it got removed even the bug is valid .

**Comment by bluebill1049** [comment]
This improvement should be released in the next minor update.
