### ISSUE TITLE
The library should provide a way to set initialValues.

### ISSUE THREAD

**Issue by juandaco** [react-hook-form/react-hook-form#674]
Hi there!
First of all thank you for a great library and you effort making this. I have a **suggestion/(problem I had)** when working with `react-hook-form`. 

While migrating a project from `formik`, I was trying to use `defaultValues` as `initialValues` and getting many errors and unwanted behavior in the process. The issue as I came to understand it, is that `defaultValues` get merged into the form when trying to submit. It took me a lot of debugging and rechecking my assumptions to understand what was causing the issues. This is not well explained in the documentation, even though the mistake is totally mine, is called _**default**Values_.

I think that the use case is common and general enough that people will use it. You just want a large enough entity/form pre-loaded without the merging at submit time that `defaultValues` provide.

I even ended up creating my custom hook, but I think more people would benefit from having this, or at least a better explanation of what happens when you submit the form, like `formik` [does](https://jaredpalmer.com/formik/docs/guides/form-submission).

```typescript
export const useRHFInitialValues = <FormValues = {}>(
  initialValues: Partial<FormValues>,
  setValue: FormContextValues['setValue'],
): void => {
  useEffect(() => {
    Object.entries(initialValues).forEach(([name, value]) => {
      setValue(name, value);
    });
  }, [initialValues, setValue]);
};
```

Let me know if there is anything I can help you with on this issue/request or if my understanding of the problem is mistaken.

**Comment by bluebill1049** [comment]
hey, @juandaco thanks for the detailed issue report.  RHF embraces uncontrolled components which is why I named it `defaultValues`, it's `defaultValue` for native input. so when you declare `defaultValues` RHF will place input `defaultValue` with `defaultValues`. If this is not working expected, maybe we have a bug. Do you have a codesandbox for this issue?

**Comment by bluebill1049** [comment]
hey @juandaco wondering what's your feedback on my reply above?

**Comment by bluebill1049** [comment]
thanks @juandaco for the detailed reply. I think you maybe able to get away with the issue from `reset()` api, so you can avoid pre-populated the inputs. I will close this issue here, but we can keep the conversation going, and i am more than happy to find a solution that works for you and many others. (if there is one 😄)
