### ISSUE TITLE
Could not setValue useFieldArray in useFieldArray

### ISSUE THREAD

**Issue by nghiepit** [react-hook-form/react-hook-form#6972]
### Version Number

7.18.1

### Codesandbox/Expo snack

https://codesandbox.io/s/calc-forked-tcqpu?file=/src/App.tsx:995-1008

### Steps to reproduce

1. Go to `SET SUB TASK TO 4 ITEMS`
2. See error: Tasks list does not set.

### Expected behaviour

The code below has no effect set the tasks.
```ts
setValue(`cart.${index}`, {
    name: "new test name",
    tasks: [
        {
        name: "name1",
        label: "label1"
        },
        {
        name: "name2",
        label: "label2"
        },
        {
        name: "name3",
        label: "label3"
        },
        {
        name: "name4",
        label: "label4"
        }
    ]
});
```

But if updated separately the `tasks` it will work
 ```ts
 setValue(`cart.${index}.tasks`, [...])
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
This is expected behavior, indeed the original purpose was to update a single input. As community growth requires groups inputs, we added some sugar syntax to update with object/array notation. 

![Screen Shot 2021-11-04 at 7 46 26 pm](https://user-images.githubusercontent.com/10513364/140284108-34ff81d8-24ea-47b4-bb6a-a3b8e9ea3e84.png)

> It's recommended to target the field's name rather than make the second argument a nested object.

when you fix with non-registered input and field array, it really makes input update difficult internally. 

https://github.com/react-hook-form/react-hook-form/blob/f60744eb741671ed596cabf065fd96dcd5cf4601/src/logic/createFormControl.ts#L634

What i would recommend is to either update individual inputs, target field array fields, or simply use reset API to update the entire form.

**Comment by nghiepit** [comment]
Thanks @bluebill1049
