### ISSUE TITLE
issue: Nested controller data issue

### ISSUE THREAD

**Issue by T0m1q** [react-hook-form/react-hook-form#6994]
### Describe the bug
Dynamically rerendered Form with nested Controller data and `shouldUnregister: true` causes the nested Controller data to be ejected on form submit. The issue doesn’t occur with nested uncontrolled inputs and root-level Controller inputs.

### Version Number

7.19.1

### Codesandbox/Expo snack

https://codesandbox.io/s/rhc-nested-controller-bug-42kfr

### Steps to reproduce

1. Open sandbox
2. Change any field
3. Click the `Submit` button
4. Notice submit value missing nested Controller data (info.city)

### Expected behaviour

Submitted value contains nested controller data

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by T0m1q** [comment]
Thanks for the quick reply,

I wanted to supply more real-world example which is also affected by this issue.
Showing the form on demand.

https://codesandbox.io/s/rhc-nested-controller-bug-v-2-lkmf5 

Steps to reproduce
1. Open sandbox
2. Change any field
3. Submit form
4. Hide form
5. Show form

**Comment by bluebill1049** [comment]
I will see what I can patch with the above. However, I wouldn't recommend such usage, this is conflicts with `defaultValues` with `state`, the usage is basically plugged in a react local state, but then after submit, it does not return the updated `state` from `usetState` because inside react hook form we don't aware or invoke `setState`, and finally submit is what's react hook form produced `formValues`, not the initial state which you have declared. so when input unmounts the `useEffect` with `Controller` kicked in and unsets the `formValues` internally which result in the current issue.
