### ISSUE TITLE
errors[name] with nested fields always returns undefined

### ISSUE THREAD

**Issue by mnesarco** [react-hook-form/react-hook-form#735]
**Describe the bug**

if name is something like myprop[0], errors['myprop[0]'] returns undefined, so the validation message cannot be shown.

`<input name="chk[0]" ref={register({required:"This is required"})}  />`

in this case errors['chk[0]'] is undefined, but validation fails, so the form cannot be submitted and the error message cannot be displayed.

I have tried to provide a codesandbox but there is a nasty bug in codesandbox (https://github.com/codesandbox/codesandbox-client/issues/667) and it was impossible to make it work.

**Comment by mnesarco** [comment]
I have discovered that errors object contains nested fields in a nested object structure, so

Wrong approach:

`let err = errors[ 'prop[0].text' ]
`

Correct approach:

`let err = errors['prop'] && errors['prop'][0] && errors['prop'][0]['text']
`

So it means that this is by design and not a bug. It is very confusing anyway because the name specified in the input component is a string (name="prop[0].text") and it is more logic to use the same string to find the error, but anyway. I think the documentation can be more explicit about this things.

**Comment by bluebill1049** [comment]
hey @mnesarco 

Previous version V3 we are using flat error object

Current V4 we are changing to nested error object. Will improve the doc to reflect that.

**Comment by bluebill1049** [comment]
also a tip you can use optional chaining, which is one of the reasons why we switch to nested.

**Comment by mnesarco** [comment]
Hi @bluebill1049 thanks for the info. I cannot use optional chaining because I have written a custom error message component which receives the name ("aaa.bbb[0].xxx") and errors object as props and renders default messages based on type if no message is specified in the instance.

I have solved it using a variation of this: https://stackoverflow.com/a/22129960/1524027 to parse the string and extract the error message.

**Comment by bluebill1049** [comment]
@mnesarco i think we can improve ErrorMessage to help you tho @kotarella1110

**Comment by stern-shawn** [comment]
I think I'm running into a similar type of issue (I'm upgrading from `react-hook-form@3.28` to latest, haha). I had a reusable field component that uses `FormContext` and accesses a field's errors similar to the examples in the docs

```
...
  const { errors, register } = useFormContext();
  const errorMessage = errors[name]?.message`
...
```

where name could be a nested property like `"user.firstName"`. In v3 this worked just fine because the errors object was flat, and `errors["user.firstName"]?.message` was valid, however now I would need to access the property via `errors.?user?.firstName?.message` very explicitly, which I can't generate dynamically 😢 (I don't think, hopefully I'm just unaware of the fix 😅 ).

I'm able to work around this using `lodash/get` but I was very happy earlier being able to fully use dynamic properties + TS + optional chaining with the flat errors. Example workaround (very gross because of the type casting)

```
const errorMessage = (get(errors, name) as FieldError)?.message;
```

I absolutely love this library and it's made things so much nicer than Redux-form / Formik, this is just a little nit since I feel dirty having to bring back lodash haha ❤️

**Comment by bluebill1049** [comment]
> I think I'm running into a similar type of issue (I'm upgrading from `react-hook-form@3.28` to latest, haha). I had a reusable field component that uses `FormContext` and accesses a field's errors similar to the examples in the docs
> 
> ```
> ...
>   const { errors, register } = useFormContext();
>   const errorMessage = errors[name]?.message`
> ...
> ```
> 
> where name could be a nested value like `"user.firstName"`. In v3 this worked just fine because the errors object was flat, and `errors["user.firstName"]?.message` was valid, however now I would need to access the property via `errors.?user?.firstName?.message` very explicitly, which I can't generate dynamically 😢 (I don't think, hopefully I'm just unaware of the fix 😅 ).
> 
> I'm able to work around this using `lodash/get` but I was very happy earlier being able to fully use dynamic properties + TS + optional chaining with the flat errors. Example workaround (very gross because of the type casting)
> 
> ```
> const errorMessage = (get(errors, name) as FieldError)?.message;
> ```
> 
> I absolutely love this library and it's made things so much nicer than Redux-form / Formik, this is just a little nit since I feel dirty having to bring back lodash haha ❤️

Thanks @stern-shawn man it's always a tradeoff... 

to be honest, I love v3 flat errors, but then everyone is cry about the type-safe :( guess really i don't have a choice rather than listen to the community, but :) i am going to export some of the utility functions from RHF, which include my tiny version of 'get' so you can skip using lodash if you want as well, (it's on my todo list and it will come :)

**Comment by bluebill1049** [comment]
by the way, i am really glad that you find it useful too ❤️ @stern-shawn

**Comment by stern-shawn** [comment]
I truly do, it's such a small nitpick in the face of so much goodness 😄 

I read in #725 how I can leverage something like `useFormContext<MetaDataFormFields>()` to have super strongly 💪 typed `error.whatever.ayy.soNested?.message` access which sounds amazing for less generic/universal components that are specific to one form type. Awesome!

**Comment by oualidmaz** [comment]
Now you can import the utile function "get" directly from react-hook-form and use it like this : 
```
import { useFormContext , get } from 'react-hook-form';
const { control, formState } = useFormContext();
const error = get(formState.errors, props.name);
// error.message to show the error message
```

**Comment by pnlabs** [comment]
You need to get filedState in Controller render props instead of formState errors object:

```
render={({ fieldState: { error }, field: { onChange, value } }) => {
```

**Comment by kamzata** [comment]
> Now you can import the utility function "get" directly from react-hook-form and use it like this :
> 
> ```
> import { useFormContext , get } from 'react-hook-form';
> const { control, formState } = useFormContext();
> const error = get(formState.errors, props.name);
> // error.message to show the error message
> ```

It works! But... where can I find it in the official Docs? There isn't any mention to this get function!

**Comment by IgnusG** [comment]
I have the opposite problem - I get a nested error object from react-hook-form and have to find out the path to the first error so I can query a label and scroll to it (the auto scroll provided by react-hook-form does not work reliably since I use it with MUI).

The solution I have now is to manually parse the object (loop over its keys deeper and deeper) until I hit an object that has a ref property (then I know I hit the full path) and then construct a new path out of this process. 

Then I can use something like `document.query(`label[name="${path}"]`).scrollIntoView()` or `.focus()`.

> PS: Maybe this is worth a new issue/discussion but it is related to the nested error object change from v4 (otherwise getting the path would be as simple as an `Object.keys(errors)[0]`.

**Comment by bluebill1049** [comment]
> I get a nested error object from react-hook-form and have to find out the path to the first error so I can query a label and scroll to it (the auto scroll provided by react-hook-form does not work reliably since I use it with MUI).

could you elaborate not working relaible? This probably only happen when input reference is not supplied.

**Comment by IgnusG** [comment]
> > I get a nested error object from react-hook-form and have to find out the path to the first error so I can query a label and scroll to it (the auto scroll provided by react-hook-form does not work reliably since I use it with MUI).
> 
> could you elaborate not working relaible? This probably only happen when input reference is not supplied.

There is an issue with MUI with the refs sometimes misbehaving (there's an FAQ about this on the react-hook-forms and I've ran into this [issue](https://github.com/react-hook-form/react-hook-form/issues/5947) repeatedly since it's easy to mess up) but after I fixed that I encountered another issue - this time timing related. I currently listen to `form.formState.errors` in a React's `useEffect` but if I fire the `ref.focus()` inside it the browser does not pick it up (no scrolling and no focus). I have to wrap it in a `setTimeout` for it to work.

I also get errors back from my backend which uses flat error paths for which I'd have to do the scroll to error manually anyway so I've decided to just turn the automatic scroll to error feature off in react hook forms.

Unfortunately since the errors are nested for react-hook-form I have to parse those manually and build a flat path from them for the query. I couldn't find any helper inside the library to do something similar to this

**Comment by bluebill1049** [comment]
I have a feeling some of your input ref is not been forward or wired-up which result in input is not bee focused, but in terms of first errors lookup, your approach is correct. However, if you have flattened or data it's probably easier with a single exit loop.

**Comment by IgnusG** [comment]
> I have a feeling some of your input ref is not been forward or wired-up which result in input is not bee focused, but in terms of first errors lookup, your approach is correct. However, if you have flattened or data it's probably easier with a single exit loop.

Yeah I have something like this now (very quickly hacked together)
```typescript
export function scrollToFirstFormError(form) {
  let path = '';
  const scrollToFirstError = (err) => {
    const errorRecord = Object.values(err).find((element, index) => {
      if (isObject(element)) {
        path = path
          ? `${path}.${Object.keys(err)[index]}`
          : path + Object.keys(err)[index];
        return true;
      }
      return false;
    });

    if (errorRecord?.ref) {
      const element = document.getElementsByName(path)[0];
      if (element) {
        element.scrollIntoView({ block: 'center' });
        element.focus();
      }
    } else if (errorRecord) {
      scrollToFirstError(errorRecord);
    }
  };
  return scrollToFirstError(form?.formState?.errors);
}
```
