### ISSUE TITLE
issue: isValid does not update when using zod resolver

### ISSUE THREAD

**Issue by ZeroPie** [react-hook-form/react-hook-form#7533]
### Version Number

7.24

### Codesandbox/Expo snack

https://codesandbox.io/embed/react-hook-form-zod-resolver-example-forked-gme7b?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

1. Go to Inputs and type numbers
2. See isValid not updating

### Expected behaviour

isValid should be set to true when the values of the inputs fit the validator criteria

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Tho, you codesandbox uses RHF ver. `6.8.4`...

**Comment by ZeroPie** [comment]
@Moshyfawn thanks for the quick answer, i updated thf to 7.4.0 and spreaded the register, IsValid is still not updating.

**Comment by Moshyfawn** [comment]
At a glance, your Zod schema suggests that both name and age values should be of **type number**. If you subscribe to `errors` form state, you'll see `Expected number, received string` for both fields even if you enter a numeric value, since the value that comes from the input is of **type string**. You can simply add `valueAsNumber: true` as a `register` method option or look into [Transform and Parse section of RHF docs](https://react-hook-form.com/advanced-usage/#Transform).
Now, that said, it deosn't seem like the `isValid` is set to false on from submition even with both fields having a valid value, @bluebill1049. [See this codesandbox](https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-nhwqf)

https://user-images.githubusercontent.com/16290753/149536059-c9a48cc4-788e-4a66-aead-f2ce60179721.mp4

**Comment by Moshyfawn** [comment]
>###  Expected behaviour
> isValid should be set to true when the values of the inputs fit the validator criteria

To this point, [the `mode` prop of `useForm`](https://react-hook-form.com/api/useform/) dictates when the validation occurs. So, if you want to validate the form values when they fit the criteria, you should set the `mode` prop to `"onChange"`

**Comment by ZeroPie** [comment]
@Moshyfawn thanks, it works by setting a mode.

**Comment by bluebill1049** [comment]
thank you @Moshyfawn yes mode is required.

> Note: isValid is affected by mode at useForm. This state is only applicable with onChange, onTouched, and onBlur mode.

https://react-hook-form.com/api/useform/formstate
