### ISSUE TITLE
getInputValue logic error

### ISSUE THREAD

**Issue by iamwelk** [react-hook-form/react-hook-form#757]
**Describe the bug**
When I use Controller, I can't change my component's value to `undefined`, it will report error
```
Uncaught TypeError: Cannot read property 'value' of undefined
    at getInputValue (react-hook-form.es.js:1245)
    at commonTask (react-hook-form.es.js:1280)
    at Object.handleChange [as onChange] (react-hook-form.es.js:1291)
    at NumberPicker.setValue (index.js:257)
    at NumberPicker.setInputValue (index.js:92)
    at NumberPicker.onChange (index.js:85)
    at Object.onChange (index.js:337)
    at Base._this.onChange (base.js:42)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
```
I think it will be better to check target is undefined before use target.value
```
var getInputValue = (target, isCheckbox) => {
    return isCheckbox
        ? isUndefined(target.checked)
            ? target
            : target.checked
        : isUndefined(target.value)
            ? target
            : target.value;
};
```

**Comment by bluebill1049** [comment]
hey @iamwelk you got a codesandbox for me to take a look?

**Comment by bluebill1049** [comment]
This almost sounds like `target` is `undefined`?

**Comment by EvGorbenko** [comment]
I have exactly the same problem. Unfortunately, I can't share the code, because it's a lot of recompose HOCs to copy. But the main problem is:
We have a custom select that accepts a value as a string or undefined if nothing is selected.

In case of react hook form - I can't use it with this field unless I'll make some hacks around. 
Right now string works fine cause it doesn't have a property value. But if I want to pass an undefined in order to clean input - undefined doesn't have properties and UI throws an exception.

Example how we can fix that without breaking existing code:
`
const getInputValue = (target, isCheckbox) => {
    const isTargetUndefined = isUndefined(target);
    return isCheckbox
        ? isTargetUndefined || isUndefined(target.value)
            ? target
            : target.checked
        : isTargetUndefined || isUndefined(target.value)
            ? target
            : target.value;
};
`

**Comment by iamwelk** [comment]
https://codesandbox.io/s/bitter-platform-7inu3

**Comment by bluebill1049** [comment]
thanks @iamwelk what's the step to reproduce in your example?

**Comment by iamwelk** [comment]
@bluebill1049 
1. input some value
2. clear the input area
3. click the button

**Comment by bluebill1049** [comment]
oh cool thanks @iamwelk

**Comment by bluebill1049** [comment]
going to have dinner now, can you guys please testing on this beta version `4.4.1-beta.1`

**Comment by bluebill1049** [comment]
verified on my end. @iamwelk you ok with this patch?

**Comment by iamwelk** [comment]
> verified on my end. @iamwelk you ok with this patch?

Yes, it's work now ,thank you!

**Comment by bluebill1049** [comment]
will release the patch tonight
