### ISSUE TITLE
issue: trigger

### ISSUE THREAD

**Issue by josias-r** [react-hook-form/react-hook-form#7602]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/determined-zeh-t1j3m?file=/src/App.tsx

### Steps to reproduce

1. Checkout the sandbox
2. Clicking the "Name: ..." div does call setValue and afterwards "trigger" to trigger validation for all fields
3. isValid bool still returns "false"

... The reason we have this pattern, because we once had performance issues when updating multiple fields using `setValue(name, val , {shouldValidate: true})`. Therefore we did not validate them each, but just after all the `setValue` calls, we ran `trigger` to run validation for all fields, just once. This used to work fine afaik.

It also interesting, that only `trigger()` does not work but `trigger("aspecificfield")` does correctly update the isValid bool returned from formState

### Expected behaviour

isValid boolean should update to true (the return of the trigger method itself is actually "true")

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Any reason to use `setValue` instead of field's `onChange` as intended? Check out [this CSB](https://codesandbox.io/s/mutable-water-19jzp?file=/src/App.tsx)

**Comment by josias-r** [comment]
@Moshyfawn We've been using react-hook-form for quite a while now, not sure if this onChange was always a thing 🤔
The docs just state [sends the input's value to the library](https://react-hook-form.com/api/usecontroller/controller). Does that include validation + updating dirty Value?

We currently always used `setValue(name, value, {shoudlDirty:true, shouldValidate: true})`

**Comment by Moshyfawn** [comment]
Huh, going back to the earliest version of RHF docs available, here's [a page on `<Controller />` API](https://react-hook-form.com/v5/api#Controller) that has `onChange` mentioned in usage examples. Idk :P
[On the current docs page](https://react-hook-form.com/api/usecontroller/controller) it states

> It should be assigned to the onChange prop of the input

Now, whether or not the `onChange` includes executing validation depends on your [form validation `mode`](https://react-hook-form.com/api/useform). Values `onChange` or `all` are what you need to invoke the validation behavior you want `onChange`. There's also `onTouched` mode:

> Validation will trigger on the first blur event. After that, it will trigger on every change event.

If the field value is dirty or not is determined by RHF by comparing the input's default value vs it's current state. So, basically, `onChange`'s gonna dirty your field whenever the input's value is changed with value different from it's  default one.

You should consider using `onChange` instead of `setValue` as it's all the functionality you want from RHF, but included by default.

@bluebill1049 do you think, based on this conversation, there's any need on improving / changing any RHF docs descriptions?

**Comment by Peter-AMD** [comment]
> @bluebill1049 do you think, based on this conversation, there's any need on improving / changing any RHF docs descriptions?

I agree on this one, I've been reading the docs these past few days. Some sentences are quite confusing or phrased confusingly for me. Adding more details, more examples, use cases, etc., would be very helpful.

**Comment by josias-r** [comment]
@Moshyfawn Thank you for the hint and the explanations 😄  I will check it out, seems like switching the pattern is the way to go

**Comment by josias-r** [comment]
You can close this, unless you want to keep it for documentation improvements

**Comment by bluebill1049** [comment]
> I agree on this one, I've been reading the docs these past few days. Some sentences are quite confusing or phrased confusingly for me. Adding more details, more examples, use cases, etc., would be very helpful.

Thanks for the feedback and I agree those issues/problems/improvements do exist. I hate to say this, but there is only so much I can do with my free time. if things are confusing or misleading send a dedicated issue report at the documentation repo with more detail, or even better send a PR with thing you reckon can be improved. It's an open-source project instead of a paid product, we can all help.

**Comment by bluebill1049** [comment]
thank you so much again @Moshyfawn you are my life & time saver. 🙏 Indeed the reason why i posted this couple days ago: https://github.com/react-hook-form/react-hook-form/discussions/7570

**Comment by bluebill1049** [comment]
> @bluebill1049 do you think, based on this conversation, there's any need on improving / changing any RHF docs descriptions?

Any suggestion on how to improve this part (I can update this) and suggestion, or PR welcome.

**Comment by Moshyfawn** [comment]
> > @bluebill1049 do you think, based on this conversation, there's any need on improving / changing any RHF docs descriptions?
> 
> Any suggestion on how to improve this part (I can update this) and suggestion, or PR welcome.

I don't have an immediate answer to patch rn, but I have a couple of ideas on some changes that might clear out some of the confusion. Let me clean sort through some work and I might get that ideas PR going

**Comment by bluebill1049** [comment]
Awesome! Thanks 😊👍

**Comment by ClementLevesque** [comment]
thanks for your answers @Moshyfawn, I would like to add something about a possible way to handle such case where the formState prop is not updated after a trigger. Think about using the [shoudValidate](https://react-hook-form.com/api/useform/setvalue) prop to true as a config option to setValue :) It was the trick for me :)
