### ISSUE TITLE
issue: useFieldArray doesn't find the ArrayPath of string[] but does for String[]

### ISSUE THREAD

**Issue by harshal317** [react-hook-form/react-hook-form#7622]
### Version Number

7.24.2

### Codesandbox/Expo snack

https://codesandbox.io/s/dreamy-wildflower-dk5wo?file=/src/App.tsx

### Steps to reproduce

If you try to use the useFieldArray API with a type that has a primitive array it seems to not let you as it doesn't detect the array paths, and you get a 

`Type 'string' is not assignable to type 'never'.ts(2322)`

However, with a `String[]` it seems to work just fine.

### Expected behaviour

I expect it would work with `string[]` as well 🤷‍♂️ 

I am curious if I can get a way with just a `@ts-ignore` and 

```
  const { fields, append, remove } = useFieldArray({
    control,
    // @ts-ignore
    name: "PATH",
  })
  ```
  
  I also wouldn't mind helping fix this bug (if it is unintended) with some guidance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The field value should be an `object` type. It's defined as `Record<string, any>`. See #7586 for more details

**Comment by harshal317** [comment]
Hmm, is it okay to still have a `string[]` if not using `useFieldArray` ?

**Comment by Moshyfawn** [comment]
The behavior that caused your confusion is due to RHF generating it's own unique ids to manage the array manipulations _(append / remove / update etc.)_. Refer to [the `useFieldArray` docs section](https://react-hook-form.com/api/usefieldarray) for more info

> useFieldArray automatically generates a unique identifier named id which is used for key prop

You can do `string[]` and manage your fields yourself in theory. It's not very convenient, tho. See [this CSB](https://codesandbox.io/s/dark-frog-vqm57?file=/src/App.tsx)

**Comment by bluebill1049** [comment]
This is expected behavior, `useFieldArray` doesn't support flat array. Thanks for the help @Moshyfawn
