### ISSUE TITLE
issue: Appending/Inserting objects with useFieldArray at an index that had a defaultValue will have ghost data from the default value applied to it

### ISSUE THREAD

**Issue by nbpeth** [react-hook-form/react-hook-form#7685]
### Version Number

7.25.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-js-forked-pusz9?file=/src/Header.js

### Steps to reproduce

* Click "insert @ 0 without name", the new input with have the value of what was initially at index 0
* Do the same with index 1
* Click the buttons that insert at an index with the name value provided - the provided name will be in the text box
* Remove all items, then add items without names. Append without name three times and you'll see "cats", "fish", ""

### Expected behaviour

if an item is removed from the list it should be gone. if I add  a new object to the field array I should not see data from the ghost of what was removed from that index sewn into the new object.

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
hey, @nbpeth append, prepend, insert API payment are all required, and not partial. I will update the doc to emphasise that.

**Comment by bluebill1049** [comment]
Actually, it's already in the doc:
![Screen Shot 2022-01-29 at 10 36 45 am](https://user-images.githubusercontent.com/10513364/151635808-0449f066-1b1e-4b0e-9d9c-21be7c514eb3.png)

**Comment by nbpeth** [comment]
@bluebill1049 apparently I missed that note, the behavior was so strange I spent all my time trying to figure out _how_

**Comment by bluebill1049** [comment]
Sorry to hear that @nbpeth I have now left a note on each API. perhaps this is something we could improve. The problem is each input is uncontrolled, so you will need to let the hook know what value is it, and we can't predict or assume it to be an empty `string`,  `undefined` or `null`.

![Screen Shot 2022-01-29 at 10 41 34 am](https://user-images.githubusercontent.com/10513364/151636150-d4e94777-fa76-4d31-8fdf-ebbdfe7d0828.png)

**Comment by bluebill1049** [comment]
Also an important note on `undefined`, it's reserved for fallback to `defaultValues`. eg if defaultValue is supplied, we will take defaultValue, otherwise, take `defeaultValues`. So we can't really mess around too much with `undefined`, which goes back to the initial issue, those APIs append/prepend/insert do need to have some sort of value.

**Comment by nbpeth** [comment]
yes, thank you @bluebill1049 - thanks for updating the docs and the explanation. It's good to know that my solution is the expected use of the api
🍺
