### ISSUE TITLE
issue: controlled textarea deoesn't set focus properly (cursor always at 1st position)

### ISSUE THREAD

**Issue by cbdeveloper** [react-hook-form/react-hook-form#7776]
### Version Number

7.26.1

### Codesandbox/Expo snack

https://codesandbox.io/s/stupefied-leakey-vzchw

### Steps to reproduce

1. Go to the CodeSandbox link (on Chrome or Firefox)
https://codesandbox.io/s/stupefied-leakey-vzchw

![image](https://user-images.githubusercontent.com/43407798/153015873-e2d745c0-2dbf-40ec-a012-3b75c2e441c7.png)

2. Click on both "Set focus" button

3. See difference in behaviour

### Expected behaviour

Both inputs should focus properly. 
The textarea should scroll to the bottom and the cursor should be at the last position of the input value.

Obs: the difference in behavior is happening in Chrome and Firefox.

Just tested on Safari, and it does not focus properly any of the inputs. 😔

Haven't tested on other browsers.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Hey, @cbdeveloper
First, I'd like to address that the initial focus behavior with plain React is to focus the input with the cursor at 1st position. So, if anything, uncontrolled input's focus behavior is incorrect. Sure, the cursor on the input that had some previous interaction _(text input)_ is gonna be at it's last position, but it only applies to the already modified input, where the initial cursor position has been changed.
See [this CSB](https://codesandbox.io/s/sweet-cdn-7ykm3?file=/src/App.tsx).

What RHF does is it takes the default field value provided to `defaultValues` at the `useForm` hook and sets the `value` attribute of an uncontrolled component with it's provided default value. I'm suspecting that this behavior doesn't exactly sit well with some browser that you're getting this behavior in.

Now, as a workaround, instead of providing the uncontrolled component's value at the `useForm` hook level to as `defaultValues`, you can set `defaultValue` attribute of the actual uncontrolled input which will prevent the unwanted behavior from happening.

As to will this behavior inconsistency be fixed, we'll have to investigate further, because the way RHF sets a default value to an input from `defaultValues` is the core functionality and a bunch of things will have to be considered.

**Comment by Moshyfawn** [comment]
Makes sense!
Thank you for your time and kind words! Indeed, uncontrolled components and embracing the native Web inputs is where it's at in terms of forms performance!
