### ISSUE TITLE
useFieldArray Improvements

### ISSUE THREAD

**Issue by mydesweb** [react-hook-form/react-hook-form#7785]
1.
I need to keep my field array items in ascending or alphabetically order, sorted by a certain key like a `date` or a `title`, so using `append`, `prepend`, `insert` actions will not help.. I need something simple like `array.sort`

2. 
after using an action like `append`, `prepend`, `replace`, etc the `dirtyFields` from `formState` will contain all form values, not only the dirty fields,  anyway they are marked correct with `false`. If I don't use any of `useFieldArray` actions then `dirtyFields` will contain only dirty fields marked with `true`. It is just a slightly difference in which information it contains.

**Comment by bluebill1049** [comment]
thanks for the feature request, I would normally put them into two separate feature requests as they are two separate things.

1. for the sorting please consider doing it at the app level for now.
2. marking dirty fields was due to performance, currently it's doing the cheapest and fastest way of marking dirty fields. as far as I know, I think only hook form does dirty field for field array, would be good to know if any other lib has a better approach towards this problem.

**Comment by Dinodanio** [comment]
@mydesweb we implemented this feature at app level with `useReducer`, `useContext` and set the value to the form context after every change on the array. I suggest to do it early because removing the formContext from controlled components was a mess ;)
