### ISSUE TITLE
Field Array does not work with validating fields

### ISSUE THREAD

**Issue by AndreasRydberg** [react-hook-form/react-hook-form#7833]
### Version Number

7.27.0

### Codesandbox/Expo snack

https://codesandbox.io/s/great-snyder-y9h0j?file=/src/App.tsx

### Steps to reproduce

1. Go to sandbox
2. Click on "Add person"
3. Fill in fields ("First name" and "Last name")
4. Click on "Submit"
4. The previously given/hardcoded fields are marked as invalid, even they are valid and never touched.

(For each time you click "Submit" again then one more field will be valid, and so on..)

### Expected behaviour

Expected all fields to be valid.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
The use of the field path is wrong in [the provided CSB](https://codesandbox.io/s/great-snyder-y9h0j?file=/src/App.tsx). 
You should pass the field item `index` instead of the `field.id` to register your input field with the field path name from the form values.
Refer to [the RHF docs section on `useFieldArray` usage](https://react-hook-form.com/api/usefieldarray)
See [this CSB](https://codesandbox.io/s/unruffled-mccarthy-4z3kco?file=/src/App.tsx) for a working example

**Comment by bluebill1049** [comment]
thanks @Moshyfawn 🙏

**Comment by AndreasRydberg** [comment]
Thanks @Moshyfawn! :smile:
