### ISSUE TITLE
Provide a method for focusing custom inputs during validation

### ISSUE THREAD

**Issue by Smona** [react-hook-form/react-hook-form#785]
**Is your feature request related to a problem? Please describe.**
As it stands, there isn't a reliable way to hook into validation and focus or scroll to a custom, controlled input on validation. It seems to me that this is the last step for making controlled inputs first-class citizens of react-hook-form.

**Describe the solution you'd like**
Now that we have `<Controller>` in the repo, it could be used to provide this behavior. Two possible implementations come to mind:

- Render the inputs passed to `Controller` within a div, and use `focus()` or `scrollIntoView()` on that div when that field is the next focusable error.
- Accept a prop similar to `onValidationFocus` in `Controller`, which allows us to define custom behavior, like focusing a specific input.

These solutions could potentially overlap, so that there's a default solution which can be overriden.

**Describe alternatives you've considered**
Based on my efforts, there's no way to achieve this currently without interfering with validation focusing of uncontrolled inputs

**Additional context**

**Comment by bluebill1049** [comment]
Thanks for the feature request, however i think this would be better to handle at your app level, because external component's ref hard to predict (in order for us to scroll into view). I am certainly don't want to introduce extra `div` or `span` around user's component, this will easy lead to other unwanted behaviour or side effect. 

As a solution, i would make custom hook at your app level which subscribe to the `errors` object and scroll into the first error (which you have to provide your components reference). This may sounds difficult but it's achievable.

Hope these make sense, i am going to close this issue for now.

**Comment by Smona** [comment]
That's understandable. Thanks for the suggestion!
