### ISSUE TITLE
Dependant Fields

### ISSUE THREAD

**Issue by mattsputnikdigital** [react-hook-form/react-hook-form#8170]
**Is your feature request related to a problem? Please describe.**
Unable to easily validate dependant fields

**Describe the solution you'd like**
Add a property to related **register** and **useController** methods.

**Describe alternatives you've considered**
Creating a wrapper component but would have potential race conditions and a lot of boiler plating for custom inputs.

**Additional context**
I make a lot of complex forms in my job / industry of financial services, lots of dependant fields when validating. Validation uses Yup and is quite complex. It would be great to have a trigger param to allow for RHF to trigger a full validation update after 'onChange' or 'onBlur' which could be set on an individual basis. Something like the below...

```
const {
    field: { onChange, value, onBlur, ref },
    fieldState: { error, invalid },
  } = useController({
    control,
    name,
    trigger: 'change'
  });
```

**Comment by Moshyfawn** [comment]
What's the issue with [the `deps` property](https://react-hook-form.com/api/useform/register)?

**Comment by mattsputnikdigital** [comment]
I thought that was going away, maybe a misunderstanding, been reading a good few posts / issues on this topic. Does deps work with a yup resolver?

"Validation will be triggered for the dependent inputs,it only limited to register api not trigger."

It would be great if dips could be added to useController as well

**Comment by bluebill1049** [comment]
One of the design principle for hook form is to improve performance which lead by validation computation and component render. The reason why we are optimised for field level validation and optimise render base on user interacted input, if depends validation occured you will have to use the trigger or deps API to info those input are related. While going thr opposite is full render on each keystorke and validation running constantly which is something we are here improve upon.

**Comment by mattsputnikdigital** [comment]
The problem is, say with massive insurance forms, a lot of related questions are asked. DOB can relate to if you were born or moved to the country for instance. The next question and the DOB question both validate against each other and the client expects each validation to fire onChange, or at the very least onBlur. Otherwise you have the user scrolling up and down a lot whilst these questions are all validated against each other on submit, sometimes invalidating another question.

We also template all the input types into Question components and use useController to setup each question from passing in a name. Makes laying out sometimes hundreds of questions, across multiple pages much easier.

Previously with Ember using "Ember CP Validations" and React using "Formik" and "Yup" this has been possible. It wasn't the most performative in Formik, but with careful construction of components, using hooks etc.. it worked out ok and was not noticeable slow.

Moving trigger into controller would help us with the ability to keep templated components for generating forms.

**Comment by JamesWong1999** [comment]
isn't that the same as basically using `trigger` inside your controller?

```tsx
<Controller
  render={({ field }) => {
    return <input onChange={(e) => {
      field.onChange(e);
      trigger('whatever')
    }} />
  }}
 />
```

**Comment by mattsputnikdigital** [comment]
Well that out mean moving trigger down the props chain and losing out on the built it functionality of the deps prop.

trigger: 'blur' | 'change' for convince in useController or let useController accept the deps prop.

**Comment by QzCurious** [comment]
Is that meaning this feture request is about to introduce `deps` prop for `useController`? How can I upvote it? I need this too.

**Comment by eugene-mohc** [comment]
I find this would be incredibly useful as well, especially at the `useController` hook level.

For example:

Basic use cases where and input's validation depends on another input's value, like a "new password" and "repeat new password" field. Right now there is no easy way to validate both when either one changes when you are using `useController`, without doing manual `useWatch` and `useEffect` with `trigger` calls. It creates a lot of boilerplate code that has to be duplicated for every similar use case. This becomes prone to bugs and hard to read code.

Another use case is when multiple fields are used to create a single value when the form is submitted. For example having multiple selects for hours, minutes, and seconds, and when the form is submitted, the values are transformed in the submit handler. But during form editing, there's no easy to way specify validation rules without again a lot of `useWatch` for the other fields and manual `trigger` inside of `useEffect`.

I think in the end in both examples, performance suffers even more because of all the extra watches and effects you have to write. There would probably be no additional harm to the performance if this was built in, while also significantly improving the developer experience and avoiding potential bugs with rolling your own solution every time this is needed.
