### ISSUE TITLE
In "onSubmit" mode, the validation check of the array is executed after the first time of changing the value of the array

### ISSUE THREAD

**Issue by wang5555555555** [react-hook-form/react-hook-form#8246]
### Version Number

7.30.0

### Codesandbox/Expo snack

https://codesandbox.io/s/reacthookform-array-iziovm?file=/src/App.tsx

### Steps to reproduce

In "onSubmit" mode, the validation check of the array is executed after the first time of changing the value of the array.

1. Click on the button [+ADD] and a row will be added.
2. Click on the button [X] at the end of the added row.
3. The validation error of the array is displayed and it is not empty.

However, if I change the value of any string field(in the sample "groupName" is a string field), the validation check only will be executed after clicking the [submit] button.

### Expected behaviour

In "onSubmit" mode, the validation check of the array only is executed after submitting the form.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I did a bit closer look at this issue. I don't think we can leverage the `mode` as it's more closely related to user interaction on individual inputs. while useFieldArray action is most like a trigger point of user decision. What I would suggest is to use the form state `isSubmitted` and combined it with `errors` object.  Also why 'onChange` mode is not applicable here, because it will affect the user's interaction with divisional inputs. so conclusion do the following:

```tsx
formState.isSubmitted && formState.errors.fieldArrayErrors
```
