### ISSUE TITLE
useFieldArray() with validation breaks input focus behavior

### ISSUE THREAD

**Issue by vgjenks** [react-hook-form/react-hook-form#8297]
### Version Number

7.14.2

### Codesandbox/Expo snack

https://codesandbox.io/s/funny-knuth-rr879b?file=/src/index.js

### Steps to reproduce

1. Click the "Save" button - will validate since there are two empty fields
2. Click into one of the empty input fields and type a character - focus is lost
3. Focus into the field again, note that you can now finish typing

### Expected behaviour

I never expect to lose focus, like any other non-dynamic form I've built with react-hook-form.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
not an issue with this library , your component is getting unmounted on each render.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/discussions/7660

**Comment by vgjenks** [comment]
> not an issue with this library , your component is getting unmounted on each render.

Is that to say, the library just isn't really equipped to handle it? How am I supposed to control that? I don't see a solution in the link you provided, either...just the same answer; "not a library problem". Isn't it still a library problem if the useFieldArray() feature can't be implemented w/o this problem?

Perhaps that's the real issue - finding documentation with a full example of how to build a form this way, just doesn't exist. I couldn't even cobble a working example together in two days of Googling and experimentation. Happy to write one up, if I could get it to actually work.

Apologies if it seems like I'm being dense, but there just doesn't appear to be a solution.

**Comment by Moshyfawn** [comment]
@vgjenks how would you like to actually listen to what you've been told and quite wining about not having a solution given to you on a plate?

It is not an issue with RHF but an issue with your React knowledge. If you define your component inside another component, the former one gets re-mounted on each re-render with a different reference. Same goes to every function you define in the components body. Hence the input losses focus and RHF is not able to track your input's `ref` to focus it on error.

There's a full list of resources like [RHF docs](https://react-hook-form.com/) with great examples + codesandboxes, [the whole folder](https://github.com/react-hook-form/react-hook-form/tree/master/examples/V7) of examples on how to implement different features with RHF, [a freaking tone of discussions](https://github.com/react-hook-form/react-hook-form/discussions?discussions_q=useFieldArray) around `useFieldArray` and most if participants have a working example at the end of each discussion. And you decide that your "unique" use-case, that you yourself call ["a much simpler example"](https://github.com/react-hook-form/react-hook-form/discussions/7660#discussioncomment-2689333) is so outside the docs, your decide to demand ["a full example of how to build a form this way"](https://github.com/react-hook-form/react-hook-form/issues/8297#issuecomment-1117688534).

I hate to write all these words to you, but the disrespect you've shown to maintainers of the package just because "I  _[you]_ couldn't even cobble a working example together in two days of Googling and experimentation" is beyond my understanding.

I've already answered to your question in [this comment](https://github.com/react-hook-form/react-hook-form/discussions/7660#discussioncomment-2689566) as well.

**Comment by bluebill1049** [comment]
You have every right to complain about things not working which was made for "free", but remember this is not a technical support channel and when maintainers try to respond with an answer or solution they are doing you a favor. Please read carefully what @Moshyfawn has answered and helped above as this is something you probably won't get from every library maiantiners.

**Comment by vgjenks** [comment]
Perhaps my tone was misunderstood. No disrespect intended - was only meant to get down to brass tacks, after a long, fruitless struggle. This wasn't simple to piece together and it took several bits from different articles, bug reports, and peoples Codesandboxes, etc. The problem with this, is they are coded to very specific use cases without much, if any, explanation.

Regardless, I'll write something up and put it out there, now that I've got a working example. Thanks!
