### ISSUE TITLE
Determine checkbox group by defaultValues when using useController

### ISSUE THREAD

**Issue by giovannipiller** [react-hook-form/react-hook-form#8430]
On version [7.30.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.30.0) it has been added support for determining checkbox group based on the defaultValues (#7938).

This however seems to be limited fields created via `register(...)` -> https://codesandbox.io/s/rhf-register-oef6f9-oef6f9

There are two more scenarios that would be nice to cover:

1. Setting up the [field `defaultValue` via `useController`](https://codesandbox.io/s/jovial-raman-1t681m?file=/src/App.tsx):
```
  const myField = useController({
    control,
    name: "firstName",
    defaultValue: []
  });
```

2. using [`useController` rather than `register` to setup the field](https://codesandbox.io/s/vibrant-fog-7dgx2t?file=/src/App.tsx:247-424):
```
  const { handleSubmit, control } = useForm<FormValues>({
    defaultValues: { firstName: [] }
  });

  const myField = useController({
    control,
    name: "firstName",
  });
```

Any thoughts?

**Comment by bluebill1049** [comment]
hey, @giovannipiller for the controlled components you could host your own local state, `Controller` or `useController` just a headless component or hook to collect and validate data. The same reason some of the additional props is not migrate to controlled, because when you build a controlled component, you are having the control already.

**Comment by giovannipiller** [comment]
Ok, thanks for the reply!
