### ISSUE TITLE
Controller with material-ui <TextField /> onChange event

### ISSUE THREAD

**Issue by NikolaStanisavljevic** [react-hook-form/react-hook-form#844]
Example: 

```
   <Controller
            as={<TextField />}
            name="firstName"
            control={control}
            onChange={{(data: any) => console.log(data.value)}}
   />
```
I'm trying to store user input without submit button and without the use of 
`handleSubmit()` function. Is that possible at this point ?
 I cant seem to get value of any field with `getValues()`,  and `setValues()` on change event is not working for me also.

**Comment by bluebill1049** [comment]
`TextField` MUI?

**Comment by JeromeDeLeon** [comment]
@NikolaStanisavljevic , `getValues` is one way to to do instead of manually tracking each field because `Controller` already tracked it inside and what you can do is have another trigger like a button that when clicked, it saved the values using `getValues({ nest: true })` if I'm understanding your question correctly.

May I know why you want to do that? so that we an look other options as well.

**Comment by bluebill1049** [comment]
i think you can use `watch()`

**Comment by NikolaStanisavljevic** [comment]
@bluebill1049 @JeromeDeLeon 
So far i do not have a solution for my prob using this library. Ill work more on this in upcoming days.
