### ISSUE TITLE
issue: Didn't focus  Automatically  to Narender text field when I enter autocomplete.

### ISSUE THREAD

**Issue by NarenderSiri** [react-hook-form/react-hook-form#8440]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/rkd1vt

### Expected behaviour

1.Go to uomCode text field . Enter min in that field. It is a Auto Complete field.
2.Click on Minutes in options of Autocomplete.It will Assign the **uomName field Value** and **description field value** and also **Append Next row**.
3. When I click on Minutes option then Autocomplete will be triggered . After that  **cursor not focused in UsefieldArray or Table**.
4.  When I click on Minutes option in Autocomplete .**how to set the focus automatically on Narender text field**.
5. please check my Video https://user-images.githubusercontent.com/48355455/171823748-cd33b28b-18f6-4df2-a3d0-c2758f4f601a.mp4

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
a lot of irrelevant files.

![Screen Shot 2022-06-03 at 8 20 29 pm](https://user-images.githubusercontent.com/10513364/171836227-3461a891-83b4-43b7-8974-c1676415fcd9.png)

> 1.Go to uomCode text field . Enter min in that field. It is a Auto Complete field.
>2.Click on Minutes in options of Autocomplete.It will Assign the uomName field Value and description field value and also >Append Next row.
>3. When I click on Minutes option then Autocomplete will be triggered . After that cursor not focused in UsefieldArray or >Table.
>4. When I click on Minutes option in Autocomplete .how to set the focus automatically on Narender text field.
>5. please check my Video https://user-images.githubusercontent.com/48355455/171823748-cd33b28b-18f6-4df2-a3d0-c2758f4f601a.mp4

does make sense to me with the steps above.

> i'm suffering with last 60 days for this problem...please check it...this is my humble request

If this is caused by react hook form, in my humble option I think you should consider the alternative. If what we made makes the developer suffer for 2 months, I don't think it's the right choice of lib for you.

### What next?

if your code sandbox and clean up all those unnecessary dependency and update with precise and clear steps to reproduce.

> issue: Didn't focus Automatically to Narender text field when I enter autocomplete. 

even the title makes very little sense to me as to what's the issue, please reword.

**Comment by NarenderSiri** [comment]
https://user-images.githubusercontent.com/48355455/172323616-8e835616-f67c-442b-abef-4be401ee4f18.mp4


[SampleCodeSandbox](https://codesandbox.io/s/reacttablefocus-5y0cby?file=/src/App.js)

please check above links.
