### ISSUE TITLE
Is behavior of useFieldArray after 4.5.5 correct?

### ISSUE THREAD

**Issue by iufd** [react-hook-form/react-hook-form#870]
Open https://codesandbox.io/s/react-hook-form-usefieldarray-jdwpm.
try to click append several times, then delete items.
In versions 4.5.6 and later values are regenerated after each delete click. In 4.5.5 values are not changed.

**Comment by bluebill1049** [comment]
This is a patch that i made over the weekend, if you remove `defaultValue` then you should get expected value. Reason is due to ref callback will not invoke existing node or you will have to do `register({})` for empty validation register. After careful consideration, i think DX is more important here, it's confusing to asking user to use `regsiter({})` vs `register`

**Comment by bluebill1049** [comment]
going to close this one, feel free to follow up with more questions.
