### ISSUE TITLE
issue: Required radio button value changes to null when reading formState

### ISSUE THREAD

**Issue by emilio-notable** [react-hook-form/react-hook-form#8720]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/relaxed-microservice-fm430q?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/relaxed-microservice-fm430q?file=/src/App.js
2. Click first Submit button twice
3. Current value changes from `""` (empty string) to `null`

If you do the same with the second Submit button, it keeps the value as an empty string

### Expected behaviour

I would expect the current value to be an empty string in both cases after submitting the form twice.

The only difference between both forms is that the first one is reading the `formState` (`formState: { isDirty }`).
Both have only one radio button input, registered as a required field, and with default value `""`

Let me know if the code sample makes sense. I tried to use as little code as possible (hoping it makes it easier to see the behavior i'm describing), but the actual use case where I noticed this was in a form with multiple radio buttons for the same field (ie: registered with the same name), and I wanted none of them to be selected by default, so that's why I used an empty string as `defaultValue`. I was also using `yup` to define the schema and validations, in particular this field was a `yup.string().required()`, so when the value changes to `null`, `yup` adds an error message saying `null` is not expected for this field

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Thanks for the detailed issue report.

This is expected behavior unselect native radio input will result in return for `null`, the first example works because you are subscribed to `formstate` (even tho you are subscribed to an irrelevant formate such as 'isDirty`) and flush down a re-render after submission. The second example results different because you are not subscribed to any `formState`, if you subscribe to `formState` errors which in your case is check for required, then the result will be the same. 

### Why

we are following the native radio input non-select value here which is `null`, this is the best solution we could come up with without further complexing the internal. As you can imagine, the radio/checkboxes are always the annoying ones. So following the standard is the best option we could follow. so none selected radio input will always return `null`, we are not going to check your defautlVaue supplied match with your value and etc.
