### ISSUE TITLE
Asynchronous validation pass overrides synchronous fail

### ISSUE THREAD

**Issue by joejknowles** [react-hook-form/react-hook-form#888]
**Describe the bug**
When an asynchronous validation passes, it overwrites a new synchronous fail. When there's a new synchronous error, it displays immediately, while the asynchronous validation is still running, but then when the asynchronous validation is complete, it overrides the synchronous one. It overrides it whether it's passing or failing. Doesn't matter as much if the async is also failing, but if the async passes then it hides the sync failure, making it look like there are no failures when there actually are. This is all during re-validation when `reValidateMode: 'onChange'`

**To Reproduce**
I've made a contrived example, where the sync validation passes on alternating validation triggers, but the async validation always passes after 1 second. So on the demo, you can see this bug every other keypress into the input if you type quickly (in revalidation state);

1. Go to https://codesandbox.io/s/react-hook-form-native-validation-2jpsw
2. Click submit to get the `required` validation
3. Quickly type two characters. After the second key press, the sync is failing. This failure displays for less than a second, then the async completes and overwrites the sync fail
4. See that there is no error message for the sync failure left after a second, but there should be

**Codesandbox link**
same as above
https://codesandbox.io/s/react-hook-form-native-validation-2jpsw

**Expected behavior**
The synchronous validation should not be overwritten by an asynchronous pass. An asynchronous validation request should probably be cancelled if the field already has an error and it's in "firstErrorDetected" mode

**Screenshots**
Two examples, the first is the above codesandbox demo, the next is my real world example.
![demo1](https://user-images.githubusercontent.com/10728145/72901491-c9f96000-3d21-11ea-9fc9-e48170452104.gif)

This is the real world example. There's an allowed characters validation, and a "duplicated username" validation. Here, after the second key press, the allowed character validation is failed by the "%" symbol, so the error message displays, but then the duplicated username validation passes, so the allowed character validation is overwritten.
![test](https://user-images.githubusercontent.com/10728145/72901505-d087d780-3d21-11ea-929c-56890630f0c2.gif)

**Desktop (think this is irrelevant, but...):**
 - OS: Windows 10
 - Browser Chrome
 - Version  79.0.3945.117

**Comment by bluebill1049** [comment]
i think you may need to debounce the validation.

**Comment by joejknowles** [comment]
I've tried this and get two other issues. If `debounce` has the `{ leading: false }` option, then it fixes this issue ^ but the validation no longer runs on submit. If `{ leading: true }` then it works on submit but the original issue ^ of overriding sync validations is just the same as described above.

Please take a look at the code sandbox, it shows this issue with quite a simple example. https://codesandbox.io/s/react-hook-form-native-validation-2jpsw

I haven't taken a close look at the source code yet, but it seems like we're not separating validation into batches properly. I think that what happens as a result of the validation caused by *an earlier* key press should never overwrite what happens  as a result of the validation caused by *a later* key press.

**Comment by bluebill1049** [comment]
Sure i haven't look closely enough with this issue, but i will after some of the bugs get resolved.

**Comment by bluebill1049** [comment]
what about this solution? https://codesandbox.io/s/tutorial-base-done-7ge59

**Comment by bluebill1049** [comment]
is the above solution works for you?

**Comment by martdavidson** [comment]
Doesn't seem to do the trick for me @bluebill1049 

```
validate: {
      specialCharacters: displayName =>
        meetsAlphaNumericRequirement(displayName) ||
        'The display name can only contain alpha-numeric characters.',
      unique: debounce(checkForUserWithSameDisplayName, 400),
    },
```

`specialCharacters` is synchronous. Let's say there is **not** already a user named Bill in the database. If I quickly type `Bill$`, I'll see the `specialCharacters` error message, but 400 ms later the `unique` validator resolves (it's an async request, debounce returns a promise), and because `Bill` is an available username, the `specialCharacters` error is replaced.

**Comment by martdavidson** [comment]
@bluebill1049 Can you take another look at this?

The _synchronous_ validation returns false, and an error is shown. Then  _asynchronous_ validation resolves and returns true. The error state is now cleared.

Your codesandbox example doesn't have a synchronous validator. Something like:

```
validate: {
      specialCharacters: displayName =>
        meetsAlphaNumericRequirement(displayName) ||
        'The display name can only contain alpha-numeric characters.',
      unique: debounce(checkForUserWithSameDisplayName, 400),
    },
```

`unique` will _always_ resolve after `specialCharacters`, so it doesn't matter what the result of `specialCharacters` was, `unique`'s result will always overwrite it.

In this case, if I enter `Bill$`, `specialCharacters` fails and shows an error, and `unique` is _not_ called with `Bill$` because the criteria is set to `firstErrorFound`. **But** `unique` _will_ fire with just `Bill` at this point, because that was the last value it was called with, and the debounce delay is triggered.

So one path I went down was to call `getValues()` inside of `checkForUserWithSameDisplayName` to get the value of the `displayName` field _at the time that the debounce triggers_ and then call `meetsAlphaNumbericRequirement()` _again_ at the top of that function like so:

```
async function checkForUserWithSameDisplayName(displayName // we actually don't even use this anymore) {
    if (!meetsAlphaNumericRequirement(getValues().displayName)) {
      return 'The display name can only contain alpha-numeric characters.';
    }
   // check uniqueness
}
```

This works, but then the `type` of the error is `unique`, not `specialCharacters`, if you care about that.

Ideally there'd be a way to maybe return undefined from a validator, which would act as though it had never been called, and the previous state of the form would remain.

**Comment by alexpanov** [comment]
@bluebill1049 this seems like a common use case. Please comment.

**Comment by xgemelaj** [comment]
@bluebill1049 could you open an issue or comment for @martdavidson comment
