### ISSUE TITLE
issue: useFieldArray rules 'minLength: 1' not respected

### ISSUE THREAD

**Issue by rowrowrowrow** [react-hook-form/react-hook-form#8933]
### Version Number

7.35

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-usefieldarray-rules-iyejbp?file=/src/index.js

### Steps to reproduce

1. Go to the sandbox list on the useFieldArray page (https://react-hook-form.com/api/usefieldarray): https://codesandbox.io/s/react-hook-form-usefieldarray-rules-iyejbp?file=/src/index.js
2. Delete the first value of the array
3. See that no error is shown

### Expected behaviour

I expect that setting minLength = 1 would throw an error if the array length is not equal to or greater than 1. It seems that setting a rule of minLength = 1 is not respected. 

NOTE: 

Setting required = true accomplishes the expectation of setting minLength =1. I would expect that the required validation would check whether or not the value is an array or at the least truthy. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
This is the expected behavior since RHF is trying to follow the web standards as close as possible.

The native web input `minLength` validation behaves in the same manner: check out [the W3Schools `minLength` attribute example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_minlength).

The solutions is as you describe: to add the `required` attribute along with `minLength`
