### ISSUE TITLE
useController() returns a stale value when form is reset in the same update as it is rendered into DOM

### ISSUE THREAD

**Issue by panta82** [react-hook-form/react-hook-form#9158]
### Version Number

7.36.1

### Codesandbox/Expo snack

https://codesandbox.io/s/beautiful-engelbart-hzi221?file=/src/App.tsx

### Steps to reproduce

1. Go to [code sandbox thingy](https://codesandbox.io/s/beautiful-engelbart-hzi221?file=/src/App.tsx)
2. Enter something in the text box
3. Click on "Show then reset"

The button will:
- call `form.reset` with the entered value
- switch a flag that will cause the form to be rendered

### Expected behaviour

**Expected:** The form's `useControler().field.value` reflects what was entered in the text box
**Actual:** The field remains stale

If you click the other button, the form updates correctly. I believe the difference is in the order of operations. Reset form then show, vs show then reset form.

I believe this regression was introduced in #7056, with optimizations not to subscribe to form changes in the first render.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
> I believe this regression was introduced in https://github.com/react-hook-form/react-hook-form/pull/7056, with optimizations not to subscribe to form changes in the first render.

This is not a regression, that was a bug fix was cause potential cause issues with react strict mode, subscription will need to be set up at `useEffect`.

This issue is not related to `defaultValues` update

why this is happening: this is because the child component will always execute before the parent component. `reset` did update the `defaultValues` correctly, however, due to the re-render `setShow(true)` ahead of time, `useController` captured the updated value and retained as updated value. The second restrict go to `useWatch` child component execution order:

<img width="911" alt="Screen Shot 2022-10-07 at 8 42 18 am" src="https://user-images.githubusercontent.com/10513364/194423907-8cf3a930-68a3-4d8c-9c1f-4dca9f2056aa.png">
