### ISSUE TITLE
Impossible to obtain the values of uncontrolled nested inputs (?)

### ISSUE THREAD

**Issue by prog13** [react-hook-form/react-hook-form#922]
**Describe the bug**
Not sure if bug or intended behaviour, but here goes: it's impossible to consistently obtain the values of uncontrolled nested inputs.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-8tklv
2. Click on 'append'
3. Type something to the new input or the default input
4. Notice how 'input length' counter doesn't change

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-8tklv

**Expected behavior**
Every newly appended or existing input should properly update its value in the 'fields' array.

**Additional context**
This case could be _kinda_ solved with 'watch', but then there's another issue arises - 'fields' get updated only when next input appended.

If there's another way to crack this case - I'd be very happy to know it.

**Comment by bluebill1049** [comment]
you may have to do the following:

https://codesandbox.io/s/bold-sound-7lej4

I think there is some fundamental difference between controlled FieldArray. I guess it's a trade-off with uncontrolled. If you need to consistently update field value and amount of inputs, I would recommend using controlled, while uncontrolled give you the benefit of better performance because not all input's onChange will trigger re-render.

**Comment by bluebill1049** [comment]
It's also related to this issue: https://github.com/react-hook-form/react-hook-form/issues/919

**Comment by bluebill1049** [comment]
i will update the website FAQ section soon with this question as well.

**Comment by prog13** [comment]
Controlled inputs definitely allow for more precise control over the form data, I'll implement that. But there's much less code with uncontrolled 😸

Thanks for the tip!

**Comment by bluebill1049** [comment]
I wouldn’t say controlled is more precise. Uncontrolled input are what browsers made us for. However if u want to read each inputs and re-render each time and be in sync with the state not just the inputs values, then it make sense to go controlled, because u want to control and monitor the changes not only inputs value but also amount of inputs. Personally I prefer uncontrolled as it’s more nature for me towards the web standard and less performance impact to your form or application and also reason why I have decided to build such library. Hope these make sense 👍 happy coding
