### ISSUE TITLE
Form won't trigger onSubmit upon press enter in textarea

### ISSUE THREAD

**Issue by muhaimincs** [react-hook-form/react-hook-form#936]
Please consider answer the question at spectrum channel.

https://spectrum.chat/react-hook-form/help/submit-form-on-textarea-keypress-enter-event~e18bc0a1-d013-4828-895c-2eb00908b00f

**Describe the question?**
I have a `textarea` in the form and I want to trigger the form `onSubmit` when user press Enter

```html
<textarea
       name={variable}
       ref={register}
       onKeyPress={handleUserKeyPress}
       rows="4"
       defaultValue={submittedValue}
/>
```
 and here is the `handleUserKeyPress` function
```js
const handleUserKeyPress = e => {
    if (e.key === "Enter" && !e.shiftKey) {
      // e.preventDefault();
      handleSubmit(onSubmit); // this won't be triggered
    }
};
```

**Comment by bluebill1049** [comment]
`handleSubmit(onSubmit)();`

**Comment by diamantisufi** [comment]
> `handleSubmit(onSubmit)();`

 This works, but I'd like to know what is going on behind the scenes with the ( ) addition?

**Comment by Jersonquinterolopez** [comment]
> `handleSubmit(onSubmit)();`

It doesn't work form me, this is my code: 

`.
 if (enterKeyIsPressed && isValid) {
      e.preventDefault();
      if (formStep === 3) completeFormStep();
      if (formStep === 4) completeFormStep();
      if (formStep === 5 && isMortgageCredit) completeFormStep();
      if (formStep === 5 && !isMortgageCredit) {
        handleSubmit(onSubmit)();
      }
      if (formStep === 6 && isMortgageCredit) {
        handleSubmit(onSubmit)();
      }
    }
`

**Comment by akomm** [comment]
I often don't want to wrap things in form. For example I don't want wrap the Dialog in Material UI with form, just so that the action buttons with type="submit" allows submitting via "enter". I just have my `handleSumibt(onSubmit)` as onClick on the submit button and no form at all. Now I could do this keyPres handling and manually trigger, but should the control from `useForm` not be able to do the same thing without all the mess of handling keypress? Could be a `useForm` option to enable "submit on enter" or it might make sense to have it on per control basis (to exclude textarea)

**Comment by Jawmo** [comment]
Any solution to this? I am seeing this as well and handling the keypress seems like a janky fix.

**Comment by sheyDev** [comment]
GUYS! Can anyone please tell me why this handleSubmit(onSubmit)(); works?
I've never seen this before, thank you!
