### ISSUE TITLE
issue: useWatch with `control` sets Typescript property types as nested Partial

### ISSUE THREAD

**Issue by Kersheh** [react-hook-form/react-hook-form#9400]
### Version Number

7.39.4

### Codesandbox/Expo snack

https://codesandbox.io/s/usewatch-typescript-type-error-qjcmqo?file=/src/App.tsx:1065-1101

### Steps to reproduce

1. Configure `useForm` with generic form type defining concrete form value types (i.e. form values are not `undefined`)
2. Use `useWatch` with ` control` provided by return of `useForm`
3. See values of `useWatch` appear as a nested Partial type (see line 51 of Codesandbox example)

### Expected behaviour

Typescript form type defined as such with configured `useForm` and `useWatch`

```tsx
interface FormValues {
  array: Array<{
    name: string;
  }>;
}

...

const { control } = useForm<FormValues>({ defaultValues: { array: [] } });
const { array } = useWatch({ control });

// type should be `Array<{ name: string }>` and not `Array<{ name?: string }> | undefined`
array.length; // Incorrectly displays --> Object is possibly 'undefined'.
```

and IDE should properly represent type as non-nested Partial when utilizing `useWatch`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
At the moment `defaultValues` itself is deep partial because it's possible to supply the entire form `defaultValues` or even don't supply at all, however, this is something we may change in the next major version, which could force the user to supply a none deep partial `defaultValues`, but this will be ba a breaking change for the better.
