### ISSUE TITLE
Issue with Typings when passing `register` as a prop

### ISSUE THREAD

**Issue by mthines** [react-hook-form/react-hook-form#942]
**Describe the bug**
I've created two components, Form and Input. The form initializes the Form Hook, and passes it to it's component prop (children). When I pass the register prop from the Form component, to the input field I get a type error, even though I'm using the same types.

If I set the type of the `register` in the `InputField` to `any`, it works correctly, but then it's not typed.
I could also set `register as any` when using the `InputField`, but that would require me doing that on every input field, which is NOT ideal.

**To Reproduce**
1. Create Two Components, Form and Input.
2. Pass down the `register` prop from the Form to the Input field

**Codesandbox link**
https://codesandbox.io/s/friendly-vaughan-p0srl?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
I expect the types not to fail, as I'm refering to the same one.

**Screenshots**
![image](https://user-images.githubusercontent.com/16097850/73516594-3a2a7480-43f9-11ea-99da-73e6446d5dd5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, WSL
 - Browser: Chrome
 - Version: Version 79.0.3945.130 (Officiel version) (64-bit)

Thanks for the help.
Let me know if I can help with something :)

**Comment by bluebill1049** [comment]
can you please provide a valid CSB? it's broken.

**Comment by mthines** [comment]
Aah, I realized the React version was too low in CSB, so the Hooks weren't supported.
I've updated now :)

Thanks!

**Comment by bluebill1049** [comment]
hey @stramel would you be able to help this one?

**Comment by stramel** [comment]
Will take a look in the morning. Not seeing the error in CSB. I did notice the `errorMessage` prop is incorrectly being put on a HTML `input`. 

Also, instead of passing the `register` function, it would be better to set the `ref` on the `InputField` then do a `forwardRef` on the `InputField` to the HTML `input`.

Lastly, minor note, it's best to not use `React.FC` in favor of explicitly defining your props.

**Comment by mthines** [comment]
In my code (not the CSB), the `errorMessage` has been deleted and been replaced with the string coming from the error type, and it's not really what's causing the problem here. But you're right.

Can you elaborate on why it would be better to pass it as a ref?

I'm also curious why you write it's best not to use `React.FC`. Can you elaborate on this as well?

**Comment by bluebill1049** [comment]
thanks @stramel a lot :)

**Comment by stramel** [comment]
@mthines Sorry for the delay.

Now that I'm at my computer and not on my phone, I can see the error in the CSB. The actual issue is that you define in the `Form` component that the `Props` has `register` defined as such `register?: FormContextValues["register"];`. This means `FormContextValues["register"] | undefined`. However, in `InputField` you define the incoming prop as such `register: FormContextValues["register"];`, meaning that `undefined` is invalid. So to address this, you should either check that `register` is defined before passing it to the `InputField` or adjust the `InputField` props to allow an `undefined` value.

> I'm also curious why you write it's best not to use React.FC. Can you elaborate on this as well?

Here is a good description of the Pros/Cons of it. https://github.com/facebook/create-react-app/pull/8177#issue-353062710 At my company, we no longer use it and haven't had any issues. 

> Can you elaborate on why it would be better to pass it as a ref?

One of the biggest benefits is flexibility. You would now have the ability to customize the register arguments on each `InputField` without having to add an additional prop to handle it. Additionally, you don't have to pass the `register` prop down to the `InputField`. This helps separate concerns as well.

```jsx
<InputField ref={register({ required }) label="Name" name="name" id="name" />
```

However, you could just as easily add custom validation to it without modifying the `InputField`.

---

The rest of this is just a few minor things that I noticed when looking at the CSB. Take what you want from it, just offering up some advice:

- Utilize FaaC (Function as a Child): Instead of passing `component` prop to `Form`, utilize the `children` prop. This is a personal preference, feel free to ignore.

```jsx
<Form onSubmit={myHandler}>
	{({ register, unregister, errors }) => (
		<InputField ref={register({ required }) />
	)}
</Form>
```

To do this, just have to call `children` as a function 

```jsx
<form>
	{children && children({ register, unregister, errors })}
</form>
```

- Utilize the rest accumulator: Instead of passing an object of options as a prop to the `Form` just allow them to be props.

```ts
const Form = ({
  component: Component,
  onSubmit,
  ...useFormOptions
}: Props) => {
  const { errors, unregister, handleSubmit, register } = useForm(useFormOptions);
```

**Comment by stramel** [comment]
Closing as it appears to be an issue with your `Props` type definition. Please let us know if this isn't resolved.

**Comment by bluebill1049** [comment]
thanks @stramel a lot 👍

**Comment by ivan-kleshnin** [comment]
> Also, instead of passing the register function, it would be better to set the ref on the InputField then do a forwardRef on the InputField to the HTML input.

@stramel I think `forwardRef` is an antipattern. For example, you don't know if the field was required or not inside an element:

```js
let TextInput = React.forwardRef(({name, label, error}, ref) => {
  // ...can't know whether it was required...
  return <div>
    <label>
      {label} (isRequired ? "*" : "")
```

unless you duplicate that information in a separate prop. 

```js
<TextInput required={true} ref={register({required: true})/>
```

Same logic can be applied to other information that you pass to `register`.
