### ISSUE TITLE
issue: field.onChange(undefined), but field.value isn't undefined

### ISSUE THREAD

**Issue by j-xzy** [react-hook-form/react-hook-form#9617]
### Version Number

7.41.0

### Codesandbox/Expo snack

https://codesandbox.io/s/red-grass-firxvq?file=/src/App.tsx

### Steps to reproduce

1. type some number in input
2. double click "toggle button" and input reappears
3. clear input
4. the number reappear

### Expected behaviour

4. the number don't reappear

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by j-xzy** [comment]
> thanks for the issue report @j-xzy
> 
> > Important: Can not apply undefined to defaultValue or defaultValues at useForm.You need to either set defaultValue at the field-level or useForm's defaultValues. undefined is not a valid value.If your form will invoke reset with default values, you will need to provide useForm with defaultValues.
> 
> https://react-hook-form.com/api/usecontroller
> 
> for a controlled component is required to provide a non-undefined value, or you will get a warning from react as well.

So 'field.onChange(undefined)' is wrong invoke?

**Comment by bluebill1049** [comment]
Going to close this issue, free free to leave more questions here as well.

**Comment by nitedani** [comment]
I'm having an issue with this. My use case is the following:
1. User opens the page with the form. The form has `defaultValues` set, using data from the server.
2. User clicks the "X" clear button on a field and expects it to clear, but instead it will reset to the value set in `defaultValues`

The workaround is to call `onChange(null)` instead of `onChange(undefined)` when the user clicks the "X" clear button.

If I remove the `defaultValues` parameter from the `useForm()`, then `getValues()` will return `undefined` values, which I think makes the developer experience inconsistent.
