### ISSUE TITLE
issue: Is that common behavior when "shouldUnregister: true" removes empty arrayFields after "reset(data)"?

### ISSUE THREAD

**Issue by igoryusha** [react-hook-form/react-hook-form#9674]
### Version Number

7.40.0

### Codesandbox/Expo snack

https://codesandbox.io/s/dawn-bash-wboprf?file=/src/App.tsx

### Steps to reproduce

Empty array is deleted from form, after first submit, so when we send data 2nd time we lost arrayFields.
1. Go to [codesandbox](https://codesandbox.io/s/dawn-bash-wboprf?file=/src/App.tsx)
2. Click on submit button
3. Open console

BTW, whats wrong with example? `input` with array item is empty somehow.
1. Uncomment default value
2. Reload example
3. Input with text is empty

### Expected behaviour

Empty array is not deleted from form, after first submit, so when send data 2nd time we still have arrayFields.
1. Go to [codesandbox](https://codesandbox.io/s/dawn-bash-wboprf?file=/src/App.tsx)
2. Click on submit button
3. Open console
4. Array data submitted two times

BTW, whats wrong with example? `input` with text is empty somehow.
1. Uncomment default value
2. Reload example
3. Value is - "Default text"

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
That's an expected behavior as there's no such input as `fieldArray` in the form. While you can group / structure your data with nested objects / arrays, RHF can only "recognize" registered inputs in the form: the ones connected with `register` or `Controller` API. `shouldUnregister` flag enables RHF to remove unregistered data entries as the flag name suggests

**Comment by igoryusha** [comment]
@Moshyfawn 

oh, ok.
