### ISSUE TITLE
Release v8-alpha.5

### ISSUE THREAD

**Issue by marcospassos** [react-hook-form/react-hook-form#9866]
It has been a long time since v8-alpha4 was released (April 2022). Because of the several typing improvements, we've been using the v8 since then. Over the last months, many cool features and fixes have been merged into the v7 branch.

Any chances of rebasing the v8 with these changes and releasing the next.5? It'd help the teams using the v8 a lot.

**Comment by PFJoey** [comment]
We currently are using v7 where we are running into the circular dependency issue with RHF. Currently all circular dependency TSX files require a ts-nocheck in order to prevent Typescript from stalling during build and intellisense lookup.

Having an updated v8 or fixed v7 for circular dependencies would be a massive improvement to the developer friendliness of this package.

**Comment by bluebill1049** [comment]
Not at this stage to continue with v8, as it has a breaking change from TS, I believe the issue introduced after 4.9 was not been able to resolve. Maybe TS v5 will help this issue, but it's not the priority right now.
