### ISSUE TITLE
v7 Circular dependency

### ISSUE THREAD

**Issue by PFJoey** [react-hook-form/react-hook-form#9884]
Currently, the v7 version of RHF does not support circular dependencies and hasn't supported it for quite some time. As many (including our) companies make extensive use of "advanced" types instead of arbitrary types this proves troublesome to say the least.

As we use RHF for our SaaS and more products to come, this feature deems to be of high importance. Are there any ways for us to support the team at RHF to prioritize this issue in v7? May it be through donations or supplied developers. 

The "workarounds" that have been mentioned in other posts are not geared towards longevity and developer friendliness (Omitting / Usage only arbitrary types) and require a lot of rework. Especially seeing as when this gets fixed all can be rollbacked.

We would love to have a more intimate relationship to support this Typescript endeavour and get to a good solution (albeit another workaround that works better and doesn't compromise on a lot of the problems stated above).

This may not be the correct place to post said issue, apologies if that's the case. I will repost it somewhere else if needed.

Many thanks in advance from my team!

**Comment by bluebill1049** [comment]
Could you please follow the feature request template?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
