### ISSUE TITLE
issue: setValue with Controller/useController trigger watch callback 1 extra call

### ISSUE THREAD

**Issue by sunkeysun** [react-hook-form/react-hook-form#9952]
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-usewatch-forked-s61b4h?file=/src/index.js

### Steps to reproduce

1. Go to "codesandbox"
2. Click on "CLICK" button
3. open "codesandbox" console
4. view watch callback trigger log

### Expected behaviour

setValue trigger watch callback only one time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I had a close look at this, I think I may skip improving on this. When `setValue` is invoked, we flush down a render for the watch to return the updated value, however, because setValue support nested object, and in order to send value update to exact controller input, we trigger re-render on each individual one of them. Hence there is an extra invocation on the watch, we can do extra logic to prevent this, but I don't think this is worth the effort at the moment. Unless you can provide a concrete use case, which we may consider support. So expect `watch(() => {})` will get multiple times, as you provided, i can update the doc to reflect this as well.

**Comment by Moshyfawn** [comment]
Yea, I don't feel like we need to chase down render optimizations at this stage.
