### ISSUE TITLE
React Select with Controller - sending only id instead of object

### ISSUE THREAD

**Issue by fjuriolli** [react-hook-form/react-hook-form#997]
I'm using react-select with Controller and its absolutely amazing, but I have a question, right now I'm sending the whole object, but I want to send only the id, how can I do that?

OBS: in my onChange function, if I do this I am able to send only the id, but then my select can't load properly, because its missing the label:
`
onChange={([selected]) => {
 return { value: selected.value };
}}
`

Code sandbox below:
https://codesandbox.io/s/react-hook-form-rhfinput-3n3bi

**Comment by bluebill1049** [comment]
hey @fjuriolli we don't have the mechanism to filter out what's returned by the external component. I personally would leave as what external component return, because it would make your life easier when you try to set `defaultValue` as well.

**Comment by fjuriolli** [comment]
@bluebill1049 the default value is working, because, in my api, I need to send only the id and only the id is returning to me. So, in my default value, I do a map in my options array (it does have value and label).

So, my controller input is like this;
`
<form onSubmit={handleSubmit(onSubmit)}>
        <Controller
          as={<ReactSelect placeholder="All" options={options} />}
          name="food"
          control={control}
          onChange={([selected]) => {
            return { value: selected };
          }}
          defaultValue={
            options.map(option => {
               return something === option.value ? option : ' '
           })    
        />
        <button>submit</button>
      </form>
`

The default value is working fine, but again, I need to send only the id and not the whole object, what is the best way that I can do that? I tried with setValue and didn't work, seems like the setValue for this input is his value, in this case, the whole object.

**Comment by bluebill1049** [comment]
I think you can either create a wrapper around `react-select`, or transform the data inside the `handleSubmit`.

**Comment by fjuriolli** [comment]
@bluebill1049 oh I see, how can I transform the data inside handleSubmit, can you give me an example? Cuz I thought I could't change the data inside handleSubmit

**Comment by bluebill1049** [comment]
@fjuriolli can you do the following?

```
const transform = (data) => {
  return ; // do your transform here?
}

handleSubmit(transform(onSubmit));
```

**Comment by fjuriolli** [comment]
@bluebill1049 can you take a look at https://codesandbox.io/s/react-hook-form-rhfinput-fecgd

I'm getting an error implementing the transform that you mentioned

**Comment by bluebill1049** [comment]
take a look this: sorry that was my bad above: https://codesandbox.io/s/react-hook-form-rhfinput-ux999

**Comment by fjuriolli** [comment]
@bluebill1049 thank you for your attention, I got it working, all good now

**Comment by bluebill1049** [comment]
my pleasure @fjuriolli

**Comment by bennettrogers** [comment]
I was trying to do something similar: I want the form values that I send to my API to be as simple as possible, and that means using values/IDs/slugs instead of an entire object from something like React Select. I was having trouble getting it to work, but then I saw @bluebill1049's suggestion to wrap React Select in an intermediate component. That seems to do the trick, but it requires an odd hack:

As discussed, React Select expects the value that it receives to be an object with a shape that mirrors the options. I can create this object in my wrapped component before passing it to React Select, but the Controller from RHF appears to clobber the inner value with the form value (which is just a string). My hack/solution is to set the valueName prop in Controller to something (anything) else so that RHF doesn't clobber the input.

@bluebill1049  - is there anything wrong with doing this? Do you have a better suggestion?

[Here's a CodeSandbox](https://codesandbox.io/s/react-hook-form-select-example-wf2ym) that demonstrates a working version with the hack. If you remove the `valueName="somethingOtherThanValue"` line from the Controller it will stop working.

Thank you for building React Hook Form. It's been a pleasure to use!

**Comment by bluebill1049** [comment]
i will take a look @bennettrogers

**Comment by bluebill1049** [comment]
`valueName` is made for prop which is not named as `value`, for example: `checked`.

<img width="916" alt="Screen Shot 2020-02-24 at 10 39 34 am" src="https://user-images.githubusercontent.com/10513364/75122483-f8d46e80-56f1-11ea-9000-8ad65a306ff0.png">

@fjuriolli do you have a working example that you could share?

**Comment by bennettrogers** [comment]
Yes. In this case though I think I'm using `valueName` in an unintended way to achieve a result I need. 

The problem is that I want the form value stored in RHF to be e.g. a simple string, but React Select expects a prop called `value` that is the entire selected option value. If I store a string value in RHF, even if I then translate that string to an object value to pass to the React Select props, the native `<input>` tag inside React Select seems to be receiving the original simple string from RHF. My guess is that even though I'm passing React Select an object in its `value` prop, RHF is overwriting the value handed to `<input>` with its internal copy. But by faking out RHF by telling it the wrapped component expects the value to come from a prop with a different name, I can prevent it from clobbering the value. This allows React Select to work with the `value` that I give it manually.

It seems to work, I just don't know if there are going to be any unfortunate side effects, or if there's another way to tell RHF to let me manage the value given to the wrapped component myself.

**Comment by bluebill1049** [comment]
can you try the following?

```
<Controller as={<ReactSelect />} onChange={(data) => {
  setValue('xxx', data.value)
  return data;
}} />
```

**Comment by bennettrogers** [comment]
[Here's](https://codesandbox.io/s/react-hook-form-select-example-2-j8qdm) a CodeSandbox trying that suggestion (let me know if this isn't what you meant).

This doesn't seem to work quite right since the form value is now the full object instead of just the slug string.

**Comment by bluebill1049** [comment]
here you go: https://codesandbox.io/s/xenodochial-water-mvhbq

**Comment by fjuriolli** [comment]
I'm using like this: https://codesandbox.io/s/react-hook-form-rhfinput-2f4rn

I send only the id, and when I receive the id from my api, I need to load my select with the object, I do something like this: 

```
<Controller
  as={<ReactSelect placeholder="All" options={options} />}
  name="food"
  control={control}
  onChange={([selected]) => {
    return { value: selected };
  }}
  defaultValue={options.forEach(food => {
    if (idFromApi === food.value) {
      return food
    }
  })}
/>
```

**Comment by bennettrogers** [comment]
Neat, that seems to be working, but I don't understand how! I see that the Select component is getting its value from the `selectedOption` state, but `setSelectedOption` is never getting called. Where is the magic happening?
